### ISSUE TITLE
[2.7.3] tmpdir doesn't work on Windows under tox

### ISSUE THREAD

**Issue by alex** [pytest-dev/pytest#1010]
py.test 2.7.3 changed it so that `tmpdir` ends up in a folder named `pytest-{user}` (https://github.com/pytest-dev/pytest/compare/2.7.2...2.7.3#diff-88a6976d3a46c4b9625271f78ccde817L46)

On Windows the only way to get the username is the environment variable `USERNAME`, whereas on UNIX there is the `pwd` module. By default, `tox` does not allow environment variables to passthrough.

The result is that if you use py.test under tox on Windows with `tmpdir`, you get a traceback: https://jenkins.cryptography.io/job/cryptography-master/TOXENV=py26,label=windows/1289/console

**Comment by alex** [comment]
This could be fixed by `py.test` catching that exception and having some fallback (I don't know what), or by `tox` adding `USERNAME` to the default `passenv`, or something else I haven't thought of.

**Comment by untitaker** [comment]
@alex I don't think you intended to close this.

**Comment by alex** [comment]
I really did not. I don't even know how I did.

**Comment by The-Compiler** [comment]
A possible alternative would perhaps be to generate a random suffix with each invocation, or to just use `pytest` without username as basedir.

I think it'd be better to fix this in pytest itself - requiring the newest version of tox so pytest works on Windows is somewhat unfortunate.

@alex it was closed because of the "resolves pytest-dev/pytest#1010" in the commit message, which is one of the possibilities to close an issue via commit message. Totally not what you intended in that case, of course :wink:
