### ISSUE TITLE
pytest.mark.asyncio with pytest.mark.parametrize may break async #379

### ISSUE THREAD

**Issue by SamShao-crypto** [pytest-dev/pytest#10103]
when i use pytest.mark.asyncio with pytest.mark.parametrize，the async logic break

**Comment by SamShao-crypto** [comment]
![image](https://user-images.githubusercontent.com/107017136/177235549-fa3cbe93-52b0-4770-b809-0ec73954355d.png)
total exhaust 6 sec，but expected lower than 6 （which is the time spending for serial）

**Comment by SamShao-crypto** [comment]
pytest                     7.1.2
pytest-asyncio             0.18.3

**Comment by Zac-HD** [comment]
See https://github.com/pytest-dev/pytest-asyncio - this is the expected behaviour, because each test is run *serially* - using asyncio internally, but finishing each test before moving on to the next.  Otherwise you could get a variety of confusing false alarms if your tests wanted some resource simulatneously, in a way which probably wouldn't reproduce if you re-ran just the failing test.

**Comment by SamShao-crypto** [comment]
thx！

**Comment by SamShao-crypto** [comment]
em actually i just want to get test result seperately  by using pytest.mark.parametrize（or other feature） but also with async，is there any other solution for it？ @Zac-HD

**Comment by Zac-HD** [comment]
I'm not sure what you mean by that, but suggest asking on stack overflow and if that fails opening an issue on pytest-asyncio.
