### ISSUE TITLE
Can TerminalReporter support unicode?

### ISSUE THREAD

**Issue by edsion1107** [pytest-dev/pytest#10310]
```python
@pytest.fixture(params=["风行频道"])
def enter_channel():
   ...

def test_fengxing(enter_channel):
  ...
```
![image](https://user-images.githubusercontent.com/1925286/191253039-6b3c6ba8-29d3-4288-83b6-4369e6ab92c7.png)

I'm trying to use fixture with params. But terminalReporter doesn't seem to support unicode. Any good suggestions over there?

**Comment by RonnyPfannschmidt** [comment]
test ids get escaped due to unicode charactes in them pretty much blowing up lots of things that integrate them in a non-unicode aware way (yay for filesystem encodings and envronment encodings)

currently there is nobody working on fixing this

there is a flag for allowing this and forfeiting all support for those reasons and a older issue around that as well

**Comment by Zac-HD** [comment]
Closing because of https://github.com/pytest-dev/pytest/issues/9037 😢
