### ISSUE TITLE
Alternative approaches for `PytestReturnNotNoneWarning`

### ISSUE THREAD

**Issue by cliffckerr** [pytest-dev/pytest#10465]
Like others ([here](https://github.com/pytest-dev/pytest/issues/10427) and [here](https://github.com/pytest-dev/pytest/issues/10421)), I was surprised with the new warnings in pytest 7.2 when test functions return values other than `None`. Dating since the original issue (https://github.com/pytest-dev/pytest/issues/7337), there was quite a bit of debate about whether this was a good idea. 

Personally, making something raise an exception not because it's an error, but simply because some users may get confused by it, feels somewhat inconsistent with other decisions made in Python. For example, these Python "[gotchas](https://docs.python-guide.org/writing/gotchas)" _could_ raise exceptions, but don't, because sometimes you do actually mean to do these things -- as is the case with returning non-`None` from a test.

I'd propose to (a) keep the warning, but leave it as a warning indefinitely (so `filterwarnings` can be used), and/or (b) add a config flag under the `pytest-warnings` section for `--allow-return-not-none`.

**Comment by nicoddemus** [comment]
Seems reasonable.

We are following `unittest`'s in this topic, if they keep it always a warning, we definitely should follow suit.

**Comment by RomeshA** [comment]
I'd be in favor of keeping it as a warning too. While having tests return values something other than `None` might be a questionable practice, it doesn't actually make the test invalid, there isn't actually anything wrong with the test and it can be used with `pytest` just fine. Displaying a warning rather than raising an error is in keeping with the purpose of assisting the user - helping them in case what they wrote isn't what they intended, but staying out of the way if it _is_ what they intended

**Comment by Kodiologist** [comment]
Making this an error would be problematic for [Hy](https://github.com/hylang/hy), which implements implicit returns, so e.g. a test that ends with a function call will pass on whatever the function returns, not `None`. Having to add a lot of trailing `None`s just to keep pytest happy would be silly.

**Comment by yifeim** [comment]
This took me by surprise. I thought something was wrong in my [codes](https://github.com/awslabs/crowd-coachable-recommendations). I would appreciate a simple option to silence these warnings for previously published codes. Better yet, the pytest team could be a little more considerate of its users by telling us that this was a new change that they introduced as of <version number@date>.

**Comment by xapple** [comment]
To solve the issue this silly warning is causing I just wrap the `return` statements of my functions like this:

         if "pytest" not in sys.modules: return result

**Comment by jrounds** [comment]
I feel this warning is overly opiniated, but a more constructive criticism is the warning prints the value of the return which in certain binary data cases can make bamboo logs unreadable due to text spam.  It seems like it shouldn't print the value of the return because pytest is not prepared to properly format all possible return values.

**Comment by RonnyPfannschmidt** [comment]
@jrounds this is primarily about helping people to avoid grave mistakes that are observable in the wild

The typical case for those is devoid of other tools that help as its precisely for the aspiring test writer that is not yet up2date with all the surrounding best practise

Im happy to discuss ways to make this easier for people that know what they are doing

But it's going to be hard to just get me to agree on removing footgun safely for people that don't know or only think they know

**Comment by Kodiologist** [comment]
What footgun are we trying to protect against, though? Is the concern that users will return an expression instead of `assert`ing it as they meant to? That should be the kind of thing one catches by just checking that the test fails when it should fail and succeed when it should succeeds, which is something one needs to do anyway because it catches a lot of other basic mistakes.

**Comment by RonnyPfannschmidt** [comment]
Beginners don't always fit what you believe ough to be

**Comment by The-Compiler** [comment]
Let me note that Python's unittest.py does the same too: https://github.com/python/cpython/issues/85494 (I believe this was one of the original motivations for pytest to follow).

As for:

> Im happy to discuss ways to make this easier for people that know what they are doing

I feel like an `filterwarnings = ignore::pytest.PytestReturnNotNoneWarning` is already rather trivial?

**Comment by xapple** [comment]
Where would you put the string `filterwarnings = ignore::pytest ...`, inside the pytest configuration file? I'd like to be able to solve this issue.

**Comment by The-Compiler** [comment]
Yes, it's a [config option](https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-filterwarnings), see the [configuration docs]{https://docs.pytest.org/en/7.1.x/reference/customize.html) for details. You can also use `-W ignore::pytest.PytestReturnNotNoneWarning` if you prefer a CLI argument.

**Comment by nicoddemus** [comment]
I think we can settle then that this will never become an error then?

If so, I think all we need to do is to change its superclass from `PytestRemovedIn8Warning` to `PytestWarning`:

https://github.com/pytest-dev/pytest/blob/fd56968f2b9006b7a93bcf918b465d37bd3eea56/src/_pytest/warning_types.py#L59

**Comment by RonnyPfannschmidt** [comment]
:+1 :

**Comment by fraserstark** [comment]
I've created a PR for this if it's still needed.
