### ISSUE TITLE
Support unittest style TestCase in parametrized tests

### ISSUE THREAD

**Issue by lukaszjanyga** [pytest-dev/pytest#10474]
#### What's the problem this feature will solve?

Some packages (e.g. https://django-elasticsearch-dsl.readthedocs.io/) offer custom `unittest` style classes. That, as documented, is not supported currently by pytest. To allow more consistent style in test suites, it would be helpful if we execute a parametrized test within the context of a TestCase subclass.

#### Describe the solution you'd like

In a project I've been working on, I used this decorator to achieve it.

```python
def use_test_case_cls(cls: Type[TestCase]):
    def _pytest_unittest_wrapper(test_func: Callable):
        def _test_case_cls_wrapper(*args, **kwargs):
            # NOTE: dynamically subclass to provide custom implementation
            class _TestCaseWrapper(cls):
                def runTest(self):
                    return test_func(*args, **kwargs)

            result = _TestCaseWrapper().run()
            for failure in result.failures:
                # NOTE: limited to first failure, is there a case where more would be relevant?
                raise AssertionError(failure[1])
                
        # NOTE: match signature for parametrization to correctly identify arguments
        _test_case_cls_wrapper.__signature__ = inspect.signature(test_func)

        return _test_case_cls_wrapper

    return _pytest_unittest_wrapper
```

Usage then looks like so:

```python
@pytest.mark.parametrize(*parametrize_args)
@use_test_case_cls(MyTestCase)
def test_my_unit_test(param):
    # Test all the things
    pass
```

Would love to contribute so just LMK if you're interested in this change.

**Comment by RonnyPfannschmidt** [comment]
This won't get added as proposed

**Comment by lukaszjanyga** [comment]
Any more context?

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt when closing things as "not planned", it is important to elaborate on why the proposal is not a good fit for the core.

@lukaszjanyga in general the core team prefers to avoid extending/adding new features for unittest support, because in our experience they might be hard to maintain, with problematic corner-cases appearing in the wild. Also, once a new feature gets into the pytest core, we need to support it for years to come, for this reason we need to be sure the functionality is beneficial to a large number of users and worth the maintenance cost.

Having said that, it is possible to write a plugin which provides the functionality your propose, this way you can fine tune as more users use it, and also provide quicker fixes/updates than having it into the pytest core.

**Comment by lukaszjanyga** [comment]
@nicoddemus thanks for that, I'll launch it as a plugin then!
