### ISSUE TITLE
when time < 10ms, the duration will be 0

### ISSUE THREAD

**Issue by TUT-jiayou** [pytest-dev/pytest#10500]
Hi,all
* When test case consumption time is less than 10ms, the number 00 is got in html report  generated by `pytest-html`.
* I open issue in  `pytest-html` project to discuss the feature or bug. The container think that is  get form pytest. more information in https://github.com/pytest-dev/pytest-html/issues/566#issue-1445326609
* would someone give me some guide to help me that get more detail time in my test case.
* thanks for your time.

**Comment by nicoddemus** [comment]
Does not seem like a pytest problem, because the report duration is calculated using `time.perf_counter()`:

https://github.com/pytest-dev/pytest/blob/69e3973d86e2db6d0a0d69202a6306626d58b423/src/_pytest/runner.py#L339-L360

So as discussed in https://github.com/pytest-dev/pytest-html/issues/566 seems like it is a formatting issue with `pytest-html`.
