### ISSUE TITLE
plugins_index.py: Wrong version number?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest#1118]
When running `plugins_index.py` when trying to release on my `2.8.2-release` branch, it generates lines with `2.8.2.dev1` as version number, despite `__version__` being updated in `__init__.py` - maybe I'm using it wrong, but I'd expect it to get the pytest version from there...

I worked around it by doing `--pytest-ver=2.8.2`.

**Comment by nicoddemus** [comment]
Hmm the relevant code is [this](https://github.com/pytest-dev/pytest/blob/master/doc/en/plugins_index/plugins_index.py#L79):

```python
    if pytest_ver is None:
        pytest_ver = pytest.__version__
```

My guess it was using `pytest` from your environment rather than the local one.

Neverthless, I think we should update the instructions to always pass the version explicitly so there's no chance of the docs being generated with the wrong version. What do you think?

**Comment by The-Compiler** [comment]
Sounds good, and it's a minor burden for being less error-prone - I also think the script should be adjusted then so `--pytest-ver` is required :wink:

**Comment by nicoddemus** [comment]
Agreed. :smile: I'll take care of it, thanks.
