### ISSUE TITLE
config.getini returns an empty list for an option of type string absent in INI file

### ISSUE THREAD

**Issue by harmin-parra** [pytest-dev/pytest#11282]
I want to manage this INI option 
```
    parser.addini(
        "my_option",
        type="string",
        default=None,
        help="My option",
    )
```

I decide not to include this option in the INI file

I read the value with this code

```
@pytest.fixture(scope='session')
def my_option(request):
    return request.config.getini("my_option")
```

Actual result: The returned value is an empty list

Expected result: None

Tested with pytest 7.4.0 on Linux Mint

**Comment by The-Compiler** [comment]
Here is an actual reproducer:

`conftest.py`:

```python
import pytest

def pytest_addoption(parser):
    parser.addini(
        "my_option",
        type="string",
        default=None,
        help="My option",
    )

@pytest.fixture(scope='session')
def my_option(request):
    return request.config.getini("my_option")
```

`test_x.py`:

```python
def test_x(my_option):
    assert my_option is None
```

results in:

```python
    def test_x(my_option):
>       assert my_option is None
E       assert [] is None
```

**Comment by SharadNair7** [comment]
Hello @harmin-parra, @The-Compiler, @Zac-HD,

I can work on this fix if you all agree.

Regards
Sharad

**Comment by SharadNair7** [comment]
Hello all,

I have a question regarding this issue. Should **config.getini()** return "None" irrespective of the "type" provided for the configuration? What if the the "type" is linelist or pathlist with no default value or "None" provided in configuration or while making the call to **parser.addini()**

Please look at a test that exists in the current code base that implicitly assumes that the configuration item named "xy" has a default value of empty list. I think the correct way to call **parser.addini()** is to always provide a default value if you are expecting it to return an Empty List or any other data type. Which means the call to addini() in the test code below should be:

parser.addini("xy", "", type="linelist", **default=[]**)
instead of just
parser.addini("xy", "", type="linelist")

```
 def test_addinivalue_line_new(self, pytester: Pytester) -> None:
        pytester.makeconftest(
            """
            def pytest_addoption(parser):
                parser.addini("xy", "", type="linelist")
        """
        )
        config = pytester.parseconfig()
        assert not config.getini("xy")
        config.addinivalue_line("xy", "456")
        values = config.getini("xy")
        assert len(values) == 1
        assert values == ["456"]
        config.addinivalue_line("xy", "123")
        values = config.getini("xy")
        assert len(values) == 2
        assert values == ["456", "123"]
```

Please let me know your views as there are some occurrences within the code base that makes this assumption of implicit default values based on "type".

Regards
Sharad

**Comment by RonnyPfannschmidt** [comment]
the issue lies in https://github.com/pytest-dev/pytest/blob/b73b4c464c6fa54f55a1c6ed8eaceb5529a161bb/src/_pytest/config/__init__.py#L1521-L1528

it tries to be smart based on type, but does not quite deal with all kinds of types correctly

as far as i can tell there also is the case of automatically returning "" on a empty default for a string when no type was defined (none implies string)

maybe using something like dataclasses.Missing as a experiment to see how to make sane default return values could be a starting point

**Comment by SharadNair7** [comment]
Thank you @RonnyPfannschmidt,

But my question was around the expected behavior after making changes for this issue. This issue as raised by @harmin-parra expects config.getini() to return "None" if "None" is set as the default value while adding the configuration item using parser.addini().

**Solution 1**
Return "None" as the default value if "None" or no default value if provided by the developer. In this approach, existing calls to the config.getini() function would need to check for "None" values

**Solution 2**
Return a default value based on the "type" argument. If no type argument is specified, then it will be treated as a string. But in this approach, "None" will never be returned as a default value.

**Solution 3**
The default value can have an additional possible option of "NotSet" which would mean that the developer did not pass any value for the "default" parameter. This will be different from passing "None" as default. In this approach, the following behavior will be seen:

1) If the developer sets "None" as the default value for the configuration, then "None" will be returned irrespective of the "type" parameter.
2) if the developer does not provide any value for the configuration, then it will be treated as "NotSet" and an appropriate default value based on the "type" argument will be returned. If no "type" argument is provided, the an empty string will be returned.

Please let me know which approach would be more acceptable?

Regards
Sharad

**Comment by SharadNair7** [comment]
I personally feel, Solution 1 is the right way to go considering the straight forward and clean approach.

regards
Sharad

**Comment by harmin-parra** [comment]
+1 for solution 1

We should return `None` if `None` is set as default value and no input value is provided by the user

**Comment by harmin-parra** [comment]
I also agree that 
`parser.addini("xy", "", type="linelist", default=[])` :white_check_mark:
while
`parser.addini("xy", "", type="linelist") `:x:
