### ISSUE TITLE
update-plugin-list job is failing

### ISSUE THREAD

**Issue by DetachHead** [pytest-dev/pytest#11327]
the update-plugin-list job has been failing for about a month

https://github.com/pytest-dev/pytest/actions/runs/5914257523/job/16039386893

```
 Traceback (most recent call last):
  File "scripts/update-plugin-list.py", line 65, in <module>
    ) -> OriginalResponse | CachedResponse:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by The-Compiler** [comment]
Good catch! Looks like this broke here:

- #10927 

Because that PR uses [PEP 604](https://peps.python.org/pep-0604/) syntax for types, which was added in Python 3.10, but the CI uses 3.8 for this:

https://github.com/pytest-dev/pytest/blob/6e5f10b28f4f2831b161c8ceb695f96a89502da8/.github/workflows/update-plugin-list.yml#L30

I suppose we can just bump this up to Python 3.10, as we don't really care much where it runs? @RonnyPfannschmidt thoughts?

@DetachHead do you want to submit a PR for this?

**Comment by RonnyPfannschmidt** [comment]
Good catch and correct solution, please go ahead,im off the computer for a while

**Comment by DetachHead** [comment]
done #11328
