### ISSUE TITLE
`--lfnf` does nothing unless you also pass `--lf`

### ISSUE THREAD

**Issue by DetachHead** [pytest-dev/pytest#11346]
this will run every test regardless of if there were any previous failures
```
pytest --lfnf=none
```
i have to pass both arguments for it to work:
```
pytest --lf --lfnf=none
```

i'm not sure if this is intended functionality for whatever reason, but if it is, it should be documented in the `--help` description. the current documentation seems a bit unclear:
```
  --lfnf={all,none}, --last-failed-no-failures={all,none}
                        Which tests to run with no previously (known) failures
```

**Comment by seanjedi** [comment]
I would agree that the documentation is a bit unclear, I would also suggest updating the documentation to make t functionality of `--lfnf` more clear.

**Comment by nicoddemus** [comment]
A PR to update the docs will be great.

*Why not make ---lfnf imply --lf?*

My understanding is that people often put the `--lfnf` configuration into their configuration file, so making that change would make all runs --lf.

**Comment by seanjedi** [comment]
I can work on the docs to make what this is supposed to do more clear, but I have an additional question, in which does `--if` and `--ifnf=all` do the same exact thing then? 
It seems like the functionalities are a bit related, in which `--if` and `--ifnf=all` do the same thing, but `--ifnf=none` should do the inverse, regardless if `--if` is included. 
However, it seems to me from the code that regarldess what value `--ifnf` has, if the configuration has `--if` then it should rerun all previously failed tests.
So it seems to me that the if statement related to the option should be changed to check if the flags `--if` or `--ifnf=all` are included, and if not then go to the else statement on line 378
Related code: https://github.com/pytest-dev/pytest/blob/main/src/_pytest/cacheprovider.py#L344

Also sorry, this is my first issue I am working on as a contributor, so I am a bit new to the Pytest codebase, and not really knowledgeable about the functionalities yet.

**Comment by DetachHead** [comment]
> A PR to update the docs will be great.
> 
> 
> 
> *Why not make ---lfnf imply --lf?*
> 
> 
> 
> My understanding is that people often put the `--lfnf` configuration into their configuration file, so making that change would make all runs --lf.

In that case wouldn't it make more sense for `lfnf` to be an ini option instead of a cli option?

**Comment by nicoddemus** [comment]
> In that case would it make more sense for lfnf to be an ini option instead of a cli option?

Not necessarily, it is also common to use it via command-line.

**Comment by nicoddemus** [comment]
@seanjedi 

> --if and --ifnf=all do the same exact thing then?

No, `--lfnf` controls what `--lf` will do when it encounters the scenario where there are no more failures, which is the case when you are in a change code/run tests/fix code cycle. The default (`all`), will run all tests then, while `none` will not run any tests and exit successfully. 

I think the `--lfnf` option only exists for backward compatibility, because it makes sense to just say "no more failures" and not run anything (which is the behavior of `--lfnf=none`) when you reach the point where you fixed all failures: it is cheap to just say that and quit. The user, if they want to run the full suite now, just need to remove the `--lf` flag then. In other words, at the time the behavior was to run all tests, but to preserve backward compatibility, we decided to include a new option to add the new behavior (`none`).

**Comment by RonnyPfannschmidt** [comment]
I think its time to close this as works ask intended

**Comment by nicoddemus** [comment]
Indeed it does, but we have since then redirected it to update/clarify the docs instead.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt is right, better to close this one and create a follow up: https://github.com/pytest-dev/pytest/issues/11354

Thanks @seanjedi and @DetachHead!
