### ISSUE TITLE
ValueError: fixture is being applied more than once to the same function

### ISSUE THREAD

**Issue by RUHMA126** [pytest-dev/pytest#11516]
@pytest.mark.order(3)
def testAddEquipment(Header, AddEquipmentAPI , AddEquipmentPayLoad, BaseUrl ,  GetGroupbyFactory ,  GetDeviceId):
    print(AddEquipmentPayLoad)
    response = requests.post(url=AddEquipmentAPI, json=AddEquipmentPayLoad, headers=Header)
    StatusCode = response.status_code
    print(StatusCode)
    print(response.json())

**Comment by RonnyPfannschmidt** [comment]
please use the code-blocks feature of github to markup code examples to make them readable and provide enough context that we can figure the error

with only the function without the supporting code we cant even guess

please provide enough details so that we can at least see the error in action if not replicate
