### ISSUE TITLE
better display/ux on fixture discovery errors

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1160]
reference #1148

fixture lookup errors should get a better ux

**Comment by hpk42** [comment]
it would be helpful if you also suggested what exactly should be better.

**Comment by immerrr** [comment]
> it would be helpful if you also suggested what exactly should be better.

I'm the author of #1148, and I don't really understand how does the description of this issue relates to it. 

#1148 was about the fact that doctest test wrapper did not create one of the fields used during error formatting (`doctest_item.obj`). I hit that issue when I had misplaced a fixture and py.test was trying to generate a "fixture not found" report and apparently pretty-printing the test case environment failed because of the missing field.

I'd wildly guess that the fix would be to provide a proper value for `doctest_item.obj` field, but perhaps Ronny has something bigger in mind.

**Comment by Zac-HD** [comment]
Closing this issue as unclear / inactive; better UX would be nice in general but this is not actionable.

**Comment by immerrr** [comment]
As the original author, I'm still unclear what was the point of closing #1148 in favour of this one. But the good news is that it was fixed somewhere between that day and 4.0.1, so all good.

**Comment by Zac-HD** [comment]
Also no idea - I was just triaging old proposals - but very glad it's been fixed :smile:
