### ISSUE TITLE
Check xfail Test Status with Plugin

### ISSUE THREAD

**Issue by eleanorjboyd** [pytest-dev/pytest#11847]
Started an discussion on this but wanted to move it over as I think it is a bug, apologies if that is incorrect. Thanks!

My goal is to correctly store the status xfail tests. Below is the code I am running, the plugin I wrote to connect to the given hook, and the output from the plugin. Im confused because the outcome of this xfail tests is "passed" during "setup" and "teardown" but then is listed as "skipped" during "call". Why does the xfail tests list as "skipped" during "call"? With all other tests I have written, the "call" phase has been accurate in collecting pass/fails etc but I wasn't sure about xfail. What does the skip mean and is it always going to say skip for xfail tests during this phase? Thanks and I appreciate any help!

```
@pytest.mark.xfail
def test_example():
    assert 1 == 2, "This test is expected to fail because 1 is not equal to 2"
```

```
@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item):
    outcome = yield
    report = outcome.get_result()
    print("pytest_report_teststatus")
    print("when", report.when)
    print("outcome", report.outcome)
    print("xfail", hasattr(report, "wasxfail"))
```
```
test_xfail.py 
pytest_report_teststatus
when setup
outcome passed
xfail False
pytest_report_teststatus
when call
outcome skipped
xfail True
xpytest_report_teststatus
when teardown
outcome passed
xfail False
```

originally commented on this related thread but it seems inactive: https://github.com/pytest-dev/pytest/discussions/10255
This question is related to a bug fix on the VS Code python extension, related issue: https://github.com/microsoft/vscode-python/issues/4963

**Comment by eleanorjboyd** [comment]
Thank you for your response. What you describe aligns with what I am seeing but I guess is still a bit confusing. In the case of `If not strict, outcome is passed and wasxfail is set.` isn't this ultimately a failure of the given test because it was expected to fail and it didn't? VS Code does not have specifics for expected failures so it has to either be in "passed", "failed" or "skipped" so I wrote down the outcome below that I think our users expect. Wanted to make sure I understood correctly before continuing, thanks!

if outcome is `skipped` and `wasxfail`
- set vscode_outcome to passed (the xfail did fail, therefore behavior is as expected)
if outcome is `failed`
- set vscode_outcome to failed: it really did fail, it was strictly set so the test was expected to fail but did not therefore failure
if `outcome` is passed and `wasxfail`
- set vscode_outcome to fail: test passes (which is unexpected so it is really a failure)

**Comment by bluetech** [comment]
> In the case of If not strict, outcome is passed and wasxfail is set. isn't this ultimately a failure of the given test because it was expected to fail and it didn't?

Yes it is supposed to be a failure and it is confusing, so `xfail_strict = true` is definitely the better setting, but currently it defaults to false. We have plans to change the default but it requires a deprecation period etc (see #11467).

> if outcome is skipped and wasxfail

From different perspectives it can be considered either skipped or passed.

In *my* opinion, xfails are not meant for "verify that this fails" uses, but for "I'm aware this fails, but I temporarily want it to not fail the test suite" uses, the most common example being committing a test before its fix. In this perspective, I'd say out of the options vscode supports, you'd want "skipped".

However there are definitely people who use `xfail` as "verify that this fails". In my opinion this is inappropriate but I'm not the testing dictator :grinning: In this cases, the user probably wants "passed".

cc @RonnyPfannschmidt on this ^^^

> if outcome is failed

Definitely "failed".

> if outcome is passed and wasxfail

So because pytest currently has a bad default for `xfail_strict` this is a bit of a bind.

*If `xfail_strict` were the default*, I'd say this should definitely be a "passed", because the user explicitly opted into the non-strict behavior which says that an XPASS is good.

But because we have a bad default, it often really should be a "failed". However I'd go with "passed".

---

And ideally, VS Code would add direct support for XFAIL and XPASS :)
