### ISSUE TITLE
Search documentation in 8.x

### ISSUE THREAD

**Issue by fschulze** [pytest-dev/pytest#11988]
It seems like the documentation lost the search field in 8.x. In 7.x it is at the top of the sidebar on the left. I can't find it in the 8.x documentation.

**Comment by bluetech** [comment]
I looked at this a bit earlier, probably the issue is with our [`slim_searchbox.html`](https://github.com/pytest-dev/pytest/blob/5f241f388be3aaf4faa5e5e0029548863413014f/doc/en/_templates/slim_searchbox.html) template (configured [here](https://github.com/pytest-dev/pytest/blob/cefb3e2277b6ea24acc7b1088f80ef0f9e9f3858/doc/en/conf.py#L266-L281)) and not with Sphinx upstream. With the upstream `searchbox.html` template the search box does appear. I was too lazy to check the exact issue though...

**Comment by nicoddemus** [comment]
Oh thanks for the pointer, will take a look.
