### ISSUE TITLE
@pytest.mark.usefixtures should support fixtures by function (rather than name)

### ISSUE THREAD

**Issue by SergioInToronto** [pytest-dev/pytest#12150]
#### What's the problem this feature will solve?
`@pytest.mark.usefixtures(_my_fixture)` should be possible but only strings are accepted currently, `@pytest.mark.usefixtures("_my_fixture")`. Adding support two advantages:
* Passing functions makes sense intuitively. This is python 💪 not Ruby
* It's helpful for people who constantly typo everything (like me) 

#### Describe the solution you'd like
`@pytest.mark.usefixtures` should support both functions and function names.

My decorators are always defined within the file where they are used.

#### Alternative Solutions
* Continue using only strings. It's not the end of the world, but I'd like to do this.

**Comment by nicoddemus** [comment]
Hi @SergioInToronto, 

I understand the sentiment, and seems harmless at first, however this is not a good idea because it will lead people to importing fixtures from other files in order to pass them by value (rather than passing their name), which is a known footgun with pytest, because the fixture location is important.

There is also the argument that having two ways of doing the same thing is not necessarily good (although we do have more than one way to do things in pytest as it is).

Closing for now, but thanks for opening the issue.

**Comment by SergioInToronto** [comment]
For future me: if I ever come back to this, and convince Bruno it's a good idea, WIP code exists here - https://github.com/SergioInToronto/pytest/pull/1

**Comment by nicoddemus** [comment]
Hi @cjw296! 

> Having references to code hidden in strings, such as in pytest fixture names or mock.patch specs means that IDEs, linters and type checkers cannot help you find refactoring mistakes, which is particularly harmful in large codebases.

I see and agree with that point, but I still think it would be an overall net negative for pytest for two reasons:

1. People importing fixtures is known footgun unfortunately
2. Two ways of doing the same thing (although I think this is the weaker argument)

I'm open to change my mind on this if other maintainers get behind it though.

**Comment by RonnyPfannschmidt** [comment]
Currently import of fixtures is a antipatter 

Until that changes we need to go with the names

**Comment by cjw296** [comment]
> Currently import of fixtures is a antipattern
> People importing fixtures is known footgun unfortunately

Why is it a footgun? I'd hope by now that the thing returned by the @pytest.fixture() decorator isn't callable, and has type annotations to say it's something like a `PytestFixture[TypeTheOriginalcallableReturns]`

I can certainly see some confusion with the parameter of a test function having the same name as the fixture, but I guess that's always been the point of pytest fixtures? If you use a fixture without including it in a parameter name of a test function your end up in a weird place...

...the purist in me says its that choice that's the core of the problem here and pytest should deprecated this pattern:

```python
def test_something(my_fixture):
    foo = my_fixture()
```

```
@uses(my_fixture)
def test_something():
    foo = my_fixture()
```
