### ISSUE TITLE
Runaway memory consumption when `mock.call` in namespace

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest#1217]
Consider this simple test case:

```
$ cat > test_foo.py
from unittest.mock import call
```

Then run `py.test --doctest-modules` and py.test will consume all memory until killed by the OS, but only on Python 3.5. Not importing call into the namespace works around the issue.

This issue was first encountered in [pmxbot 42](https://bitbucket.org/yougov/pmxbot/issues/42/tests-crash-on-python-35).

**Comment by The-Compiler** [comment]
FWIW, someone in the `#python` IRC channel just reported the same, but it only happens when additionally using `--cov` (pytest-cov) for them.

**Comment by pstch** [comment]
I'm that guy on the `#python` IRC channel, and `--cov` was actually not related, this was a mistake (I thought it was related because I saw long parts of coverage in traceback when I `^C` the process).

So I'm hitting the same problem, and am able to reproduce it the same way as OP.

I'd be glad to help, not sure where to start.

**Comment by The-Compiler** [comment]
Looks like this is a Python bug: http://bugs.python.org/issue25532
