### ISSUE TITLE
Missing `py.process`

### ISSUE THREAD

**Issue by Flamefire** [pytest-dev/pytest#12206]
It seems that pytest does no longer include the full `py` which is seemingly in maintenance mode and shouldn't be used anymore?

However the pytest plugin `pytest-forked` uses it but now fails to import `py.process` to use `ForkedFunc`: https://github.com/pytest-dev/pytest-forked/issues/88

**Comment by The-Compiler** [comment]
`pytest-forked` [depends on](https://github.com/pytest-dev/pytest-forked/blob/master/setup.py#L22) `py`, so if you don't have the full `py` installed, that's an issue with how you install it.

The compatibility shim in pytest itself only exists for `py.path`, since pytest testsuites might still use it. It's not its aim to provide a full copy of `py`.

**Comment by Flamefire** [comment]
I see thanks! Issue here was that we have a base installation with pytest and py and an extra installation with pytest only. And the import picks up the shim-py in the extra not the full module in the base.
