### ISSUE TITLE
Docs: redirect loop

### ISSUE THREAD

**Issue by soxofaan** [pytest-dev/pytest#12648]
Search engine brought me to  https://docs.pytest.org/en/7.1.x/how-to/writing_plugins.html 
I noticed I was looking at 7.x docs and wanted to go to 8.x version.
I removed the `7.1.x` from the url just to see what would happed - > https://docs.pytest.org/en/how-to/writing_plugins.html
That failed with an "The page isn’t redirecting properly" error.
Looking at dev tools it seemed to trigger a redirect loop:
https://docs.pytest.org/en/how-to/writing_plugins.html redirects to https://docs.pytest.org/en/how-to/how-to/writing_plugins.html (note the double `/how-to/`) and the latter redirects back to the former

**Comment by nauman897** [comment]
You always need to add a version after `https://docs.pytest.org/en/`. If you want to navigate to the latest versions documentation, you can add `stable` instead of the version number, which would take you to the latest stable release's documentation.

So in your case, you need to navigate to: https://docs.pytest.org/en/stable/how-to/writing_plugins.html

**Comment by nauman897** [comment]
**Suggestion:**
We can add a version dropdown to the documentation page, making the process of switching between different versions of documentation more intuitive.

I would love to help out with this

**Comment by soxofaan** [comment]
yes, I know how to get to the desired page, that's not the problem, 
I just wanted to point out a possible redirect loop in the docs

**Comment by The-Compiler** [comment]
> We can add a version dropdown to the documentation page, making the process of switching between different versions of documentation more intuitive.

![image](https://github.com/user-attachments/assets/39706545-7aec-4470-85e1-d42c9ff03387)

---

As for the OP, we have a redirect `/writing_plugins.html -> /how-to/writing_plugins.html` and a redirect `/how-to/writing_plugins.html -> /writing_plugins.html` configured on RTD. This was due to #8443 / #8471, and we deliberately added reverse redirects too: https://github.com/pytest-dev/pytest/issues/8471#issuecomment-987015839

Looks like this issue will thus happen for something that's a 404 but *also* a valid redirected page. Unfortunately, I don't think this is something we can fix without breaking version switching too.
