### ISSUE TITLE
--failed-first and --new-first don't play well together

### ISSUE THREAD

**Issue by Gaelan** [pytest-dev/pytest#12715]
When running `pytest --new-first --failed-first`, I would expect failing and completely new (ie never run before) tests to run first, then the rest of the test suite in order of modification time. Unfortunately, `NFPlugin` actually seems to [sort the entire test list by modification time](https://github.com/pytest-dev/pytest/blob/b08b41cefb5e83271a055bf6a22c79d52a06a8c3/src/_pytest/cacheprovider.py#L454-L457), clobbering any ordering done by `LFPlugin`, so `--new-first --failed-first` is equivalent to `--new-first` alone.

Running pytest 8.3.2 on Debian bullseye.

**Comment by Zac-HD** [comment]
Unfortunately I think this problem is basically inherent in anything that includes multiple ordering steps; distinct command-line arguments are generally treated as if the ordering doesn't matter (e.g. being put in a namespace, not a sequence), and so we don't know how to construct a sorting key.  And if we did, that would still require every plugin which reorders items to be aware of the mechanism... so overall I think we're basically stuck with the status quo for now.
