### ISSUE TITLE
how to change the default test discover method for file not starts with test_

### ISSUE THREAD

**Issue by hackrole** [pytest-dev/pytest#1276]
the pytest is really awesome. the test code has been really short and reusable than what I write in unittest2.

I usually and a tests-dir output of my src-dir. and I like to do both functional-test and unittest.
I like to put them together. I usually name the unittest with test_*.py, which has no problem with py.test.
and I name the functional-test  with fts_*.py, which cause problem with py.test.

now I can only ran the fts with py.test fts*.py, which only allow run one fts file at once.
when in unittest2, this not hard for me. But I go through the doc and google, still cannot got a good answer. 

Did I miss something?

**Comment by nicoddemus** [comment]
Use the [python_files](http://pytest.org/latest/customize.html?highlight=python_files#confval-python_files) configuration variable:

```ini
[pytest]
python_files=test_*.py
    fts_*.py    
```

:smile:

**Comment by hackrole** [comment]
Oh god, It works. can I set it on the command line instead of the pytest.ini?

**Comment by RonnyPfannschmidt** [comment]
you could apply a marker to the  modules, and then select using py.test -k unit or -k fts (or whatever name you pick

also closing this issue, since its a question

**Comment by hackrole** [comment]
really not a good solution. I have to mark every testcase I write with fts and unit. it is foolish and really repeated.
I like the unittest way for this.
```bash
python -m unittest -p test*.py
python -m unttest -p fts*.py
```

**Comment by nicoddemus** [comment]
One solution for your specific request is to implement a custom hook that automatically marks each test item based on their file name.

Put this into a `conftest.py` file at the root of your test files:

```python
def pytest_collection_modifyitems(items):
    for item in items:
        name = item.fspath.basename
        if name.startswith('fts'):
            item.add_mark('fts')
        elif name.startswith('test'):
            item.add_marker('test')
```

(More information about plugins [here](http://pytest.org/latest/writing_plugins.html)).

Now you can selectively run your tests with:

```
py.test -m test
py.test -m fts
```

Note that py.test marks are a more flexible way to filter tests, and people usually use them instead of file names when classifying tests. Suppose you also add `slow` marks to some of the functional tests that take some time to run. This allows you to do this:

```
py.test -m "fts and not slow"  # run only fast functional tests (not slow)
py.test -m "fts and slow"  # run only slow functional tests
```

**About the command line option**: feel free to create an issue for it.
