### ISSUE TITLE
Would there be any interest if I rewrote the test collector in go/rust?

### ISSUE THREAD

**Issue by dougthor42** [pytest-dev/pytest#12813]
#### What's the problem this feature will solve?

Slow test collection for large projects.

#### Describe the solution you'd like

It's possible that rewriting the test collector in go/rust could provide a significant speedup. Take a look at the `ruff` or `uv` projects or Bazel's `rules_python` - both deal with parsing many Python files and do so insanely fast.

#### Alternative Solutions

A quick search of the Issues and Googleing didn't return any existing projects that does this, so I'm assuming that it's not been done before. Please feel free to correct me!

#### Additional context

I'm looking for a new project to help me learn another programming language. We've been experiencing slow pytest collection in our large project and I figured that updating it might be a good project. For our main codebase, `--collect-only` can sometimes take 7-9 minutes for 35k items. On good days it's more like 3 minutes:

```
$ time pytest --collect-only
======= test session starts =======
platform linux -- Python 3.11.8, pytest-8.1.1, pluggy-1.4.0
...
plugins: pyfakefs-5.6.0, anyio-3.5.0, xdist-3.5.0, asyncio-0.23.6, flaky-3.8.1, cov-5.0.0, dash-2.14.2, qt-4.4.0, benchmark-4.0.0, typeguard-2.13.3, timeout-2.1.0
...
======= 34891 tests collected in 197.54s (0:03:17) =======

real    3m29.856s
user    3m25.792s
sys     0m25.333s
```

I haven't done any benchmarking, but given the success of projects like `ruff` and `uv`, my naive, baseless assumption is that we could probably get a 10x speed improvement for test collection.

#### Questions:

1. Do you think that the collector code would lend itself to being ported?
    + Or is it too highly coupled? (I haven't investigated yet).
    + Is it well tested? My goal would be to make a drop-in replacement that passes all current unit tests.
2. If I were to implement it, would the current maintainers be willing to support it going forward?
    + I could do some maintenance, but I can't guarantee any time allotment - it would all be "best effort".
    + I completely understand if this is "no" - after all, I'd be giving you more work!
3. Alternatively to merging into pytest core, does the pytest plugin ecosystem make it easy to override the test collector? I could instead write a plugin that does this, and then the core team wouldn't have to maintain it.
4. Is there a preference on language?
    + I have some experience with Go and almost no experience with Rust but would like to get better at either.
    + I'd learn more towards Go just because I think it would be easier for me.
    + I believe that Rust has better Python integration. AIUI, Rust can make python objects "directly" (via [pyo3](https://github.com/PyO3/pyo3)) whereas a Go implementation might have to use gRPC or something (I could be wrong - there may be a pyo3-like project for Go, but I'm not aware of it)

**Comment by nicoddemus** [comment]
Hi @dougthor42,

Thanks for writing!

About any kind of external extension to pytest, in any language, is at principle a no-go for the pytest *core*: pytest is used to test many many Python packages, and being pure Python is a significant benefit for this. 

Having said that, a plugin that re-implements some of the pytest internals in order to gain speed ups is a possibility.

About the collection part itself, I'm not sure rewriting it in any other language would speed up things much, because other than traversing the file system, the actual *collection* (importing files) will still need to be done by the Python interpreter; together with that we have the entire fixture system which still needs to live on the Python side, so it needs to be executed by the Python interpreter.

All of this is of course just my gut feeling, I did not do any benchmarks in that sense.

As to your questions:

1. As I mentioned I don't think it would be possible to just port it, and the bulk of it would still need to invoke the Python interpreter. About it being well tested, it is definitely well tested, but still today some times edge cases appear that catch us off guard.
2. As I mentioned, I don't think something like this would be a good fit for the pytest core. I like Rust myself (but only a newbie), but I don't think the project itself would like to support this.
3. Yes a plugin would be a great way to do experiments.
4. As said it probably will not fit the pytest core, so in reality it is really up to you. But I do agree Rust seems a better fit in general for this kind of integration.

**Comment by dougthor42** [comment]
Thanks for the info!

> the actual _collection_ (importing files) will still need to be done by the Python interpreter

I wonder how much of this could be handled by parsing the python file/AST instead actually importing modules. I assume you're, at least partially, talking about things like a parametrized test function that gets collected into N individual tests. For basic cases (such as ones where the parameters are a fix list of basic values), it _might_ be possible to parse instead of import. While that would only cover a small portion of everything possible with pytest, it might be enough to see some gains.

It does sound like something definitely more complex that I initially thought, haha. That doesn't mean I won't try though!

I now see that there's a [custom collection example plugin](https://docs.pytest.org/en/stable/example/nonpython.html#yaml-plugin) so I think I'll be able to build off that.

I'll go ahead and close this as not planned and if I ever _actually_ get around to building something I'll reply here for anyone else who might find this in the future.

**Comment by mikicz** [comment]
Looks like someone gave it a go: https://pypi.org/project/pytest-fastcollect/

However I found that the collection produced a different number of results

**Comment by RonnyPfannschmidt** [comment]
Looks vibrant coded and abandoned plus the project metadata is incomplete 

Based on those indicators id avoid
