### ISSUE TITLE
Why does pytest not execute the entire loop?

### ISSUE THREAD

**Issue by tejendrapsingh** [pytest-dev/pytest#12927]
Hey! I am using the pytest together with seleniumbase for scraping a website. The function that I am passing to pytest has a long loop. pytest however stops before executing the entire loop. I have tried tweaking a few parameters but to no avail. I am posting a picture with a run that did not execute the entire loop. [Here](https://github.com/tejendrapsingh/for-help/blob/main/using-pytest-for-parallelization.py) is the link to the code.

![for-upload](https://github.com/user-attachments/assets/2e03f4bc-f7ce-4377-b33c-f2577e3a4ccc)
</div>

**Comment by graingert** [comment]
pytest with xdist doesn't print anything out when using `-s` https://github.com/pytest-dev/pytest-xdist/issues/354

Probably this issue is in where you catch all exceptions and suppress them https://github.com/tejendrapsingh/for-help/blob/main/using-pytest-for-parallelization.py#L900

Instead you should only catch the exceptions that you expect 

If you want to catch multiple exceptions and continue a for loop you should use an exception group:

```python
exceptions = []
for x in y:
    try:
        ...
    except Exception as e:
        e.add_note("failed processing {x}")
        exceptions.append(e)
if exceptions:
    raise ExceptionGroup("multiple errors processing", exceptions)
```

**Comment by graingert** [comment]
These bare except statements are also bad, and incompatible with a signal handler and BaseException timeout approach: https://github.com/tejendrapsingh/for-help/blob/main/using-pytest-for-parallelization.py#L92

**Comment by graingert** [comment]
It looks like you promoted this to an issue, but it's not an issue in pytest it appears to be an issue in your code. Let's continue the discussion on the discussion instead.
