### ISSUE TITLE
Remove `_pytest.compat.is_generator()` and just use `inspect.isgeneratorfunction()` directly

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#12960]
It's already equivalent in practice, and deleting the [few uses and handful of tests](https://github.com/search?q=repo%3Apytest-dev%2Fpytest%20is_generator&type=code) will make it easier for contributors to understand code which uses the stdlib function instead.

While we're there, I'd like to turn the xfail on "yield tests" - a noop since Pytest 4! - into a hard error, to reduce the risk that users incorrectly believe that they're testing something.

**Comment by arpitgupta-it** [comment]
I want to take it up!

**Comment by RonnyPfannschmidt** [comment]
go for it, thanks !

**Comment by arpitgupta-it** [comment]
Hi @RonnyPfannschmidt 

I've made the requested changes to "Remove _pytest.compat.is_generator() and just use inspect.isgeneratorfunction() directly."

Regarding the additional note: "While we're there, I'd like to turn the xfail on 'yield tests'—a noop since Pytest 4!—into a hard error, to reduce the risk that users incorrectly believe that they're testing something":

Would you like me to just turn the xfail into a hard error, or should I also refactor hooks that use yield (e.g., @pytest.hookimpl(wrapper=True))? If so, are there any specific files you'd like me to focus on?

Thank you!

**Comment by Zac-HD** [comment]
- just the xfail, which is guarded by the condition in your diff in `src/_pytest/python.py`.  yield fixtures are fine.
- in test_compat.py, just delete the affected tests - we don't need tests for the stdlib function.
- in general I'd encourage you to open a PR with your current state and ask any questions there - the review interface is really helpful for tracking work-in-progress, not just finished or polished contributions!

and thanks for helping out!
