### ISSUE TITLE
issue a pytest-waring on eol and known to be broken python versions

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#1308]
after crosschecking with some of our users i realized we should sync our policy with pip

however its reasonable to warn users of python2.6 that their python is eol
the same holds true for 3.0 and 3.1, 3.2 will join in february

this is a followup to #1273

**Comment by The-Compiler** [comment]
I don't think this should be pytest's job. If I was using those python's, it sure would get me to never look at pytest warnings again.

**Comment by nicoddemus** [comment]
I kind of agree with @The-Compiler as well... people already kind of dislike pytest-warnings because most of the time the users can't do anything about them (for example in an external plugin). 

I think we could just make that clear during the release announcements for 2.9 and onward that we will drop 2.6 as soon as pip does.

**Comment by RonnyPfannschmidt** [comment]
I agree, closing as wont fix
