### ISSUE TITLE
Not available PDF documentation

### ISSUE THREAD

**Issue by maksim77** [pytest-dev/pytest#1436]
[Link](http://pytest.org/latest/pytest.pdf) to pdf returns 404 code

**Comment by nicoddemus** [comment]
Thanks for the pointer! Meanwhile please find the PDF docs generated by readthedocs [here](http://readthedocs.org/projects/pytest/downloads/pdf/2.9.0/).

**Comment by stleon** [comment]
what about epub?

**Comment by nicoddemus** [comment]
This is not official yet, but we plan move our documentation hosting to readthedocs.org. docs.pytest.org is already online, and it provides epub as well. :grin:

**Comment by nicoddemus** [comment]
Could anyone with a working environment that can generate PDF files fix this? Often someone still stumbles on this. :worried: 

@The-Compiler, @RonnyPfannschmidt? :grin:

**Comment by The-Compiler** [comment]
I did a quick build of the 2.9 docs and uploaded them.

**Comment by nicoddemus** [comment]
@The-Compiler thanks a ton! :smile:

**Comment by ernstki** [comment]
Sorry to nag, but this is still (or once again) an issue for 2.9.3.dev0, where the latest PDF can be found [here](https://media.readthedocs.org/pdf/pytest/latest/pytest.pdf), but many/most of the links to it from within the online documentation are broken.

There aren't that many places in the `doc` subdirectory that would need to be fixed, but because I'm not reeeally sure how Read the Docs works its multiple-versions-of-the-same-documentation magic, I dunno if just hard-coding https://media.readthedocs.org/pdf/pytest/latest/pytest.pdf all over there would be such a good idea.

![bildschirmfoto 2016-07-19 um 15 50 37](https://cloud.githubusercontent.com/assets/4009681/16952325/ff713b0a-4dc8-11e6-8b11-9336f668696b.png)

But if it really _is_ that easy, I'd be happy to file a pull request.

**Comment by nicoddemus** [comment]
> But if it really is that easy, I'd be happy to file a pull request.

I think that should be enough... certainly it would be an improvement already! :grin: 

A PR would be really appreciated.
