### ISSUE TITLE
Suggestion: merge .fixture and .yield_fixture

### ISSUE THREAD

**Issue by csaftoiu** [pytest-dev/pytest#1461]
The [yield_fixture](https://pytest.org/latest/yieldfixture.html) page says:

> lastly yield introduces more than one way to write fixture functions, so what’s the obvious way to a newcomer?

My suggestion is to merge `pytest.fixture` and `pytest.yield_fixture`. 

Before:

    @pytest.fixture
    def foo():
        return ['bar']

    @pytest.yield_fixture
    def boof():
        with some_stuff as more_stuff:
            yield even_more_stuff(more_stuff)

After:

    @pytest.fixture
    def foo():
        return ['bar']

    @pytest.fixture
    def boof():
        with some_stuff as more_stuff:
            yield even_more_stuff(more_stuff)

This should be possible - if calling the fixture function returns a generator, then do what `yield_fixture` currently does, otherwise (i.e. if it returns a value), then do what `fixture` currently does.

The reason? There will be one less choice for a newcomer to make - which decorator to call. 

---

Further, the documentation section "Fixture finalization / executing teardown code" can now read something like this:

> pytest supports execution of fixture specific finalization code when the fixture goes out of scope. By yielding the fixture object instead of returning it, you can perform finalization code after the test has finished executing:

    # content of conftest.py

    import smtplib
    import pytest

    @pytest.fixture(scope="module")
    def smtp(request):
        smtp = smtplib.SMTP("smtp.gmail.com")
        yield smtp  # provide the fixture value
        print("teardown smtp")
        smtp.close()

> The code after the `yield `will execute when the last test using the fixture in the module has finished execution.

This is a straightforward change, syntactically (`return` -> `yield`), even if the internals are quite different, and is intuitive enough to me, and I suspect anyone who gets how generators work. 

I suggest deprecating the old callback-teardown method since the `yield` mechanism is superior in every way. Really it should be the only way, but it may be confusing to someone who expects to be able to simply return a value, and so returning a value will just work as well.

**Comment by nicoddemus** [comment]
Particularly I agree that `yield_fixture`s are superior and would like to see `pytest.fixture` support both styles.

I don't think there are backward compatibility issues, because we can use `inspect.isgeneratorfunction(f)` to decide if a fixture is using `yield`-style or `return`-style.

But I would like to hear what others have to say on this.

**Comment by The-Compiler** [comment]
I've always thought the same, but I thought there *was* some obscure reason it was done the way it is rather than combining them since the beginning - seems like I'm wrong? :wink:

I've also talked with @hpk42 about yield-fixtures vs. normal fixtures, in the context of the pytest trainings we're giving. He finds it more difficult to teach the `yield_fixture` approach, as people might not know `yield` or generators yet.

I personally think it's *still* easier to teach than `request.addfinalizer`, as people are also likely to not know the difference between *calling* a function and passing a function object (and of course it gets even more complex when parameters are involved), as I also saw [in this stackoverflow question today](http://stackoverflow.com/q/36069102/2085149).

If I were to decide, I'd integrate `yield_fixture` into `fixture`, promote that to the official/recommended way to do teardown from fixtures, and in the long run maybe deprecate `request.addfinalizer` and `yield_fixture`.

**Comment by nicoddemus** [comment]
> If I were to decide, I'd integrate yield_fixture into fixture, promote that to the official/recommended way to do teardown from fixtures

:+1: 

>  in the long run maybe deprecate request.addfinalizer and yield_fixture.

Depends on what you mean exactly by deprecate, but I would prefer just discourage or note that `request.addfinalizer` is the old approach and just recommend using `yield`. :wink: (My main point here is that we wouldn't remove support for it in any future version because certainly there's a ton of code depending on it).

**Comment by RonnyPfannschmidt** [comment]
we need a proper deprecation warning system

**Comment by nicoddemus** [comment]
> we need a proper deprecation warning system

I agree, but do you feel the need for a better warning system blocks deprecating `yield_fixture` as suggested here? To me they are separate concerns.

**Comment by chrish42** [comment]
As an experienced Python developer learning pytest, having the two merged together would have reduced what I had to learn with pytest.

Also, I'm pretty sure I'll forget (and need to lookup in the doc) the specific name `request.addfinalizer`, but I'll remember how to do cleanup by writing a generator (since it's similar to `contextlib.contextmanager`, etc. and feels like idiomatic Python to me).

**Comment by nicoddemus** [comment]
Resolved in #1586

**Comment by csaftoiu** [comment]
I do enjoy open source software :).
