### ISSUE TITLE
xfail_strict doesnt work with unittest-based tests

### ISSUE THREAD

**Issue by campbellr** [pytest-dev/pytest#1473]
I upgraded to py.test 1.9.1 to take advantage of the new `xfail_strict` option to force XPASS results to be reported as failures.

Unfortunately it seems like this doesn't work with `unittest`-based tests (with either the `unittest.expectedFailure` decorator or the `pytest.mark.xfail` decorator).

Is this expected behavior? I'd love to be able to use `xfail_strict=true` without having to convert my entire suite of tests to "native" pytest tests.

**Comment by nicoddemus** [comment]
Hmmm that's weird, thanks for the report! :smile: 

For my own reference:

```python
import unittest
import pytest


class Test(unittest.TestCase):

    def test_foo(self):
        pass

    @pytest.mark.xfail(strict=True)
    def test_bar(self):
        assert 1


class Test2:

    def test_foo(self):
        pass

    @pytest.mark.xfail(strict=True, reason='should never pass')
    def test_bar(self):
        assert 1
```

```
============================= test session starts =============================
platform win32 -- Python 3.5.0, pytest-2.9.2.dev1, py-1.4.31, pluggy-0.3.1
collected 4 items

foo.py X..F
=========================== short test summary info ===========================
XPASS foo.py::Test::test_bar

================================== FAILURES ===================================
_______________________________ Test2.test_bar ________________________________
[XPASS(strict)] should never pass
================ 1 failed, 2 passed, 1 xpassed in 0.02 seconds ================
```

**Comment by RonnyPfannschmidt** [comment]
We should make a decision about how much we want to support pytest Features in unittest classes

My personal opinion is to support no more than the bare minimum

**Comment by nicoddemus** [comment]
I agree, but IMO we should try to support what we can if it is feasible (ease of implementation/maintenance wise). In this particular case, since `@expectedFailure` works exactly like `@pytest.mark.xfail(strict=True)` we should then probably strive to support that.

We need to acknowledge that the ability of running existing `unittest` test suites using `py.test` is a great way to encourage others to try out py.test and migrate or just at least start all new tests using plain pytest style. :grin:

**Comment by Bajron** [comment]
After recent update on Debian I noticed, that `@unittest.expectedFailure` stopped working in pytest. My google searches brought me here. I hope what I found is connected with this issue.

I am using pytest to run my unittest suite on CI server, to get nice XML-report.
I am not experienced enough in pytest to suggest final solution, but I think I know what is going on.

When I have a test marked with `@unittest.expectedFailure` and I use `--runxfail`, my tests fail because of raising XFailed.
It started to appear in 3.1.0, and I think it was introduced in https://github.com/pytest-dev/pytest/commit/92f6ab188137a44479b0c6bcf209c3bf2ea31b41

The problem is that, the old "by global module variable" communication does not happen anymore.

This code sets up no-op for pytest.xfail when we actually run tests expected to fail: 
https://github.com/pytest-dev/pytest/blob/master/_pytest/skipping.py#L38

But this one does not use the previously set up function, but always the xfail function that raises XFail exception: 
https://github.com/pytest-dev/pytest/blob/master/_pytest/unittest.py#L143

Adding
```
#yay hack                                                                      
import pytest                                                       
pytest.xfail(str(reason))
```
in `addExpectedFailure` solves my problem, but is rather not a production ready solution ;)

**Comment by RonnyPfannschmidt** [comment]
@Bajron thats a new issue that i introduced, i'll take a look at fixing it,

what you proposed seems to enable it nicely

**Comment by Zac-HD** [comment]
```
$ pytest t.py
============================= test session starts =============================
platform win32 -- Python 3.8.0, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
collected 4 items

t.py F..F                                                                [100%]

================================== FAILURES ===================================
________________________________ Test.test_bar ________________________________
[XPASS(strict)]
_______________________________ Test2.test_bar ________________________________
[XPASS(strict)] should never pass
=========================== short test summary info ===========================
FAILED t.py::Test::test_bar
FAILED t.py::Test2::test_bar
========================= 2 failed, 2 passed in 0.04s =========================
```
