### ISSUE TITLE
FAQ: improve comparison with nose and unittest

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#1477]
From #1476:

> Overall I would suggest still adding a bit more of an explanation to https://pytest.org/latest/faq.html#how-does-pytest-relate-to-nose-and-unittest, outlining some of the major features/differences

cc @philfreo

**Comment by ryan-jr** [comment]
Hey @nicoddemus first time contributor here, let me know if something like this would be up to snuff.  If so, where should I put this so it can be accepted in a pull request? If not let me know what to fix/what should be included.  Thanks.  


# Feature comparison
| Features	  |  Paramaterized tests |  Custom Marking | Assert Rewrites  |   |
|---|---|---|---|---|
|  Unittest2	 | With some setup  | Limited			  |  No |   |
| Pytest		|Yes					 |Yes			 |Yes|




Beyond these great features are the philosophical differences with unittest being based on Java's junit and pytest being an elegant and pythonic based alternative that can run many(if not most) of the tests that unittest does.  These differences along with a vibrant community that has great documentation and support make pytest a solid choice so there's less boilerplate/setup and more testing.

**Comment by nicoddemus** [comment]
Hi @ryan-jr thanks for writing.

I think this a step in the good direction. I'm not sure if a yes/no table format is adequate though: IMHO they tend to be biased towards one of the tools. For example, Assert Rewrite is a specific pytest feature, it is unfair to say "unittest doesn't implement it" (giving the impression that *it should*).

Perhaps a side-by-side comparison of each feature would be better:

| Features	  |  unittest  |  pytest  |
|---|---|---|
|  assertions  | Must be done with various `self.assert*` messages | Use plain `assert` statements due to assertion rewrite |
| test collection/discovery | `python -m unittest` will discover `TestCase` subclasses and run them | Collects `test_*.py` and `*_test.py` files and runs classes named `Test*` and `test_` functions by convention|
| Custom markins | ... | ... |
| Parametrized tests | ... | ... |
| test resource creation/destruction | `setUp/tearDown`, `setUpClass/tearDownClass` | `fixtures`, which can be scoped |
| ... | ... | ... |

... and so on.

But this is just my opinion of course. 😁

**Comment by ryan-jr** [comment]
Thanks for the input, I'll integrate the feedback/updates to my original post tonight when I get home!

**Comment by nicoddemus** [comment]
Awesome, thanks!

**Comment by aeltanawy** [comment]
@nicoddemus and @ryan-jr  anyone is working, or has already worked, on this case? Happy to tackle it if not.

**Comment by nicoddemus** [comment]
@aeltanawy not that I'm aware of. Feel free to work on it and open a PR! 👍

**Comment by mcsitter** [comment]
I had a look into the `faq.rst`. Except for very minor changes the FAQ is more then half a decade old. There are a lot of things that could be changed, updated, removed. Previous versions of the docs will still be available anyways. BTW: the link in the original post is broken due to the missing `en/` in the url and does not redirect.

Some of the things I noticed:
1. Nose has nose2 as a successor.
2. We are way past pytest-2.0 and support for unittest seems to be great according to `unittest.rst`. `nose.rst` has info about compatibility as well. Both documents seem to be maintained. Also note `existingtestsuite.rst`. Maybe linking appropriately and stating that pytest has good support for both while also having a lot of other features would suffice?
3. The notice about setuptools is also rather old.
> As of mid-2013, there shouldn't be a problem anymore.
4. At the top of `xunit_setup.rst` is a note about using xunit and fixtures.
5. pytest-django works rather well I think. Another outdated part.

I conclude that the note at the top about the FAQ existing for historic reasons is very much true, which is funny for something written 7 years ago. Instead of
1. improving the comparison
I propose to do one of
2. remove the FAQ entirely 
3. at least the completly outdated parts. GitLens opens eyes for this one.
4. fill it with meaningful content.
The pytest documentation is redundant in many places. Especially because this is not caused by included files, maintaining the same information in different places is tedious. This is why I personally favor option 2.

**Comment by nicoddemus** [comment]
I agree that updating it seems more trouble than it is worth, because that same information is already available in other places.

👍 for removing it then.
