### ISSUE TITLE
TDD reading from excel with pytest.mark.parametrize

### ISSUE THREAD

**Issue by LABETE** [pytest-dev/pytest#1610]
Hi,

I am delcaring a list: 
    lst="" 
and when the execution starts I have a fixture function with scope session reading data from an excel file and filling the list: 
    lst = [('val1', 'val2', 'val3'),('val1', 'val2', 'val3')] 
after that I am passing the list to:
@pytest.mark.parametrize('var1,var2,var3', lst)

but the test is skipped with the following message:

testpath[var10-var20-var30] SKIPPED

if I hard-code the values it works is it an issue? or is expected? and is there a workaround that I can use?

pytest==2.9.1
Windows 8

**Comment by The-Compiler** [comment]
You have a fixture which fills out a `@pytest.mark.parametrize` call? That sounds impossible :wink:.

Anyways - something is probably calling `pytest.skip` there - maybe starting pytest with `-rs` tells you more?

**Comment by nicoddemus** [comment]
I understood that you have a global list `lst` which you use to parametrize a test, but the `lst` is filled by session-scoped fixture. If I understood you correctly, this is currently not possible because parametrization happens during collection (iow, during import), so by the time your session fixture executes the parametrization has already occurred is "skipped" because the parametrization resulted in no tests (to see what I mean, initialize `lst` with something else instead of an empty list).

**Comment by LABETE** [comment]
Yes nicoddemus I try it and it works hardcoding the values to the list but I want to read the data from excel, Is there a way of doing what I want with pytest?

**Comment by nicoddemus** [comment]
With current parametrization, your only choice is to read your excel file during collection. So let's say you are doing this:

```python
values = []

@pytest.mark.parametrize(v, values)
def test_values(v):
    check_value(v)

@pytest.fixture(scope='session', autouse=True)
def fill_values():
    values[:] = read_values_from_excel()
```

As I said, parametrization happens during import time, so by the time `fill_values` executes the parametrized tests were already generated.

I see two approaches here:

## 1) read values during collection 

This will let you parametrize your tests as you want, but at the cost of increased collection time:

```python
values = read_values_from_excel()

@pytest.mark.parametrize(v, values)
def test_values(v):
    check_value(v)

```

## 2) forego parametrization and test values within the test

In this approach you no longer parametrize the test, but make the test check all values explicitly:

```python
def test_values(values):
    for v in values:
        check_value(v)

@pytest.fixture(scope='session')
def values():
    return read_values_from_excel()
```

The problem with this is that you lose parametrization benefits: if one of the checks fails, the rest is skipped because the test function will stop at that point.

I would go with **1** if reading from excel is quick enough, otherwise I would go with **2**. **2** might be more attractive as well if you have several tests which use the same excel file.

Hope that helps!

**Comment by LABETE** [comment]
I have thought at first in the second approach but the first one works perfectly as I want.

Thanks

**Comment by The-Compiler** [comment]
I assume this can be closed then - glad you got something to work, and sorry for my initial thought being wrong :smile:
