### ISSUE TITLE
teardown_function() with no argument list crashes

### ISSUE THREAD

**Issue by okken** [pytest-dev/pytest#1728]
- [x] Include a detailed description of the bug or suggestion

These functions appear to work even if someone forgets to list the module/function argument:
- setup_module()
- teardown_module()
- setup_function()

However, this crashes:
- teardown_function()

Example file test_foo.py, listing at end.

```
> py.test test_foo.py
<some output deleted>
>   self.addfinalizer(lambda: fin(self.obj))
E   TypeError: teardown_function() takes no arguments (1 given)
<some output deleted>
```

Suggestion. look at how setup/teardown module and setup_function are handled, because they don't crash.

- [ ] `pip list` of the virtual environment you are using

Currently looking at an anaconda install, and the list is huge.

- [x] py.test and operating system versions

> python --version
Python 2.7.10 :: Anaconda 2.4.0 (64-bit)
> py.test --version
This is pytest version 2.8.1, imported from C:\Python\lib\site-packages\pytest.pyc

However, I've tried it with Python 3.5.2 and most recent pytest on a mac without anaconda, and that's broken too.

- [x] Minimal example if possible

test_foo.py:

```python
from __future__ import print_function

def test_something():
    print('\nIn test_something()')

def teardown_function():
    print('\nIn teardown_function()')
```

**Comment by nicoddemus** [comment]
Thanks @okken!

(edited your post for formatting, hope you don't mind)

**Comment by nicoddemus** [comment]
I see the error happening with `teardown_function()` as you mention, but when I add a `setup_function()` method I get a similar error for the `setup_function()` as well:

```python
from __future__ import print_function

def setup_function():
    print('\nIn setup_function()')

def test_something():
    print('\nIn test_something()')

def teardown_function():
    print('\nIn teardown_function()')
```

```
$ py.test
> setup_func_or_method(self.obj)
E TypeError: setup_function() takes 0 positional arguments but 1 was given
```

According to the [docs](http://doc.pytest.org/en/latest/xunit_setup.html), all `setup/teardown` functions and methods receive an argument, so the behavior seems correct to me.

Hmm I made some other tests, and it seems there's some inconsistency, because `setup_module` and `teardown_module` can receive or not the `module` argument, while `*_method` and `*_function` must always receive it.

So it seems the problem is actually that `*_module` and `*_function/*_method` behave differently: the former can receive or not an object, while the latter ones must always receive an object.

**Comment by nicoddemus** [comment]
Digging a little further, it is clear why this is consistent: `Module` explicitly handles the optional argument:

```python
        if setup_module is not None:
            #XXX: nose compat hack, move to nose plugin
            # if it takes a positional arg, its probably a pytest style one
            # so we pass the current module object
            if _has_positional_arg(setup_module):
                setup_module(self.obj)
            else:
                setup_module()
```

(similar code for `teardown_module`)

IMO the correct solution is to apply the same handling for `*_method` and `*_function` forms to keep consistency (the other way around would break backward compatibility).

**Comment by okken** [comment]
Awesome. I'd like the option of not providing the parameters if the aren't needed. I frequently forget them.

**Comment by RonnyPfannschmidt** [comment]
i propose creating a helper function to call an attribute with an optional "context"
