### ISSUE TITLE
`pytest` conflict with logilab-common

### ISSUE THREAD

**Issue by sebastinas** [pytest-dev/pytest#1833]
While updating the Debian package for pytest I noticed that pytest now ships a `pytest` binary and it's supposed to be the new default entrypoint. However, logilab-common provides the same entrypoint since many versions. #1662 claims that this conflict has been resolved, but logilab-common still contains the entrypoint. Were there any discussions with the logilab developers about this issue?

**Comment by The-Compiler** [comment]
We - that is both pytest developers and me together with @pcmanticore who's the pylint maintainer - tried to talk to logilab to drop their `pytest` entrypoint from `logilab-common`, but unfortunately, that never happened.

FWIW, I think nothing uses `pytest` in `logilab-common` except logilab internally. However, it was very common for people (who have `pylint` as well as `pytest` installed) to get confused because they're running `pytest` and get a non-working test runner, and we get to take the blame :wink:

Since about a year, however, `pylint` and `astroid` don't depend on `logilab-common` anymore, which will probably make it possible for many distributions to drop `logilab-common` altogether. Looking at the reverse dependencies of logilab-common for python2/python3 on Debian:

- astroid: doesn't need `logilab-common` anymore
- pylint: doesn't need `logilab-common` anymore
- logilab-astng: [Got replaced](https://www.logilab.org/project/logilab-astng) by `astroid` a long time ago and has no reverse dependencies on its own - I don't see it packaged for stretch/sid however
- python-logilab-constraint: Also not packaged in stretch/sid it seems, and nothing needs it?

**Comment by sebastinas** [comment]
Thank you for the information! Do you have any pointers to past discussion with logilab about this issue?

Looking at the current reverse dependencies of `logilab-common` (ignoring `logilab-constraint`) the following are left in Debian unstable:
```
$ dak rm -Rn logilab-common logilab-constraint
Will remove the following packages from unstable:

logilab-common |    1.2.2-1 | source
logilab-constraint |    0.5.0-2 | source
python-logilab-common |    1.2.2-1 | all
python-logilab-constraint |    0.5.0-2 | all
python3-logilab-common |    1.2.2-1 | all

...

Checking reverse dependencies...
# Broken Build-Depends:
pylint-celery: python-logilab-common
               python3-logilab-common
pylint-flask: python-logilab-common
              python3-logilab-common

Dependency problem found.
```

For `pylint-flask` I prepared https://github.com/jschaf/pylint-flask/pull/4 and filed https://bugs.debian.org/835601. `pylint-celery` uses `logilab.common.testlib`, but it doesn't seem to use the `pytest` binary.

**Comment by The-Compiler** [comment]
There were various discussions, but here's the one I found:

- Original mail I didn't find, quoted in the one below
- [Their answer that they still need it](http://lists.logilab.org/pipermail/python-projects/2015-June/003605.html)
- [A "just joking" follow up claiming they were first](http://lists.logilab.org/pipermail/python-projects/2015-June/003606.html)
- [Me telling them that's inaccurate](http://lists.logilab.org/pipermail/python-projects/2015-October/003615.html)

I also remember another discussion in their bugtracker which I can't find anymore, and I think the pylint maintainer also talked to them privately, but I'm not 100% sure anymore on that (it's been over a year since I talked to him about it).

**Comment by flub** [comment]
@sebastinas It sounds like your are able to resolve this in Debian?  That would be great news for all involved.  To be fair we where afraid of causing trouble for you but we where all a bit stuck between a rock and a hard place.  If you can make this change in Debian that would be awesome.  If so would you mind closing the issue here if there's nothing else to be done by us?  Thanks

**Comment by sebastinas** [comment]
I will try to take this up with logilab-common upstream. I don't see anything to be done here, so I'm closing this issue. Thanks for all the links.

**Comment by The-Compiler** [comment]
Thank you! Can you please keep us updated if there's any news?

**Comment by sebastinas** [comment]
A patch renaming the binary from `logilab-common` is pending review. See https://www.logilab.org/patch/8425481for details.

**Comment by dlax** [comment]
logilab-common version 1.3.0 just got released, it does not ship `pytest` binary anymore.

**Comment by RonnyPfannschmidt** [comment]
@dlax thanks for the update
