### ISSUE TITLE
pytest_keyboard_interrupt hook is also called with --maxfail

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#1865]
When using `-x` / `--maxfail` the [Interrupted exception](https://github.com/pytest-dev/pytest/blob/86ec3f37afbf3238a437b92d30115d87a9cf3141/_pytest/main.py#L528-L530) is thrown, and gets handled in the same place as `KeyboardInterrupt` (https://github.com/pytest-dev/pytest/blob/86ec3f37afbf3238a437b92d30115d87a9cf3141/_pytest/main.py#L99-L106), because it is a subclass.

Therefore I think the hook name is confusing / misleading.
If this behavior is intentional, it should get added to the documentation at least.

I have noticed this, because pytest-testmon uses this hook to not save its data: https://github.com/tarpas/pytest-testmon/blob/55c89bb3df65c94e226ead8dd465f3dd5bb8927b/testmon/pytest_testmon.py#L173-L174
Here a check using `excinfo.typename` could be added to handle 'Interrupted' different from 'KeyboardInterrupt'.

btw: is there a way to import the `Interrupted` class from pytest?

**Comment by The-Compiler** [comment]
FWIW, `Interrupted` being a subclass of `KeyboardInterrupt` sounds weird to me...

**Comment by nicoddemus** [comment]
I agree. I think that we should:

1. Subclass `Interrupted` from something else (`RuntimeError`?)
2. Make `Interrupted` part of the public API so plugins can raise or catch it; perhaps by making it available in the `pytest` namespace? Also, how about renaming it to `SessionInterrupt`?

This has to be done carefully, because there are a number of places which handle `KeyboardInterrupt` on pytest's code base that will have to be changed to also handle `SessionInterrupt`.

I also noticed that `Exit` also subclasses `KeyboardInterrupt`.

**Comment by The-Compiler** [comment]
> 1. Subclass `Interrupted` from something else (`RuntimeError`?)

If you do `except RuntimeError:`, would you expect `Interrupted` to be caught (I don't)? If not, it should simply subclass `Exception`.

**Comment by nicoddemus** [comment]
Good point!
