### ISSUE TITLE
session scoped fixtures get executed multiple times. I suspect I am using pytest wrong

### ISSUE THREAD

**Issue by do3cc** [pytest-dev/pytest#1878]
Hi,

I am using pytest 3.0.1.

I've created a lot of test fixtures and wanted to push them to module scope.
I now see exceptions that show that they get executed twice.

I suspect that by importing my fixtures from one test module to another, I created a second session scoped fixture.

So in test_a.py I do:
```
fixture
def a():
    pass
```
and in test_b.py I do:
```
from .test_a import a

def test_lala(a):
    pass
```

Can you confirm my suspicion?

**Comment by RonnyPfannschmidt** [comment]
due to importing py.test sees 2 different fixtures at different locations

there should probably bea warning about that one

**Comment by nicoddemus** [comment]
I suggest to move your fixtures to a `conftest.py` file, importing them is really not recommended because it might bring some problems as @RonnyPfannschmidt mentioned. 

Just create a `conftest.py` file at the root of your test files and put your fixtures there and they will be available automatically for all test modules below it.
