### ISSUE TITLE
Module-level skip no longer works

### ISSUE THREAD

**Issue by astrofrog** [pytest-dev/pytest#1885]
I used to make use of the ability to invoke ``pytest.skip`` to skip a whole test file (rather than having to decorate dozens of functions):

```python
if not SOME_PACKAGE_INSTALLED:
    pytest.skip()
```

but am now getting errors with pytest 3.0:

```
Using @pytest.skip outside of a test (e.g. as a test function decorator) is not allowed. Use @pytest.mark.skip or @pytest.mark.skipif instead.
```

Is there a way to simply skip a whole file instead?

**Comment by The-Compiler** [comment]
Are you aware of [`pytest.importorskip`](http://docs.pytest.org/en/latest/builtin.html?highlight=importorskip#_pytest.runner.importorskip)? That seems to fit your usecase nicely - instead of:

```python
try:
    import some_package
except ImportError:
    pytest.skip()
```

do:

```python
some_package = pytest.importorskip('some_package')
```

**Comment by nicoddemus** [comment]
We have removed this ability because it was a common error to use `pytest.skip` as a decorator (as opposed to using `pytest.mark.skip` as a decorator) and skip the entire module instead of just the decorated test.

`importorskip` is probably the best choice if you are just checking if a package is installed like @The-Compiler said, but if you have some other condition that you would like to check as well, you can set a [`pytestmark`](http://doc.pytest.org/en/latest/example/markers.html?highlight=pytestmark#marking-whole-classes-or-modules) global variable:

```python
if not SOME_RUNTIME_CONDITION:
    pytestmark = pytest.mark.skip(reason='reasons')
```

**Comment by astrofrog** [comment]
@The-Compiler @nicoddemus ``importorskip`` fits my needs, thanks! (and good to know about the other way too just in case)
