### ISSUE TITLE
Monkeypatch docs lost method reference between 3.0.1 and 3.0.2

### ISSUE THREAD

**Issue by alex** [pytest-dev/pytest#1909]
Compare:

http://doc.pytest.org/en/3.0.1/monkeypatch.html

vs

http://doc.pytest.org/en/3.0.2/monkeypatch.html

I suspect this was caused by https://github.com/pytest-dev/pytest/commit/519f02b0149c3150c15bf240c09f362f5a391dd5#diff-425daef754438812ec1a0e4d3aeaeff8

**Comment by RonnyPfannschmidt** [comment]
good find, https://github.com/pytest-dev/pytest/commit/519f02b0149c3150c15bf240c09f362f5a391dd5#diff-425daef754438812ec1a0e4d3aeaeff8L62 is the exact place

**Comment by nicoddemus** [comment]
Yep, my bad! I removed `:members:` because it contained members which were no longer on the class (hence generating warnings) and I thought `autoclass` was enough... but failed to check it. :sweat: 

Opened #1910, will merge as soon as tests pass so the docs are OK again.

Thansk @alex for the report! :grin:
