### ISSUE TITLE
Failed assertions in external files are lacking hints

### ISSUE THREAD

**Issue by qua-bla** [pytest-dev/pytest#1941]
I have a a set of assertions that I am using in several `test_` files. I have defined a function inside a utils module that makes all the required assertions. However, all the nice hints about the failed assertions like "Left contains more items" are not working if the assertions are made outside of the `test_` file.

## In file assertion (works as expected)
```py
def test_x():
    assert ['a', 'b'] == ['a']
```

Output

```py
    def test_x():
>       assert ['a', 'b'] == ['a']
E       assert ['a', 'b'] == ['a']
E         Left contains more items, first extra item: 'b'
E         Use -v to get the full diff
```

## External assertion (lacking hints)

`external.py`:

```py
def f():
    assert ['a', 'b'] == ['a']
```

```py
import external

def test_x():
    external.f()
```

Output

```py
    def test_x():
>       external.f()

test_x.py:4: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def f():
>       assert ['a', 'b'] == ['a']
E       AssertionError

external.py:2: AssertionError
```

**Comment by nicoddemus** [comment]
Hi @qua-bla,

The mechanism that allowed that was called "assertion reinterpretation", and it was filled with perils and possibility of writing code that acted in surprising ways. Test modules themselves didn't have this problem because they have "assert rewriting" in place which is much more reliable and works with calls that has side-effects.

In pytest 3.0 assertion reinterpretation has been removed (see "Assert reinterpretation is gone" in [What's new in pytest 3.0](http://blog.pytest.org/2016/whats-new-in-pytest-30)), so modules besides tests, `conftest.py` files and plugins must be registered manually *before* being imported to benefit from assertion rewriting.

You can call `pytest.register_assert_rewrite` before the module is imported somewhere in your codebase (for example at your root `conftest.py` file):

```python
import pytest
pytest.register_assert_rewrite('external')
import external
```

**Comment by qua-bla** [comment]
Calling `pytest.register_assert_rewrite` for all external modules with assertions in `conftest.py` works great. Thanks!

**Comment by nicoddemus** [comment]
Great!

Just a tip: if your external modules have fixtures and whatnot, it might make more sense to declare them as plugins in your `conftest.py` file rather than importing them directly:

```python
pytest_plugins = ['external']
```

This will make fixtures declared in `external` available for all test modules as usual plus their asserts will be rewritten automatically.
