### ISSUE TITLE
What is the best way to parametrize test with python code?

### ISSUE THREAD

**Issue by proofit404** [pytest-dev/pytest#2061]
I want to test an API of some package with different ways of its usage. At first version I ended up with lots of tests with similar setup and tear down logic. The only difference in those tests are API calls in the middle of the test function. I try to use parametrize mechanism for this purpose. This is what I use as current solution to this problem.
```python
import pytest


class CodeCollector(object):

    def __init__(self):

        self.collected = []

    def __call__(self, f):

        self.collected.append(f)

    def __iter__(self):

        return iter(self.collected)


let_redefine = CodeCollector()


@pytest.mark.parametrize('f', let_redefine)
def test_deny_to_redefine_let(f):

    with pytest.raises(Exception):
        f()


@let_redefine
def x():
    raise Exception('We are here.')


@let_redefine
def y():
    raise Exception('We are here.')


@let_redefine
def z():
    raise Exception('We are here.')
```
However I doubt if this approach is optimal or fit the py.test way of doing things.

**Comment by flub** [comment]
Hi,

It might be helpful to show more specifically what you are trying to test, the code above is fairly abstract and indeed looks a bit strange to me.  This is because your solution tries to parametrise the entire unit under test rather then provide different parameters to the unit under test.

Your description mentions that the tests share a lot of common setup and teardown code.  This sounds to like it might be worth looking to turn that into one or several fixtures to encapsulate this setup or teardown.  Then you still write multiple tests because they all have a unique unit-under-test while the fixtures take care of the setup and teardown.

Hope that helps, if not please provide a more detailed example of your problem.

**Comment by proofit404** [comment]
Thanks for quick reply!

Here is some example of test [unit](https://github.com/proofit404/dependencies/blob/master/tests/test_injector.py#L475-L493). It uses `exec` right now. But you can see any way that I'm trying to test same behavior of different API usage. Attribute deletion in this case.

**Comment by nicoddemus** [comment]
@proofit404 is this an issue for you? Just revisiting old issues and see what can be closed. 😁

**Comment by proofit404** [comment]
Hi, I can't find an answer to solve this completely. But yes, let's close this to reduce the noise.
