### ISSUE TITLE
Capturing output causes test to fail.

### ISSUE THREAD

**Issue by GandaG** [pytest-dev/pytest#2172]
When running with capture disabled, test passed but with enabled test fails with no reason given. Not sure if relevant, but the test is failing on a c extension module built with cython.

Windows 64-bit, Python 3.4.5 32-bit, pytest 3.0.5

A [screenshot](http://i.imgur.com/wFtsWeo.png) with `pip list` and the results of running `py.test -s` and `py.test` respectively. `bethesdalib` is the package being tested.

The test code:

```
import os
from bethlib.tesfive import pex, esp

def test_pex():
    ...

def test_esp():
    data_folder = os.path.join(os.path.abspath(os.path.dirname(__file__)), "data", "esp")
    for plugin_file in next(os.walk(data_folder), (None, None, []))[2]:
        plugin = esp.parse(os.path.join(data_folder, plugin_file))
        with open(os.path.join(data_folder, plugin_file), 'rb') as open_plugin:
            assert open_plugin.read() == esp.to_string(plugin)
```

Thanks!

**Comment by nicoddemus** [comment]
Hi @GandaG,

pytest's exception capture in `fd` mode is probably causing the C extension module to fail somehow. It is *probably* the fault of the extension module not handling the fact that the out/err handles have been redirected, but is hard to know without debugging this somehow.

What happens if you run pytest with `--capture=sys`?

Could you try running pytest with a debugger attached and see where it crashes?

**Comment by GandaG** [comment]
🤦‍♂️ Sorry, I just went full stupid. I am redirecting the output from the extension module to handle errors. It functions perfectly if I remove that part.

Thank you! And sorry :/

**Comment by nicoddemus** [comment]
> Thank you! And sorry :/

No worries! Thanks for closing the issue then.
