### ISSUE TITLE
Xfail marker for non-standard Item missing `obj`

### ISSUE THREAD

**Issue by vidartf** [pytest-dev/pytest#2231]
Hi!

We're currently writing a plugin for py.test that collects custom tests (i.e. our own class that inherits from `pytest.Item`). I want to add an xfail marker to these, so I try to do this dynamically via `item.add_marker()`. If I do this, and run the tests, it will fail on [this line](https://github.com/pytest-dev/pytest/blob/da5a3dba8747c1497782ebf7e1b6824d915577a4/_pytest/skipping.py#L115): 

```python
d.update(self.item.obj.__globals__)
```

Here, the `skipping` plugin assumes that the item has an `obj` attribute, which again has a `__globals__` attribute. I can side-step this issue by simply adding a dummy variable here, with an empty `__globals__` dict, but I want to ensure that:
 - I am not doing something stupid by adding the dummy
 - I am not doing something wrong elsewhere since I am missing the `obj` attribute
 - I report this so that I minimize the risk of our plugin failing for similar reasons in the future

Am I doing it right? 😄

**Comment by nicoddemus** [comment]
I think the workaround is adding a dummy object like you propose.

But I also think `skipping` shouldn't require that `obj` attribute at all since it is not part of [`Item`'s](https://github.com/pytest-dev/pytest/blob/da5a3dba8747c1497782ebf7e1b6824d915577a4/_pytest/main.py#L507) interface.

Would you mind to submit a PR which removes that requirement from there? I think this should do it:

```python
def _getglobals(self):
    d = {'os': os, 'sys': sys, 'config': self.item.config}
    if hasattr(self.item, 'obj'):
        d.update(self.item.obj.__globals__)
    return d
```

What do you think @RonnyPfannschmidt?

**Comment by vidartf** [comment]
I see now that an alternative solution was proposed in #2142 .

**Comment by nicoddemus** [comment]
I think they complement each other, with your's fixing the underlying problem more correctly. 👍
