### ISSUE TITLE
capsys not capturing on Python 2.7

### ISSUE THREAD

**Issue by cjw296** [pytest-dev/pytest#2327]
This works on 3.5:

https://travis-ci.org/cjw296/sybil/jobs/214145869

But on 2.7, the capsys is empty:

https://travis-ci.org/cjw296/sybil/jobs/214145867#L301
https://travis-ci.org/cjw296/sybil/jobs/214145867#L314

**Comment by cjw296** [comment]
Well, this is the diff that got things working:

https://github.com/cjw296/sybil/commit/d6cf19af44b341cf3773791b74a56d6eb5bb91cf

My guess is that unittest in py2.7 is doing something that makes capsys sad. Probably not worth bottoming out...

**Comment by cjw296** [comment]
nb: `test_nose` below the test I updated, that uses capsys and works fine...

**Comment by RonnyPfannschmidt** [comment]
thansk for the followup

**Comment by cjw296** [comment]
@RonnyPfannschmidt - weirder still, this also works: https://github.com/cjw296/sybil/commit/791fe7477ba420188ec4f72e20dff68d3366b43e

...and here we have it:
https://hg.python.org/cpython/file/v2.7.11/Lib/unittest/runner.py#l127

d'oh. 

I thought a `-c fd` would work with that? It didn't...

**Comment by RonnyPfannschmidt** [comment]
Import time sys.stdout differs from test time sys.stdout

This is a bug in unittest, but pytest should protect you against it

**Comment by asottile** [comment]
hello, first off thank you for the issue!

python 2.x support has ended for pytest core.

we've decided in #7296 to close the python-2-specific issues to free up some space in our backlog.  however, in accordance to our [python 2.7 and 3.4 support](https://docs.pytest.org/en/latest/py27-py34-deprecation.html) community patches *will still be accepted* to the `4.6` series to fix bugs for python 2.  (so if this issue is important to you and you have a patch to fix it, feel free to make a PR targeting the 4.6.x branch despite this ticket being closed).
