### ISSUE TITLE
Disallow test skipping in circle CI

### ISSUE THREAD

**Issue by VinodhiniHarish** [pytest-dev/pytest#2349]
Requirement:
My Project has a requirement to run selenium test cases only on master builds. Which is done by unittest decorator @skipunless(CI_BRANCH=master). 
Now I have a new requirement that I the selenium test cases should also run when developer wants to(even if it is not a master build).
Basically I need to override the unittest decorator with a git command(git commit/push) so that the test cases gets picked up and executed in Circle CI.
[CI skip] given in git commit actually skips the test. What I am looking for is a command that will override the skip decorator.

Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` of the virtual environment you are using
- [ ] pytest and operating system versions
- [ ] Minimal example if possible

**Comment by nicoddemus** [comment]
Hi,

Sorry I'm confused, I'm not sure I understand your requirements.

> My Project has a requirement to run selenium test cases only on master builds. Which is done by unittest decorator @skipunless(CI_BRANCH=master).

Right.

> Now I have a new requirement that I the selenium test cases should also run when developer wants to(even if it is not a master build).
Basically I need to override the unittest decorator with a git command(git commit/push) so that the test cases gets picked up and executed in Circle CI.

That's not the part that's not clear to me. Do you want developers to be able to add some special text to the commit message so that the selenium tests will execute on their branch? I'm assuming that from your next phrase:

> [CI skip] given in git commit actually skips the test.

Can you please explain the workflow you are trying to accomplish better?

(Of course, I'm assuming you are using pytest as a test runner even though you mentioned the `skipunless` decorator from `unittest`).
