### ISSUE TITLE
using pytest.mark.skipIf doesn't skip anything, but calling pytest.mark.skipif (all lower case) works

### ISSUE THREAD

**Issue by knifewine** [pytest-dev/pytest#2355]
I can provide more details if needed, just ask.

pytest.mark.skipIf(True) does not skip anything

pytest.mark.skipif(True) works though.

This is pretty confusing.

Python 2.7, pytest 3.0.7.

**Comment by RonnyPfannschmidt** [comment]
py.test --strict would complain,

@hpk42 @nicoddemus should we do something like we do for parameterize wrt the possible spelling mistakes ?

**Comment by nicoddemus** [comment]
Is this a common mistake? After all, Python is case-sensitive...

If we decide to do something about it, we can easily do a check like we do we parametrize like @RonnyPfannschmidt suggests.

**Comment by vit0rg** [comment]
isInstance() also doesn't work, but isinstance() works fine, same for skipIf() and skip_if(), etc. There is no reason to complain that nonexistent function doesn't work, it's pretty expected behavior.

**Comment by knifewine** [comment]
I wasn't aware it's a non-existent function, but point taken. It's a surprising usability issue imo, but was just trying to be helpful by reporting what I ran into. Cheers.

**Comment by nicoddemus** [comment]
It is not the same as `isInstance` because `isInstance` will blow up immediately while `pytest.mark.skipIf` will silently create a new marker named `skipIf` that does nothing, which I believe was the point @knifewine was making.

It might be worth doing a similar check for all builtin markers, I was just wondering if that was a common mistake or not (`parametrize` being misspelled as `parameterize` was, so much we decided to warn against it).
