### ISSUE TITLE
Unable to use doctest_namespace fixture for package docstrings

### ISSUE THREAD

**Issue by abstiles** [pytest-dev/pytest#2379]
I am attempting to use the `doctest_namespace` fixture to perform some setup which I do not want to publish as part of the documentation of a package, but when I try to configure something similar to the documented example, the fixture does not appear to accomplish anything. Is this broken, or are there some assumptions missing in the documentation? I am attempting to duplicate the same setup as the example on [this page](https://docs.pytest.org/en/latest/doctest.html#the-doctest-namespace-fixture).

A trivial example:

```
.
├── src
│   └── testpackage
│       └── __init__.py
└── tests
    └── conftest.py
```

__init__.py:

```
""" An example doctest expecting 'hello' to exist.

    >>> hello.world()
    'hello world'
"""
```

conftest.py:

```
import pytest

class Hello(object):
    def world(self):
        return 'hello world'

@pytest.fixture(autouse=True)
def add_hello(doctest_namespace):
    doctest_namespace['hello'] = Hello()
```

The result:

```
$ pytest src tests --doctest-modules
============================= test session starts ==============================
platform darwin -- Python 2.7.8, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /private/tmp/testdoctest, inifile:
collected 1 items

src/testpackage/__init__.py F

=================================== FAILURES ===================================
____________________________ [doctest] testpackage _____________________________
001  An example doctest expecting 'hello' to exist.
002
003     >>> hello.world()
UNEXPECTED EXCEPTION: NameError("name 'hello' is not defined",)
Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/doctest.py", line 1315, in __run
    compileflags, 1) in test.globs

  File "<doctest testpackage[0]>", line 1, in <module>

NameError: name 'hello' is not defined

/private/tmp/testdoctest/src/testpackage/__init__.py:3: UnexpectedException
=========================== 1 failed in 0.04 seconds ===========================
```

I am using Python 2.7 on Mac OS 10.11. Package versions from `pip list` are as follows:

```
appdirs (1.4.3)
packaging (16.8)
pip (9.0.1)
py (1.4.33)
pyparsing (2.2.0)
pytest (3.0.7)
setuptools (35.0.1)
six (1.10.0)
wheel (0.29.0)
```

**Comment by nicoddemus** [comment]
Fixtures defined in `conftest` files are only available for test modules at the same level or below, I suspect that is what is happening here. Does the example work you move your `conftest.py` file to `testpackage`?

**Comment by abstiles** [comment]
Ah yes, it does. Thanks. Is there any way to configure this fixture without polluting the `src` tree with test configuration logic? A command-line argument, perhaps?

**Comment by nicoddemus** [comment]
Sorry for the late response, this one slipped through the cracks.

You can put it into a module which is importable named something like `myplugin.py`, and pass in the command-line: `-p myplugin`. `-p MOD` makes pytest load MOD as a plugin, which is almost the same as a `conftest` file.

You can add the same flag in your `pytest.ini`:

```ini
[pytest]
addopts = -p myplugin
``` 

I'm closing this for now, feel free to ask any further questions.

**Comment by lazarillo** [comment]
Thank you, @nicoddemus for your information regarding how to keep the `src` tree uncluttered, but I cannot manage to figure it out.

    .
    ├── src
    │   └── mypkg
    │       └── __init__.py
    │       └── mymodule.py
    └── tests
        └── conftest.py

In my situation, all of the fixtures are in `conftest.py`, like usual. `conftest.py` is living underneath `tests`, whereas the code of interest lives under `src/mypkg`.  After `pip install`ing the package, when I provide the command line of `pytest -p conftest --doctest-modules ../src/mypkg/mymodule.py`, I get an `ImportError` that there is no module named `conftest`.

When I instead presume that I can source the entire pacakge and try `pytest -p mypkg --doctest-modules mymodule.py`, I get an error that the "imported module `__file__` attribute does not match the test file we want to collect".

I also tried setting the `pytest.ini` as you suggested, both using `mypkg` and `conftest`, no luck with either.

Can you please provide a more full example of how we can configure things to avoid polluting the namespace? I know that I am setting up that `myplugin.py` file wrong, but I don't understand how or why.  Are you saying that I have to set up an entire plugin and install that? Seems like a lot of work just to be able to read in my `conftest`.  If I do need to set up an entire plugin, what should it contain?  Just the `doctest`-related fixtures?  Or should it just be my entire `conftest.py` file?

---

For now, I have unfortunately cluttered my `src` tree because I cannot figure out how to properly do this.
