### ISSUE TITLE
Option to suppress exit code 5 (no tests run)

### ISSUE THREAD

**Issue by jakirkham** [pytest-dev/pytest#2393]
For the most part, I think the addition of PR ( https://github.com/pytest-dev/pytest/pull/817 ) to have a special exit code to denote no tests run was a good idea. However when I start out a project, I may not have any tests as there is no real code. Still I would like to get everything up and running (i.e. CIs). It would be nice in these cases like this to have an option to suppress this behavior and have exit code 0 returned instead.

**Comment by The-Compiler** [comment]
FWIW you can do something like

```python
def test_placeholder():
    pass
```

**Comment by RonnyPfannschmidt** [comment]
im closing this, as the very reason for having and not suppressing this error code is to learn of broken/gone bad ci setups, its just as easy to simply put a first green test you know you will fill out later than to opt out of something you may forget about

**Comment by nicoddemus** [comment]
Thanks for the suggestion @jakirkham, but I agree with @RonnyPfannschmidt that we shouldn't add yet another option to pytest to handle this case specially because an alternative solution is trivial and easy to do, while the possible drawbacks can be a pain (forgetting later that the option is set like @RonnyPfannschmidt mentioned).

**Comment by mkleina** [comment]
But what in case the `-m` (markers) option is present and provided marker is not found? I am working on the case where multiple test suites are run in particular order using tox.

```
[testenv:all]
commands =
    pytest testuite1/ {posargs}
    pytest testuite2/ {posargs}
    pytest testuite3/ {posargs}
```

where `{posargs}` are arguments passed to tox. When I want to preserve order, but filter out selected marker, for example:

```shell
tox -e all -- -m smoketest
```

`pytest` command fails when no markers found and no further tests are started because of exit code 5.

Any idea how to substitute this use case?

**Comment by blueyed** [comment]
@mkleina 
You can wrap the command:
`sh -c 'pytest testsuite1/ {posargs}; ret=$?; [ $ret = 5 ] && exit 0 || exit $ret'`

I am using the following `p` wrapper myself:
```sh
#!/bin/sh

pytest "$@"
ret=$?
if [ "$ret" = 5 ]; then
  echo "No tests collected.  Exiting with 0 (instead of 5)."
  exit 0
fi
exit "$ret"
```

**Comment by RonnyPfannschmidt** [comment]
we ought to have a pytest plugin to do that for people that truely need it  (since a shell wrapper is pretty anti-portable

**Comment by RonnyPfannschmidt** [comment]
@ChiKenNeg nobody worked on a plugin for this as far as i know, if you'd like to have one, i strongly suggest making one

**Comment by yashtodi94** [comment]
A little hack. But something on these lines should work fine. (`Pytest v4.0.2`)

Add this to your conftest.py:

```
def pytest_sessionfinish(session, exitstatus):
    if exitstatus == 5:
        session.exitstatus = 10 # Any arbitrary custom status you want to return```

**Comment by Tadaboody** [comment]
@yashtodi94 would you be willing to create a plugin with that solution?

**Comment by yashtodi94** [comment]
Sure...I'll try submitting a PR by next week

**Comment by Tadaboody** [comment]
@yashtodi94 I think implementing the plugin in a different repository and linking it here is the norm, because it isn't changing pytest directly.
There's a cookie cutter template for making one that's easy to submit to pytest-dev
https://github.com/pytest-dev/cookiecutter-pytest-plugin
If you need any help let me know!

**Comment by yashtodi94** [comment]
> @yashtodi94 I think implementing the plugin in a different repository and linking it here is the norm, because it isn't changing pytest directly.
> There's a cookie cutter template for making one that's easy to submit to pytest-dev
> https://github.com/pytest-dev/cookiecutter-pytest-plugin
> If you need any help let me know!

Yes, I discovered that after posting my previous comment. Thanks for the help :)

**Comment by yashtodi94** [comment]
@Tadaboody @RonnyPfannschmidt 

First attempt at building a plugin: https://pypi.org/project/pytest-custom-exit-code/

**Comment by sayjeyhi** [comment]
5 Years later...

**Comment by dmcnulla** [comment]
> https://pypi.org/project/pytest-custom-exit-code/

I made a variation of that. Thanks for posting it.
```
export PYTHONPATH=.:./framework:./integration_tests
export CONFIG=test

python -m integration_tests.purge_queues
pytest -c int_tests.ini --disable-pytest-warnings
ret=$?
if [ "$ret" = 1 ]; then
  python -m integration_tests.purge_queues
  pytest --last-failed --last-failed-no-failures none -c int_tests.ini --disable-pytest-warnings
else
  exit $ret
fi

```

**Comment by joelazar** [comment]
Also, here is an example of how to have a workaround for this in a `Makefile`:

```sh
.PHONY: test
test:
	sh -c 'poetry run pytest **.py || ([ $$? = 5 ] && exit 0 || exit $$?)'
```

**Comment by timvink** [comment]
Thanks @joelazar . 

I had to change it to single `$` notation, but other than that solved it!  

```bash
pytest || ([ $? = 5 ] && exit 0 || exit $?)'
```

**Comment by paigeadelethompson** [comment]
I guess this works for me, would have been nice if pytest just had an option for it though `python -c 'import subprocess, sys; (lambda p: p.returncode == 5 and sys.exit(0) or sys.exit(p.returncode) )(subprocess.run("pytest"))' && echo "ok"`

**Comment by ardunster** [comment]
I just ran into this issue today attempting to amend a commit in which all I did was remove a few `print()` calls I'd put in for debugging. The commit hook refused to actually rerun tests because nothing materially changed (I assume), even though if ran manually with the same command (`pipenv run pytset`) I get the output listing pass/skip quantities rather than an error. I didn't *want* to actually change anything else in that commit, so I ended up using `--no-verify`, but this doesn't seem like desired behavior.

**Comment by SonOfLilit** [comment]
I modified @yashtodi94 's solution a bit to only swallow the failure if I passed the `-k` argument to filter the tests, so I still get a failure if something bad happened to test collection (you may want to check different argument(s) instead).

```NO_TESTS_COLLECTED = 5
SUCCESS = 0

def pytest_sessionfinish(session, exitstatus):
    if exitstatus == NO_TESTS_COLLECTED and session.config.getoption("-k"):
        session.exitstatus = SUCCESS```

**Comment by emurze** [comment]
pytest --continue-on-collection-errors .

**Comment by Marc--Olivier** [comment]
For information, I ran into this issue today while running `pytest --cov=.` on a directory that had no test. Still, I wanted to collect the code coverage. I personally did not find satisfactory to have to handle the error code 5 or to install the `pytest-custom-exit-code` in multiple places.
Why does `pytest` return an error code when there is no test whereas `unittest` does not?

**Comment by nicoddemus** [comment]
@Marc--Olivier 

> Why does pytest return an error code when there is no test whereas unittest does not?

See #812 and #500 for the discussion that led the inclusion of this feature.
