### ISSUE TITLE
switching _pytest.code to new style classes broke the api

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#2398]
@nicoddemus  @hpk42 this one is fun

due to 
```
>>> class a:
...  pass
... 
>>> a()[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: a instance has no attribute '__getitem__'
>>> class b(object): pass
... 
>>> b()[1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'b' object does not support indexing
>>> 
```

we changed the behaviour of feature detection on `report.long_repr`

**Comment by The-Compiler** [comment]
Which class is affected by this? Here's a crazy idea: What about adding a `__getitem__` to that class which raises an `AttributeError` (or a custom error which subclasses both `AttributeError` and `TypeError`)?

**Comment by nicoddemus** [comment]
> Which class is affected by this? 

IIRC originally it was [`TerminalRepr`](https://github.com/pytest-dev/pytest/blame/master/_pytest/_code/code.py#L655) which was changed in fbc5ba08d969adafd71ecb6fce25a1cad76bb983, but since we changed all `class` declarations to subclass from `object` explicitly in #2179, this affects all classes now.

It is important to note that the purpose of #2179 was to exactly remove the subtle differences between old and new classes in Python 2 because pytest wasn't consistent regarding this with some classes subclassing `object` and others not.

> Here's a crazy idea: What about adding a __getitem__ to that class which raises an AttributeError (or a custom error which subclasses both AttributeError and TypeError)?

I agree with the "crazy" part of it. 😛 I would rather not make things worse by adding black magic just to fix this, hehehe.

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler  its next to impossible to ensure we didn't mis some random painful edge-cases, i'd prefer admitting an accidental break so people can review and fix their stuff

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler  its next to impossible to ensure we didn't mis some random painful edge-cases, i'd prefer admitting an accidental break so people can review and fix their stuff

**Comment by RonnyPfannschmidt** [comment]
@The-Compiler  its next to impossible to ensure we didn't miss some random painful edge-cases, i'd prefer admitting an accidental break so people can review and fix their stuff

**Comment by nicoddemus** [comment]
Can we close this given that #2414 has been merged?
