### ISSUE TITLE
The plugin hooks pytest_cmdline_parse and pytest_load_initial_conftests don't appear to get called

### ISSUE THREAD

**Issue by ceridwen** [pytest-dev/pytest#2616]
I have a conftest.py I've been using to try to test the available hook functions.

```python
import pytest

print('conftest.py')

def pytest_load_initial_conftests(early_config, parser, args):
    print(early_config)
    print(parser)
    print(args)

def pytest_cmdline_parse(pluginmanager, args):
    print(pluginmanager)
    print(args)

def pytest_cmdline_main(config):
    print(config)

def pytest_cmdline_preparse(config, args):
    print(config)
    print(args)
```

The values for pytest_cmdline_main and pytest_cmdline_preparse never get printed, so I think they're not being called.  When I look in the debugger, the latter hooks seem to be called by the line https://github.com/pytest-dev/pytest/blob/81ad185f0d0b2474120140246d756acc8e0530aa/_pytest/config.py#L167.  Setting a breakpoint there and looking at the plugins,

```python
Pdb) b /usr/local/lib/python3.6/site-packages/_pytest/config.py:157
Breakpoint 1 at /usr/local/lib/python3.6/site-packages/_pytest/config.py:157
(Pdb) c
> /usr/local/lib/python3.6/site-packages/_pytest/config.py(157)_prepareconfig()
-> return pluginmanager.hook.pytest_cmdline_parse(
(Pdb) for i in config.hook.pytest_cmdline_parse._nonwrappers: i.function.__module__
'_pytest.config'
```
The only hook at this point is `_pytest.config.Config.pytest_cmdline_parse`, which gets called.  Later on, the hook in my conftest.py is added, but I don't think this list of hooks is examined again after this initial call.  Having `__init__.py `in the directory or not doesn't seem to matter, the first two hooks don't get executed.  I haven't checked more complicated possible package configurations.

If this is intended behavior, it's not very transparent, and the documentation doesn't explain what's needed to get the first two hooks actually called.

```
$ pip list
asn1crypto (0.22.0)
Babel (2.3.4)
certifi (2017.4.17)
cffi (1.10.0)
chardet (3.0.4)
cryptography (1.9)
debtcollector (1.14.0)
enum34 (1.1.6)
Fabric (1.13.2)
funcsigs (1.0.2)
httplib2 (0.10.3)
idna (2.5)
ipaddress (1.0.18)
iso8601 (0.1.11)
keystoneauth1 (2.21.0)
kubernetes (2.0.0)
mercurial (4.2.1)
monotonic (1.3)
msgpack-python (0.4.8)
netaddr (0.7.19)
netifaces (0.10.6)
oauth2client (4.1.1)
oslo.i18n (3.15.3)
oslo.serialization (2.18.0)
oslo.utils (3.26.0)
paramiko (2.1.2)
pbr (3.0.1)
pexpect (4.2.1)
pip (9.0.1)
positional (1.1.1)
prettytable (0.7.2)
ptyprocess (0.5.1)
py (1.4.34)
pyasn1 (0.2.3)
pyasn1-modules (0.0.9)
pycparser (2.17)
pyparsing (2.2.0)
pytest (3.1.2)
python-dateutil (2.6.0)
python-novaclient (9.0.0)
pytz (2017.2)
PyYAML (3.12)
Reindent (0.1.1)
requests (2.17.3)
rsa (3.4.2)
setuptools (32.1.0)
simplejson (3.10.0)
six (1.10.0)
stevedore (1.23.0)
urllib3 (1.21.1)
websocket-client (0.44.0)
wheel (0.29.0)
wrapt (1.10.10)
```
```
$ pytest --version
This is pytest version 3.1.1, imported from /usr/local/lib/python3.6/site-packages/pytest.py
setuptools registered plugins:
  pytest-metadata-1.5.0 at ~/Library/Python/3.6/lib/python/site-packages/pytest_metadata/plugin.py
  pytest-html-1.15.1 at ~/Library/Python/3.6/lib/python/site-packages/pytest_html/plugin.py
  pytest-xprocess-0.12.1 at /usr/local/lib/python3.6/site-packages/pytest_xprocess.py
  pytest-cov-2.5.1 at /usr/local/lib/python3.6/site-packages/pytest_cov/plugin.py
```

This is on MacOS X 10.12.5 and Python 3.6 installed with Homebrew.

**Comment by nicoddemus** [comment]
Hi @ceridwen,

Where is `conftest.py` located? `pytest_load_initial_conftests` and `pytest_cmdline_parse` are a little special in the sense that they are only called for installed plugins or `conftest.py` files at the root of the suite, see [the note for pytest_addoption](https://docs.pytest.org/en/latest/writing_plugins.html#_pytest.hookspec.pytest_addoption), I suspect the same rules are valid for `pytest_load_initial_conftests` and `pytest_cmdline_parse`.

**Comment by ceridwen** [comment]
In this case, `conftest.py` is in the root of the suite.  This is a minimalistic set of tests I keep around for studying pytest functionality, so there's no setup.py or other complicated arrangement of packages.  If there needs to be a specific arranagement to get these two methods to work, that's not obvious to me from reading the documentation.

**Comment by j19sch** [comment]
Am having the same problem using pytest 3.3.1 and python 2.7.12.

I created a basic setup similar to @ceridwen with one directory containing `conftest.py` and two files with tests. `pytest_cmdline_preparse` works, `pytest_load_initial_conftests` and `pytest_cmdline_parse` don't seem to do anything.

**Comment by nicoddemus** [comment]
Looking at the code I see that this is how it works right now: `conftest.py` files are collected and setup to handle hooks by an implementation of the `pytest_load_initial_conftests` hook in `config.py`, so it is not possible for `conftest.py` files to implement that hook themselves. `pytest_cmdline_parse` is called way before that, which also explains why it is not being called for `conftest.py` files.

I don't see how it would be possible to make pytest call those hooks for `conftest.py` files so it's a documentation issue, those hooks (and possibly others) cannot be implemented in `conftest.py` files, only by setuptools plugins. ,

Opened #3091 to fix the docs.

Thanks guys for the report!

**Comment by jxramos** [comment]
I'm stumbling across this reality myself while trying to add the hook in a plugin and then referencing it with `-p proj_foo.my_plugin`

```
# my_plugin.py

# raise RuntimeError("Testing module is loaded")

def pytest_cmdline_parse(pluginmanager, args):
    raise RuntimeError("Not today")
```

I never get the runtime error the hook exposes. But if I uncomment out the module level exception I can see the module is indeed being loaded, therefore the hook is not being picked up.

This is some tricky stuff this notion of  *setuptools plugins*, that's a very different class of plugin that appears to unlock these special bootstrapping hooks (https://docs.pytest.org/en/stable/reference/reference.html#bootstrapping-hooks).

**Comment by RonnyPfannschmidt** [comment]
https://docs.pytest.org/en/stable/reference/reference.html#pytest.hookspec.pytest_cmdline_parse

The note mentions that the hook is only called for plugins passed in the plugins arg of the main function

**Comment by jxramos** [comment]
Oh wow, this is very eye opening. There’s a whole other plugin avenue I was unfamiliar with.


I had previously interpreted that note as pertaining to plugins passed into `pytest.main` via args with `-p projX.pluginFoo`. What you’re describing is a dedicated `plugins` parameter to the main function itself. To share the relevant code here now I see it very clearly.

https://github.com/pytest-dev/pytest/blob/d889ca0f3b8c45f92ef90f34e67ddbaa2c988134/src/_pytest/config/__init__.py#L172-L181


That is interesting. I’ll need to think about this. Going this route would imply a lot of boilerplate for me to make the connection for all of the test modules we author. Every module of ours has a `pytest.main` line in the main section so that we can make a connection for bazel execution.


I need to more deeply grasp what this statement is getting at, particularly the notion of early registered plugins.

> Bootstrapping hooks called for plugins registered early enough (internal and third-party plugins).


What’s the language and vocabulary to specify here. It seems like there are two categories of pytest plugins, early and late registering plugins. Is the following an example of a late registering plugin, which I will call *path only plugins* where you merely provide a path to the plugin to reference it (ie the `-p projFoo.subDirBar.plugin_p` or equivalently `pytest_plugins = [“projFoo.subDirBar.plugin_p”]`? 

I imagine these *installable plugins* or *setuptools plugins* are synonymous with *third party plugins*, is that correct? These would be python packages which at the least define a line like the following

```
pyproject.toml
[project.entry-points.pytest11]
```
Eg
https://github.com/pytest-dev/pytest-mock/blob/f7a0cbaa59014dc6d63d1df737a0275408f18fdb/pyproject.toml#L53

Hopefully I’m making sense here with the above.

As always @RonnyPfannschmidt thank you and the team for your dedication to the project and taking these comments and questions.
