### ISSUE TITLE
call to pytest_runtest_logreport  is not proper 

### ISSUE THREAD

**Issue by gkambalu** [pytest-dev/pytest#2647]
from `_pytest/runner.py`

```python
def call_and_report(item, when, log=True, **kwds):
    call = call_runtest_hook(item, when, **kwds) 
    hook = item.ihook
    report = hook.pytest_runtest_makereport(item=item, call=call)
    #import pdb; pdb.set_trace()
    if log:
        hook.pytest_runtest_logreport(report=report) # -----> **this logreport has been overridden in our 
                                                                                               custom plugins** 
    if check_interactive_exception(call, report):
        hook.pytest_exception_interact(node=item, call=call, report=report)
    return report
```
for every test function , "`pytest_runtest_logreport`" is called after each of the setup/call/teardwon sections are executed.
but  during the teardown of the last test  function:

```python
   def teardown_exact(self, item, nextitem):
        needed_collectors = nextitem and nextitem.listchain() or []
        self._teardown_towards(needed_collectors)
```

`nextitem` is `none` [which is expected] so  `needed_collectors = []`

In  `_teardown_towards` function  `self.stack`  never gets equl to `needed_collectors` unless all the teardown functions are called, that is function , module and session . and after which the `runtest_log_report` is  called . which is not the case if it were not the last test case.

```python
def _teardown_towards(self, needed_collectors):
        import pdb; pdb.set_trace()
        while self.stack:
            if self.stack == needed_collectors[:len(self.stack)]:
                break
            self._pop_and_teardown()
```

due to this our reporting is getting impacted as we have overridden the `pytest_runtest_logreport` , please
help here.

---

edited by @The-Compiler to add proper [code formatting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code) as this was unreadable otherwise :wink:

**Comment by nicoddemus** [comment]
Hi @gkambalu, sorry for the delay. Can you provide a minimal example which demonstrates the problem so it is easier to go through the code and analyse the issue? Thanks.

**Comment by gkambalu** [comment]
![image](https://user-images.githubusercontent.com/29251330/29283563-eff14476-8144-11e7-8377-32e07d353687.png)


I have two test casses   each has a function level fixture and  a common module and a session fixture.

after the execution of each of  function fixture setup , first test and function teardown  log_report hook gets called.

and for the second test case log_report hook is called immedialtely after the function fixture setup and second test call 
but unlike the first test case ,  log_report hook for the teardown is not called immediatetly, instead it is called after the module and session fixture teardown gets executed. 

ideally teardwon fixture for second test  should have called immedialtey after the  end of  second test execution.

atttaching the log

**Comment by RonnyPfannschmidt** [comment]
as per the current setup/teardown model of pytest

which is structurally wrong ever since @hpk42 introduced `nextitem` its "correct" to tear down everything before invoking the report

technically not tearing down everything between 2 tests is just an "optimization"

**Comment by nicoddemus** [comment]
To help me understand the issue:

```python
# test_foo.py
import pytest

@pytest.fixture(scope='module')
def module_fix():
    print('module fixture setup')
    yield
    print('module fixture teardown')


@pytest.fixture
def fix():
    print('function fixture setup')
    yield
    print('function fixture teardown')


def test_first(fix, module_fix):
    pass


def test_second(fix, module_fix):
    pass

# conftest.py
def pytest_runtest_logreport(report):
    print('pytest_runtest_logreport -> "{}" for "{}"'.format(report.when, report.nodeid))
```

Running `pytest -qs` gives:

```
function fixture setup
module fixture setup
pytest_runtest_logreport -> "setup" for "test_foo.py::test_first"
.pytest_runtest_logreport -> "call" for "test_foo.py::test_first"
function fixture teardown
pytest_runtest_logreport -> "teardown" for "test_foo.py::test_first"
function fixture setup
pytest_runtest_logreport -> "setup" for "test_foo.py::test_second"
.pytest_runtest_logreport -> "call" for "test_foo.py::test_second"
function fixture teardown
module fixture teardown
pytest_runtest_logreport -> "teardown" for "test_foo.py::test_second"
```

If I understand the issue correctly, @gkambalu expected the order of teardown calls to be the following:

```
.pytest_runtest_logreport -> "call" for "test_foo.py::test_second"
function fixture teardown
pytest_runtest_logreport -> "teardown" for "test_foo.py::test_second"
module fixture teardown
```

Is that it?

**Comment by gkambalu** [comment]
exactly , you got it right, this is how exactly i thought it should have behaved .

**Comment by nicoddemus** [comment]
@gkambalu I see, thanks for confirming. I don't think the current implementation is incorrect though,  let me explain my reasoning:

`pytest_runtest_logreport` is used to report "setup", "call" and "teardown" stages after the stage has been complete. This allows hook implementations to react to failure at any of those stages.

So the current sequence of events:

```
function fixture setup
module fixture setup
pytest_runtest_logreport -> "setup" for "test_foo.py::test_first"
...
function fixture teardown
module fixture teardown
pytest_runtest_logreport -> "teardown" for "test_foo.py::test_second"
```

"teardown" for `"test_foo.py::test_second"` is called only after all the fixtures which are part of its teardown process have also been finalized. This is important because `module fixture` might fail during "teardown", allowing it to be properly reported. 

Now if the teardown sequence was:

```
function fixture teardown
pytest_runtest_logreport -> "teardown" for "test_foo.py::test_second"
module fixture teardown
```

And `module fixture` fails during teardown, which hook would we call to inform hook implementations of that, given that the teardown stage of "test_foo.py::test_second" was already completed?

So the current implementation seems correct from my POV. I also understand your interpretation and it makes sense, but the current implementation also has logic behind it.

Having said that, I think you can obtain the behavior you want by using [`hookwrappers`](https://docs.pytest.org/en/latest/writing_plugins.html#hookwrapper-executing-around-other-hooks) instead of plain hooks? For example using a hook wrapper around [`pytest_runtest_setup`](https://docs.pytest.org/en/latest/writing_plugins.html#_pytest.hookspec.pytest_runtest_setup) you can get called before any fixture is even created:

```python
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_setup(item):
    # at this point no fixture was setup for `item` yet
    yield
```

[`pytest_fixture_setup`](https://docs.pytest.org/en/latest/writing_plugins.html#_pytest.hookspec.pytest_fixture_setup) and [`pytest_fixture_post_finalizer`](https://docs.pytest.org/en/latest/writing_plugins.html#_pytest.hookspec.pytest_fixture_post_finalizer) might also be helpful.

**Comment by nicoddemus** [comment]
Closing for now.
