### ISSUE TITLE
Add a linting flag to error on tests that contain no assertions

### ISSUE THREAD

**Issue by reaperhulk** [pytest-dev/pytest#2706]
Occasionally when writing a test I will do something like:

```python
def test_important_thing():
   # amazing test code here
   actual == expected
```

Unfortunately, because I am an idiot, I accidentally left off the `assert` on that equality and thus this test is worthless and doesn't confirm that anything actually works. This is not pytest's fault, but it would be wonderful if pytest had the ability to error/fail on tests that contain no assertions. Occasionally people do write tests that implicitly should pass if no exceptions are raised, so it would be useful if you could mark functions you don't want to fail via a decorator like `@pytest.mark.noassertion` when this flag is enabled.

**Comment by RonnyPfannschmidt** [comment]
tests without assertions are valid and useful in pytest as well - like for example acceptance tests that execute a larger piece of software

in addition its not clear how to correctly lint for no assertions, while we could implement it for rewritten code - there is heaps of code tats not rewritten and still asserts

so there is no way to do this completely

also it could break perfectly fine testsuites to just enable this at one point unconditionally

as such its a huge hassle to get this one started up and in - i believe it needs a volunteer willing to push it trough discovering the edges to make it work and the transition to make it from a opt in to a default

**Comment by The-Compiler** [comment]
FWIW [pylint](https://pylint.org/) would already catch this, telling you `Statement seems to have no effect (pointless-statement)`.

**Comment by nicoddemus** [comment]
Another point is that it is common for tests not have `assert` statements themselves but use small utility functions which do assertions, instead of just expecting that no exception is raised. 

For example:

```python
from app.common_testing import check_all_processed

def test_transactions(factory):
    transactions = factory.perform_transactions()
    check_all_processed(transactions)
```

In the example above, `check_all_processed` ensures all transactions were properly processed by using `assert` statements.

Given that there are valid cases of tests not having asserts and being valid, an opt-out mark would be more a nuisance than a chance to catch the occasional mistake. Making this feature opt-in by using a mark would defeat the purpose I believe.

@reaperhulk given that pylint can catch this kind of problem better by spotting statements which have no effect and the other reasons given by @RonnyPfannschmidt, I feel this wouldn't be a good fit for pytest right now. 

What do you guys think?

**Comment by reaperhulk** [comment]
Yeah, if pylint is capable of linting in this fashion then I'm fine with saying this is out of scope for pytest. I'll go ahead and close it 😄
