### ISSUE TITLE
provide option to really hide warnings completely

### ISSUE THREAD

**Issue by petri** [pytest-dev/pytest#2883]
The newest pytest from pypi (on OSX, Python 2.7) forces warnings on user.

Despite using -r w --disable-pytest-warnings the tests always stay yellow and say "2 warnings" because of some pytest internal deprecation warnings. I've read the docs, googled yet could not find the magical switch to kill the warning count warning (sic) and have my green results back. 

If there's some option I've missed, please advise.

FWIW, apparently in my case this is caused by:

>   'pytest_configure' hook uses deprecated __multicall__ argument
>   'pytest_runtest_call' hook uses deprecated __multicall__ argument

Even if those lines can be hidden, pytest still always shows yellow status and says "2 warnings". Why force that? They have nothing to do with the tests. It does not matter whether they are caused by a plugin.

This is really, really annoying. Please, please provide some means to just silence this completely.

**Comment by RonnyPfannschmidt** [comment]
the way to go actually back to green is to update your pytest dependencies/interal plugins to no longer use __multicall__

since you didn't post more information i cant guess how much effort is require for that on your side

**Comment by petri** [comment]
Thanks for response @RonnyPfannschmidt. Allow me to clarify: Are you implying that this is intentional and that I, as a pytest user, should go and fix pytest dependencies and plugins I may be using, in order to be able to pytest normally?

**Comment by The-Compiler** [comment]
Yes, you should upgrade your plugins, or find a replacement for plugins you're using which aren't maintained anymore. At some point, your testsuite will break because of the outdated plugins, which is what the warning warns you about.

**Comment by nicoddemus** [comment]
@petri FWIW we plan to replace the internal warnings system to use the builtin `warnings` module; when that is done, you can use the normal mechanisms of the `warnings` module to silence those internal warnings.

But as @The-Compiler mentions, you really should heed those warnings because eventually that functionality will be removed (in this case the internal `__multicall__` wrapper) and then the test suite will break hard when you update the pytest version.

If the plugins that are emitting this are being maintained, most often it is just a matter of updating the plugin or bugging the maintainer if that's not the case; it is usually trivial for plugin writers to update their code.

If unfortunately the plugin has been abandoned and is outside `pytest-dev` organization, then unfortunately someone will have to pick up maintenance of it or find some other plugin which fits the same needs.
