### ISSUE TITLE
Pytest limits the unique test suite names in different project folders.

### ISSUE THREAD

**Issue by cauveryguda** [pytest-dev/pytest#2887]
I have same file names py files in different project folders.  The issue occurred if I ever wanted to execute all the tests from all folders, the name conflicts issue happened. This is a bug or is this the pytest limitation. Is there any work around for this for if I wanted to keep the same names.  

tests
  - project1_folder
      - test1.py
      - test2.py
      - test3.py
      - test4.py
  - project2_folder
      - test1.py
      - test2.py
      - test3.py
  - project3_folder
      - test1.py
      - test2.py

Please let me know if more details are needed.  I can prefix them with projectx  if there is no other work around, but my other drawback to renaming now after long way in my tests, then I will lose history in my source control.  Please let me know any suggestions.

**Comment by RonnyPfannschmidt** [comment]
@cauveryguda the limitation is based on the python import system as is - currently pytests adds a import root to every python module folder
since pytest it detects each project folder as module root, we therefore get all project folders in sys.path and hit the limitation

if its workable or you, you can for example add a `__init__.py` in each project folder and thus have the shared folder as module root 

another alternative would be to hook a own import system hack in, so each project folder gets a virtual package as root (but that might be quite a pain to implement)

**Comment by nicoddemus** [comment]
@cauveryguda there's a full explanation in the docs: [pytest import mechanisms and sys.path/PYTHONPATH](https://docs.pytest.org/en/latest/pythonpath.html?highlight=pythonpath).

I would suggest to go with the `__init__.py` approach as it is the simplest one.

Closing this for now, but feel free to follow up with more questions.

**Comment by cauveryguda** [comment]
Thank you for the explanation. Adding __init__.py to each module.

-Cauvery.
