### ISSUE TITLE
Warnings from conftest.py should show up in warning summary

### ISSUE THREAD

**Issue by drdavella** [pytest-dev/pytest#2891]
Right now if a `conftest.py` (or a module it imports) issues a warning, it does not show up in the warnings summary. Since `conftest.py` can be used to load plugins from other packages, it would be useful to be able to issue `DeprecationWarning`s and other warnings that are actually visible when `pytest` is run.

**Comment by nicoddemus** [comment]
Definitely @drdavella, this is on our plans, please see #2452

**Comment by drdavella** [comment]
@nicoddemus, great, thanks! Just wondering, but is there any temporary workaround in the meantime?

**Comment by nicoddemus** [comment]
Hooks are the mechanism in which it is possible to extend pytest behavior, but using hooks for capturing warnings from `conftest` files seems tricky because `conftest` files will be imported before any hooks are executed.

It should be possible to implement a hookwrapper around [`pytest_collect_file`](https://docs.pytest.org/en/latest/writing_plugins.html#_pytest.hookspec.pytest_collect_file) to capture warnings emitted during import of test modules though.

If the latter is acceptable to you, let me know and I can provide some sample code.

**Comment by drdavella** [comment]
Thanks, that sounds like a good starting point. Just to be clear, we are talking about the following scenario, right?

```python
# conftest.py
# Importing this causes a DeprecationWarning
from foo import baz
```

In this case, I'd like to see a warning from `pytest`, but none currently appears.

You can even do this, and it doesn't work:
```python
# conftest.py
import warnings

warnings.warn("No one will ever see this warning!", DeprecationWarning)
```

**Comment by nicoddemus** [comment]
Exactly. The case you describe was my first point, which I don't believe is doable right now.

The second scenario describes when a test module `test_foo.py` emits a warning during import (or other module it imports emits it), then I believe it is possible to implement this in a custom plugin (`conftest.py` file).

**Comment by thisch** [comment]
related to #3251

**Comment by nicoddemus** [comment]
Just a heads up: I'm currently working on #2452, but this issue is a little trickier because when we are loading conftest files, the pytest options are not quite ready for use yet, and the `warnings` plugin needs access to some options from command-line and ini file to do its work. We will probably need some more time to fix this issue in particular, possibly after the internal refactoring to the config system lead by @RonnyPfannschmidt.

**Comment by CentralLT** [comment]
What's the status on this issue? Is it already fixed?

**Comment by The-Compiler** [comment]
@CentralLT Doesn't look like it - with the conftest.py from https://github.com/pytest-dev/pytest/issues/2891#issuecomment-341812130 above, I still don't see any warning. @nicoddemus might know more, given that 0fffa6ba2f5458a22778551db7bf64b1fbd4f5b3 (which was part of #3931) was merged.
