### ISSUE TITLE
py 1.5 release breaks pytest with pip dependency resolver

### ISSUE THREAD

**Issue by uSpike** [pytest-dev/pytest#2926]
Hi,

Since pip doesn't have a great dependency resolver (see https://github.com/pypa/pip/issues/988) it will download the latest version of the dependencies of the first package passed to it.  For example,

`pip install tox pytest`

This will install `py>=1.4.17` as depended on by `tox`, which will happily get the most recent `py` package at version 1.5.  However, we cannot run pytest now since pytest depends on `py<1.5`

I think you can make the argument that the blame doesn't fall within pytest itself, but I think there's going to be a lot of requirements.txt out there which don't list pytest first, and may run into this issue.

**Comment by nicoddemus** [comment]
Hi @uSpike,

Thanks for bringing this to attention.

Hmm, the only reason why the `<1.5` restriction was put into place was because 1.5 no longer supports py26 and py33. I guess that's a little harsh, perhaps the ideal would be to make the `<1.5` restriction valid only for `py26` and `py33` I guess. This can still cause havoc on those platforms, but I'm sure the affected users will be much fewer.

Alternatively, we might remove the restriction in `pytest` completely and let `py` declare `python_requires` instead.

**Comment by nicoddemus** [comment]
I went ahead and opened #2927 removing the restriction; as soon as we decide this is the way to go we just push the package to PyPI.

**Comment by nicoddemus** [comment]
>  let py declare python_requires instead.

Oh oh, seems it is too late now; publishing a new `py-1.5.1` with `python_requires` won't help because `1.5.0` is already out and it no longer supports py26 and py33. ☹️

**Comment by RonnyPfannschmidt** [comment]
we can pull the release from pypi if necessary

**Comment by nicoddemus** [comment]
`3.2.5` has been published with the restriction removed, thanks @uSpike again for the quick report.

**Comment by merwok** [comment]
FIW pip-compile from the https://github.com/jazzband/pip-tools project can handle this kind of situtations.
