### ISSUE TITLE
Publish GitHub release notes?

### ISSUE THREAD

**Issue by jab** [pytest-dev/pytest#2933]
Any interest in publishing release notes to https://github.com/pytest-dev/pytest/releases?

This would help users follow progress more proactively, especially if using tools such as Sibbell. Currently pages like https://sibbell.com/github/pytest-dev/pytest/3.2.5/ are blank because of the lack of release notes.

**Comment by nicoddemus** [comment]
Hi @jab, thanks for the suggestion.

I wouldn't mind at all using GitHub Releases, only that right now we have an automated system using `towncrier` to generate our CHANGELOGs. If someone wants to automate the process so that GH Releases are updated automatically, I'm all for it. 👍

**Comment by Zac-HD** [comment]
@nicoddemus (cc @blueyed @asottile) - I've been [putting something together for Hypothesis](https://github.com/HypothesisWorks/hypothesis/compare/master...Zac-HD:tidelift#diff-079523b2c7786eeb3f98bb05fa89a74f) to run Sphinx with the plain `text` builder, grab the latest changelog from the built file, and upload that to GitHub releases and Tidelift.

Feel free to copy it!  I had a quick look at `sphinx-markdown-builder` but haven't adopted it yet, though that's a pretty obvious enhancement.  Using *a* builder rather than just clipping the rst formatting is pretty important though, as the more detailed markup [tends to look pretty weird in markdown](https://tidelift.com/lifter/package/pypi/pytest/release-notes).  

If you have something that can run after release in CI (or even just as a manual script) though, updating both GH releases and Tidelift is basically painless.

**Comment by nicoddemus** [comment]
(Nice to know Hypothesis is also on Tidelift! 😁)

Thanks for sharing this. I've a brief conversation with @jaraco in https://github.com/jaraco/jaraco.tidelift/issues/1, which has started `jaraco.tidelift` with this purpose. 

I believe the hardest part of the "upload release notes" process in a general manner is *getting* the release notes, as projects use wildly different approaches to that.

Anyway the work you already done is definitely great already, and can be used as basis for a more general project, or at least something that works with `towncrier`. 👍 

This thread also gives me the idea of writing a generic "changelog uploader to Tidelift and GH release notes", based on towncrier (at least initially).

Ahh so many interesting projects to tackle, so little time. 😁

**Comment by nicoddemus** [comment]
Just to note, Tidelift now automatically scans for GitHub release notes, so just uploading the release notes to GH will also solve this for Tidelift. 👍
