### ISSUE TITLE
Duplicate test results in Jenkins when test is failing in both test and in teardown

### ISSUE THREAD

**Issue by jdesmarais-jive** [pytest-dev/pytest#2967]
It seems that the junit xml test results generated by pytest can be incorrectly misinterpreted by Jenkins if a test fails in it's **testing phase**, and in **teardown phase** at the same time.

Extraction from the xml file:
```
<testsuite errors="1" failures="1" name="pytest" skips="46" tests="47" time="12.782">
```

I would have expect that the results be consistent here: have only 1 failures but not 1 errors since the test has failed in its execution before failing in its teardown. 
If you sum up the errors, failures and skips, you have 48 tests instead of 47 test execution.

The results:

Junit plugin view for the specific xml file:
![screen shot 2017-11-28 at 15 11 10](https://user-images.githubusercontent.com/29709551/33342019-9ddd247c-d44e-11e7-82d1-43f3b5ff1166.png)

requirements.txt
```
netifaces==0.10.6
pytest==3.1.3
pytest-repeat==0.4.1
pytest-html==1.15.2
pyyaml==3.12
arrow>=0.10.0
```

Xml file generated by pytest
[results_junit_xml_file.txt](https://github.com/pytest-dev/pytest/files/1511495/results_junit_xml_file.txt)

Thanks for your project

**Comment by nicoddemus** [comment]
@jdesmarais-jive thanks for writing.

Your thinking makes sense, but pytest generates a failure report any of the test phases fails, otherwise the teardown failure for the teardown phase would not be displayed at all. It might be a little confusing at first but the alternative is not showing the teardown error at all which I believe would be worse.

If you click on the links for the failures/errors above, you will see that one of them points to the traceback for the failure during the **testing phase**, while the other points to the traceback for the **teardown phase**, which is marked as an error.

**Comment by jdesmarais-jive** [comment]
Thanks for your quick answer, it is really appreciated.

I understand completely your point but I only think it was a little confusing from an outside the code point of view since there is more failed than number of total tests.

I will close this since it seems to be as designed.
