### ISSUE TITLE
pytest 3.3: TerminalReporter.writer removed without deprecating it first

### ISSUE THREAD

**Issue by jluebbe** [pytest-dev/pytest#2984]
We have a small plugin, which uses the TerminalReporter.writer attribute to continue printing to the terminal even when normal output is captured and the CaptureFixture is used.

The writer attribute was originally added by 1fc466e8 back in 2013. It was removed by 05cfdcc8 (which intended to revert 3b30c93f), probably by mistake.

**Comment by nicoddemus** [comment]
@jluebbe thanks for reporting! Indeed `writer` was removed by accident while trying to revert 05cfdcc which rendered `_tw` read-only while preparing for 3.3 in #2945. The reason for that revert is because `pytest-instafail` plugin attempts to set `_tw` to something else. 😞 

Not sure how to proceed here to be honest. Removing `writer` was a mistake, but I'm thinking re-adding `TerminalReporter.writer` only to deprecate it in the next release will only add to the confusion further. Opinions?

@RonnyPfannschmidt @The-Compiler

**Comment by RonnyPfannschmidt** [comment]
since its a public and used api we have to bring it back and can deprecate it in the next feature release

**Comment by RonnyPfannschmidt** [comment]
man - for extra fun, practically all new code in that linked commit is broken and the plug-in itself has better methods to handle it already existing back at that time (unlike other methods of the object those in particular dont maintain the state, so in all fairness we should deprecate all of them
