### ISSUE TITLE
capsys not available for utility functions

### ISSUE THREAD

**Issue by fxdgear** [pytest-dev/pytest#2988]
I have a test framework for doing integration tests between logstash and elasticsearch. 

I've written this whole thing to use docker and pytest. 

I have a couple utility functions that setup an environment (pull images, ensure Elasticsearch is ready before running the tests etc...). 

I can specify a `-s` flag when running the tests and I get all the output. 

BUT in my setup class I call some utility functions. I want to report to the user that 

1. the images are downloading
2. waiting for Elasticsearch to be ready

I tried using `capsys` in one of my utility functions. BUT I don't know where it gets imported from. i don't know how to pass it to my function. etc... 

Is there a better way to go about handling this?

**Comment by fxdgear** [comment]
@nicoddemus thanks for the quick answer. 

So if I'm using a test class, and I have a setup defined: 

https://github.com/fxdgear/lit/blob/master/lit/test_logstash.py#L45-L54
Is the capsys passable into a `setup_class(cls)`

**Comment by nicoddemus** [comment]
xUnit style setup/teardown do not support fixtures so they remain compatible with unittest-style frameworks.

I see you are using `setup_class` which is called before the first test method of that class executes, is that what you intend? If so I'm afraid you can't use `capsys` because it is for function-scoped only tests.

I suggest to go with `contextlib.redirect_stdout` in your case to keep things simple.

**Comment by fxdgear** [comment]
@nicoddemus great. thanks for the help. I was struggling to find an answer in the docs :) 

I know that this is an edge case so i gave up and came here.

**Comment by nicoddemus** [comment]
Sure thing, glad I could help.
