### ISSUE TITLE
Customize test id on the terminal report

### ISSUE THREAD

**Issue by fontealpina** [pytest-dev/pytest#3140]
Running pytest with -v option, I am obtaining an output of this type:   
`ToolTest/test/bug_001/test.py::TestBug001::test_bug_001 <- test.py PASSED`  
I would like to customize the test id, e.g. removing `<- test.py ` to get: 
`ToolTest/test/bug_001/test.py::TestBug001::test_bug_001 PASSED`   

To do this, I tried to write a plugin with the hook:   
`def pytest_runtest_logstart(nodeid, location):`
but seems that my hook is called after the test id has already been printed on the terminal.  
So I was wondering if there is a way to do this?

Thanks

**Comment by nicoddemus** [comment]
Hi @fontealpina,

This is the code responsible for adding that `<-`:

https://github.com/pytest-dev/pytest/blob/0d96a5bf9059e51324ac24ec24d68af1c35db6d8/_pytest/terminal.py#L507-L512

So it seems the collected node and the actual path are different, which might indicate some other problem or can be fixed in some other way.

Can you provide a reproducible example?

**Comment by fontealpina** [comment]
Hi, 
actually I added a plugin to modify the root dir path:
```python
def pytest_configure(config):     
     config.rootdir = py.path.local(os.getcwd())
```  
My target would be use the cwd as rootdir instead of using the common ancestor directory. 
I tried this solution and seems to work apart the ` <- test.py` shown in the terminal. 
Maybe can I get this in a different way?  
Thanks again

**Comment by nicoddemus** [comment]
> Maybe can I get this in a different way?

Indeed, that's #1642 and #3127. 😉 

I'm closing this for now, feel free to ask any follow up questions though.
