### ISSUE TITLE
plan and implement the change of empty_parameterset values

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#3155]
followup to  #3044 

plan and implement the deprecation time line for switching the default of empty_parameterset from skip to `xfail(run=False)` over the course of the next few feature releases

**Comment by nicoddemus** [comment]
Not very nice of @pytestbot to remove labels like that... 😕

**Comment by RonnyPfannschmidt** [comment]
lets see how it fares in future - @sils can you take a look on what prompted it and how it will learn

**Comment by RonnyPfannschmidt** [comment]
closed by #3044

**Comment by sils** [comment]
@RonnyPfannschmidt I'm fairly sure this is a race condition between you and the bot, I'm assuming you added the labels after opening the issue?

The bot uses the information from the webhook and doesn't always refresh because we can only use so many API requests.

We use locks internally to not have the bot do that to itself but then humans come around ;). I'll look into how we can improve on that, I think there is a way without wasting more API requests.

**Comment by nicoddemus** [comment]
@sils you are right, @RonnyPfannschmidt updated the labels at 8:29 and the bot changed the labels at 8:30. 👍

**Comment by sils** [comment]
I opened https://gitlab.com/gitmate/open-source/IGitt/issues/104 for this, thanks for pinging me :) keep doing that, the more feedback we get, the better.
