### ISSUE TITLE
pytest shows 0% test statistics after 3.4.0 with --capture argument

### ISSUE THREAD

**Issue by skirpichev** [pytest-dev/pytest#3203]
```

$ cat test_a.py 
def test_1():
    pass
def test_2():
    pass
$ cat test_b.py 
def test_1():
    pass
def test_2():
    pass
```

Before 3.4.0 I get:
```
$ py.test --capture=no test_*
============================= test session starts ==============================
platform linux -- Python 3.5.3, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/sk/test, inifile:
plugins: cov-2.4.0
collected 4 items                                                              

test_a.py ..                                                             [ 50%]
test_b.py ..                                                             [100%]

=========================== 4 passed in 0.04 seconds ===========================
```

But since last release:
```
$ py.test --capture=no test_*
============================= test session starts ==============================
platform linux -- Python 3.5.3, pytest-3.4.0, py-1.5.2, pluggy-0.6.0
rootdir: /home/sk/test, inifile:
plugins: cov-2.4.0
collected 4 items                                                              

test_a.py ..                                                             [  0%]
test_b.py ..

=========================== 4 passed in 0.04 seconds ===========================
```

**Comment by feuillemorte** [comment]
The problem is here:

https://github.com/pytest-dev/pytest/blob/e7bcc854d975e981c090e37e747d91fc7999500e/_pytest/terminal.py#L158-L166

```
        # do not show progress if we are not capturing output (#3038)
        if self.config.getoption('capture') == 'no':
            return False
```

Why we don't need to show a progress when capture option is off? If it is right may be we need to hide percentage? because [0%] is not good point here, I think

I can fix it but I don't know what is right :)

**Comment by nicoddemus** [comment]
> Why we don't need to show a progress when capture option is off?

Because since we are not capturing output, the output of the tests can create quite a mess in the terminal and printing the progress indicator really only adds to the mess so it was decided to not print it at all (also we can't really track the correct position where to put the progress indicator because the output is not coming through the `TerminalReporter`, which tracks the number of characters written per line). The example shown here does not suffer from this because the tests do not actually print anything, but that's not easy to detect.

So we really should just find the bit of code which "slipped" that check and not print the indicator in that case. 😁 

Want to tackle this @feuillemorte?

**Comment by feuillemorte** [comment]
@nicoddemus yes, then I take it and will delete indicator in this case :) Thank you!
