### ISSUE TITLE
Print captured logs before entering pdb

### ISSUE THREAD

**Issue by brianmaissy** [pytest-dev/pytest#3204]
Extension of PR #3186 for the caplog feature.

When a test fails and we are about the enter the debugger, we first print the traceback and the captured stdout and stderr. We need to add the captured logs. This is being opened as a separate ticket because caplog was added in the features branch, so if this issue is fixed before it gets merged, target the features branch for this issue as well.

See discussion here: https://github.com/pytest-dev/pytest/pull/3186/files#r166777807

**Comment by brianmaissy** [comment]
@nicoddemus @thisch So do you think we should still print captured logs at the end when live logging is on? It seems to me that as long as we capture something we should print it. Live logging is _in addition_ to capturing, because if it's on we get the logs as they happen and also in the report if the test fails. I think the behavior before entering the debugger should parallel the failed test report.

**Comment by brianmaissy** [comment]
Also, I don't know how the branch-management workflow works here. Can I cherry-pick the relevant commits in  #3186 from `master` to this PR to features?

**Comment by brianmaissy** [comment]
How does the branch management workflow work here? I want to build the changes on top of the changes in master. Do we occasionally merge master into features? Or should I cherry-pick the commits from the other PR?

**Comment by thisch** [comment]
I have some long running tests, which output a lot of log messages when I debug them. For debugging I use live-logging and `--pdb`. This allows me to abort the tests when I spot sth suspicious in the live-logs while the test is running). 

For me it does not make sense to show the captured logs before entering pdb, since 

*1)* the captured logs are not colored. IMO the captured logs are not as readable as the colored live-logs (see #3142). 
*2)* the large number of logs generated by my tests is displayed twice (first the live-logs then the captured logs).

For the test reports it is possible to disable the printing of caught logs on failure (`--no-print-logs`). AFAIK this is not possible for the captured stdout/stderr, right (@niccodemus)? `--no-print-logs` is not taken into account in your PR #3120. 

It might make sense to only display the captured logs before entering pdb when `--no-print-logs` is not given.

WDYT?

**Comment by brianmaissy** [comment]
Sounds good, I'll modify it to take into consideration the `--no-print-logs` option

**Comment by nicoddemus** [comment]
Thanks @thisch for the explanation, indeed it makes sense to consider `--no-print-logs` to not print the logs in that case. 👍

**Comment by thisch** [comment]
BTW I would suggest to introduce a new generic @--no-captured-output@ option and deprecate the @--no-print-logs@ option. The @--no-captured-output@ option disables the printing of captured output (stdout, stderr and logs) on failure and can also be used in the "enter pdb" code in #3186 and #3210.

**Comment by nicoddemus** [comment]
@thisch I think this should go in a separate issue, would you mind opening it? Thanks!

**Comment by thisch** [comment]
Given that we've merged #3234, we can close this issue.
