### ISSUE TITLE
How to run a piece of code only one time before all tests run ?

### ISSUE THREAD

**Issue by david-fliguer-ws** [pytest-dev/pytest#3709]
Hi,

I use pytest as my testing framework.

I would like some piece of code to run only one time before the tests start to run, I would like this also to work even if I run only some of the tests (For example using the -k parameter on the command line)

Where is the recommendation to write that code ? Use fixtures or traditional JUnit style ? Can someone explain more about this topic ?

Thanks a lot !!!

David

**Comment by RonnyPfannschmidt** [comment]
hi @david-fliguer-ws ,

due to lack of a use-case I'm going to presume that an autouse session scoped fixture is sufficient
`@pytest.fixture(scope="session", autouse=True)`

there is more than just that to run code before tests, but in order to give more to the point advise we need to know what you are setting out to do instead of how you think it should be done

-- Ronny

**Comment by asottile** [comment]
@david-fliguer-ws hope the above comment helped you resolve this!  If not please comment here and we can reopen / provide more direction :)

**Comment by martinvol** [comment]
As a walk-around, code inside `__init__.py` file in your tests folder will execute before all tests.

**Comment by RonnyPfannschmidt** [comment]
It will also execute if no test runs, which may be a problem
