### ISSUE TITLE
pytest-xdist newer version 1.22.4 seems to be broken

### ISSUE THREAD

**Issue by cauvery** [pytest-dev/pytest#3724]
I am seeing below error all of a sudden, nothing changed from my last run.  Suspected if that is caused by pytest-xdist newer version 1.22.4 
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: 

pytest-xdist = 1.22.4
python 2.7 

Thank you,
Cauvery

**Comment by nicoddemus** [comment]
Hi @cauvery,

Sorry to hear about that, could you please post the full output?

**Comment by cauvery** [comment]
The issue occurred with pytest-xdist=1.22.4  and pytest=3.2.5 .
And is fixed by updating pytest to 3.4 or more.  

@nicoddemus here is the full output 
_pytest.vendored_packages.pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: (pytest 3.2.5 (/home/myworkspace/.tox/py27/lib/python2.7/site-packages), Requirement.parse('pytest>=3.4'))!


Should the new version pytest-xdist=1.22.4 be compatible with pytest=3.2.5 ?

Thank you,
Cauvery.

**Comment by nicoddemus** [comment]
Yeah `1.22.4` dropped support for `pytest<3.4`. In retrospect that was a mistake on my part, because we shouldn't change requirements in bug-fix releases.

Anyway, the underlying cause seems to be that `pip`'s dependency solver has known problems, because `1.22.4` correctly declares the `pytest>=3.5` dependency:

https://github.com/pytest-dev/pytest-xdist/blob/3776f3b74b73fedc4a74c1dc6acf893bd7fb7d67/setup.py#L3
