### ISSUE TITLE
3.7.0 Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by ironiccode** [pytest-dev/pytest#3748]
When comparing `numpy.float64` with `float` using `pytest.approx` we reach maximum recursion. It works in pytest `3.5.0` and `3.6.0` thou.
Run on Ubuntu 16.04, python 3.5.2, numpy 1.11.3

It seems that changing
```python
return all(a == self for a in actual.flat)
```
to
```python
return all(self == a for a in actual.flat)
```
in `pytest_api.py` file fixes the issue (see the bottom of traceback below).

```python
import pytest
import numpy as np
val = np.float64(1.0)
val_to_cmp = 1.0
val == pytest.approx(val_to_cmp)

RecursionError                            Traceback (most recent call last)
<ipython-input-8-b44e412779ee> in <module>()
----> 1 val == pytest.approx(val_to_cmp)

~/venvs/dl3/lib/python3.5/site-packages/_pytest/python_api.py in __eq__(self, actual)
    212         """
    213         if _is_numpy_array(actual):
--> 214             return all(a == self for a in actual.flat)
    215 
    216         # Short-circuit exact equality.

~/venvs/dl3/lib/python3.5/site-packages/_pytest/python_api.py in <genexpr>(.0)
    212         """
    213         if _is_numpy_array(actual):
--> 214             return all(a == self for a in actual.flat)
    215 
    216         # Short-circuit exact equality.

... last 2 frames repeated, from the frame below ...

~/venvs/dl3/lib/python3.5/site-packages/_pytest/python_api.py in __eq__(self, actual)
    212         """
    213         if _is_numpy_array(actual):
--> 214             return all(a == self for a in actual.flat)
    215 
    216         # Short-circuit exact equality.

RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by nicoddemus** [comment]
Thanks for the report @ironiccode.

cc @abrammer @kalekundert @tadeu

**Comment by ironiccode** [comment]
You're welcome.

I'll try to create a pull request tomorrow.

**Comment by tigarmo** [comment]
Here's another test that reproduces this issue for me: Fails with max recursion in python 2.7, passes in python 3.6 (haven't checked 3.5):

```python
def testApprox():
    from pytest import approx
    import numpy as np

    a = np.array([1, 2, 3])
    assert a == approx([1, 2, 3])
```

**Comment by abrammer** [comment]
well so much for all those tests. @tigarmo What version of numpy are you using?  I can't reproduce in 2.7.14 with numpy  1.14.2. 

I think the issue would be whether `_is_numpy_array()` is recursively returning `True`.  Though I've only looked at this code for a couple days.

**Comment by tigarmo** [comment]
Hi @abrammer, it's numpy `1.11.0`. Unfortunately our python 2 environment is a bit customized so I'll try to see if I can repro this with a more 'standard' python 2 environment.

**Comment by kalekundert** [comment]
I had the exact same thought @abrammer.  :-)  I think you're right that the problem is that _is_numpy_array() is returning true when it shouldn't.  It's also weird that switching the order of the operands would do anything.  It should end up calling ``ApproxScalar.__eq__()`` either way.

**Comment by ironiccode** [comment]
I've updated info about my `numpy` version (`1.11.3`)

**Comment by tigarmo** [comment]
Good call on the numpy version @abrammer, I confirm that for me the previous test fails with numpy `1.11` but passes with numpy `1.15`. Playing with the versions a bit here it seems that the test starts passing in numpy `1.13.0`, so here's the changelog for that if anyone is feeling adventurous: https://docs.scipy.org/doc/numpy-1.13.0/release.html

**Comment by kalekundert** [comment]
My first impression is it has something to do with:

> New ``__array_ufunc__`` attribute provides improved ability for classes to override default ufunc behavior.

``approx()`` uses ``__array_ufunc__`` to ensure that its ``__eq__`` operator is called regardless of the order of the operands (otherwise the operand on the left side takes precedence, potentially explaining why putting ``self`` on the left solves the problem).  I don't understand how the infinite recursion results, though.

**Comment by abrammer** [comment]
I think it's related to this. https://github.com/numpy/numpy/pull/9175
I'm not sure what the solution though.

**Comment by tigarmo** [comment]
@abrammer that is my reading of the issue too. My understanding is that in the numpy versions with the problem, `a == self` first calls `numpy.float64.__eq__` passing `self` which is an `ApproxScalar`. Since numpy doesn't know how to handle that it ends up calling `ApproxScalar.__eq__` but passes an array with `a` inside instead of just `a`. It must be some kind of standardization to arrays that numpy does internally. So then it makes sense that `a == self` is an infinite recursion.

As you and @ironiccode originally said, flipping the order fixes the problem because it calls `ApproxScalar.__eq__` immediatly with the `float64` parameter. If it doesn't break anything else I think that's the simplest fix.
