### ISSUE TITLE
Running all tests of a subfolder of the test folder

### ISSUE THREAD

**Issue by Toekan** [pytest-dev/pytest#4048]
Hi,

I'm using --addopts -k to run subsets of my test. When I try --addopts -k 'subfolder_1' in the example below it used to run all tests in foo_test_a.py and foo_test_b.py when using pytest 3.6. In pytest 3.8 though this behaviour seems to be gone and no tests are selected. Is this on purpose? If so, what is the correct way to achieve this behaviour in pytest 3.8?

```
- tests
|- subfolder_1
    |- foo_test_a.py
    |- foo_test_b.py
|- subfolder_2
   |- foo_test.py
```

I'm working within a virtual environment with python 2.7, the only package I changed was pytest 3.6 <-> 3.8, so it seems the changed behaviour must come from updating pytest.

Thanks!

**Comment by nicoddemus** [comment]
Hi @Toekan, thanks for the report.

I believe your example is incomplete, because `foo_test_a.py` and `foo_test_b.py` wouldn't be collected by pytest as they don't match the default `python_files` glob. 

I renamed them to `foo_a_test.py` and `foo_b_test.py` for testing.

With `3.6.0`, `--collect-only` shows:

```
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.6.0, py-1.6.0, pluggy-0.6.0
...
collected 3 items
<Module 'test-k/tests/subfolder_1/foo_a_test.py'>
  <Function 'test'>
<Module 'test-k/tests/subfolder_1/foo_b_test.py'>
  <Function 'test'>
<Module 'test-k/tests/subfolder_2/foo_test.py'>
  <Function 'test'>
```

And with the latest `master`:

```
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.8.1.dev50+g41f6ea13, py-1.6.0, pluggy-0.7.1
...
collected 3 items
<Package 'c:\\pytest\\.tmp'>
  <Module 'foo_a_test.py'>
    <Function 'test'>
  <Module 'foo_b_test.py'>
    <Function 'test'>
  <Module 'foo_test.py'>
    <Function 'test'>
```

So the introduction of `package`-scoped fixtures changed the collection tree and the test modules no longer include the directory path where they are located, which explains why `-k` no longer works in this case.

This is an unintended breakage, but I don't think it is easily fixable in pytest either.

One workaround is to turn `subfolder_1` into a package by adding a `__init__.py` file. This will change the collection tree to:

```
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.8.1.dev50+g41f6ea13, py-1.6.0, pluggy-0.7.1
...
collected 3 items
<Package 'c:\\pytest\\.tmp'>
  <Package 'c:\\pytest\\.tmp\\test-k\\tests\\subfolder_1'>
    <Module 'foo_a_test.py'>
      <Function 'test'>
    <Module 'foo_b_test.py'>
      <Function 'test'>
  <Module 'foo_test.py'>
    <Function 'test'>
```

And then `-k subfolder_1` will work:

```
λ pytest -k subfolder_1
============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-3.8.1.dev50+g41f6ea13, py-1.6.0, pluggy-0.7.1
...
collected 3 items / 1 deselected

tests\subfolder_1\foo_a_test.py .                                        [ 50%]
tests\subfolder_1\foo_b_test.py .                                        [100%]
```

**Comment by nicoddemus** [comment]
Cool, glad to help!
