### ISSUE TITLE
Why pytest recreate instance of test class on evry test method?

### ISSUE THREAD

**Issue by heckad** [pytest-dev/pytest#4515]
How to forbid pytest recreate instance of class when I use `@pytest.mark.incremental`? I want to set value in `self` but pytest recreate instance and in next method I get exception `AttributeError`.
If there is no such possibility then consider this issue as a feature issue.

**Comment by heckad** [comment]
I want test creation selection, modifiaction and deletion user in my app. In first test I create user and function return of creation user return me user id. I store this id in instanse of test class using `self.user_id=user_id` and I want to get user_id in next tests but pytest recreate instance and user_id not in new instance. I propose add copy state of instance for incremental mark.

**Comment by asottile** [comment]
I suggest using fixtures. Where are you getting an incremental mark from? I'm not familiar with that being something that pytest provides?

**Comment by heckad** [comment]
`@pytest.mark.incremental`

**Comment by RonnyPfannschmidt** [comment]
@heckad pytest itself does not interpret that mark

**Comment by asottile** [comment]
@heckad pytest allows arbitrary marks to be defined. A few have special meaning such as parametrize and xfail, others can be defined by plugins or contest.py files.

**Comment by heckad** [comment]
What the reason for recretion instance for each test?

**Comment by asottile** [comment]
consistency, both with the way that `unittest` does this and to make tests as repeatable as possible (you can run just a single test and so it is the same experience whether you run an individual test or a collection of tests from the test's point of view).  test classes really shouldn't be a container for state but just a way to organize tests, I'd suggest using fixtures (which are designed for this) instead.

**Comment by heckad** [comment]
Is it even possible to add mark wich say copy state of self? Where can I read about creating marks and their capabilities?

**Comment by heckad** [comment]
It seems to me logical that tests inside the class should be performed within some context that they themselves will change. Why is it necessary to start something else if you already have self?

**Comment by nicoddemus** [comment]
@heckad Tests should not save state from one test to another as a general rule, most users will shoot themselves in the foot if they do and probably create a messy test suite. For this reason pytest (and other test frameworks) always provide a fresh `self` for each test. "Copying self" between tests is not really something that is possible today.

We already have provided you with a possible solution (using a class fixture as @asottile suggested), another would save your state in the *class* instead of *self* (`Test.user_id=user_id`). But again, this has the potential to make your tests confusing and hard to run as they depend on specific ordering.

Can you tell where does `@pytest.mark.incremental` comes from? `pip list` might provide a clue.

**Comment by asottile** [comment]
Here's the docs on this and how I got to them.

- [google search: `site:pytest.org marks`](https://www.google.com/search?q=site%3Apytest.org+marks)
    - [marking test functions with attributes](http://doc.pytest.org/en/latest/mark.html)
    - [working with custom markers](http://doc.pytest.org/en/latest/example/markers.html)

is it possible to do what you want? probably? maybe?  is it a good idea -- no I don't think so.

**Comment by heckad** [comment]
If it not good idea why then do we need classes? And how to make a chain of tests with context var without classes?

**Comment by asottile** [comment]
you don't need classes, that's one of the main selling points of pytest is it enables and encourages you to write function-based tests instead of class-based tests.  pytest still supports class-based tests to allow you to migrate from older code bases and because sometimes using a class for grouping related tests is useful.

you can use fixtures as a way to share state as I demonstrated above -- it doesn't have to be a class fixture even, you could use `scope='module'` or `scope='session'`.  But usually sharing state between tests or requiring an ordering for tests indicates a design problem with the tests themselves (which generally should be free-standing  and side-effect free)

**Comment by gemerden** [comment]
This issue also popped up in my tests when i wanted to switch from unittest to pytest testing. It should at least be mentioned in the docs about running unittests, since some unittests won't run anymore with AttributeErrors. There are perfectly good reasons to share state between tests, like when you want to run a specific sequence of tests and keep the steps organized to easily see (auto document) when something goes wrong (e.g. when using a state machine). Ofcourse there are workarounds, but for me the choice is to do extra work or go back to unittest.

**Comment by gemerden** [comment]
a lot of extra work ... replacing every access to `self` to something else

**Comment by nicoddemus** [comment]
Hi @gemerden, 

Not sure what you mean, `unittest` also creates a new instance of each test class for every test execution:

```python
import unittest

class T(unittest.TestCase):

    def test_1(self):
        self.foo = 'foo'

    def test_2(self):
        self.assertEqual(self.foo, 'foo')

if __name__ == '__main__':
    unittest.main()
```

```
λ python .tmp\test_ut.py
.E
======================================================================
ERROR: test_2 (__main__.T)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".tmp\test_ut.py", line 9, in test_2
    self.assertEqual(self.foo, 'foo')
AttributeError: 'T' object has no attribute 'foo'

----------------------------------------------------------------------
Ran 2 tests in 0.001s
```

**Comment by gemerden** [comment]
Just double checked, you are right, i remembered wrong, too bad, sorry to bother you, will have to do the work anyway.

**Comment by nicoddemus** [comment]
I see, thanks for the follow up.

There are a few suggestions on how to share state between tests in this thread (although we don't recommend to do so), feel free to ask if anything is not clear.
