### ISSUE TITLE
Codecov interpretation

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#4533]
As of now, pytest's status is listed as "failed" because codecov says we reduced `-0.02%` coverage since the last commit:

![image](https://user-images.githubusercontent.com/1085180/49835134-6e6e4c00-fd85-11e8-928b-2511ed5ae9ff.png)

Following the link:

https://codecov.io/gh/pytest-dev/pytest/commit/22345ef722efe31f0daaef633482f846665970a7

I don't understand the diff there. We only changed the formatting, how can that reduce the coverage? Am I missing something? 🤔 

cc @blueyed

**Comment by blueyed** [comment]
@nicoddemus 
Where is the status from?  master?
I would diff the commits themselves, and if there is more/less code in general that might explain it.

**Comment by blueyed** [comment]
Hmm.. "compared to 5ec…" refers to 5ecbb02a and 22345ef7 is the merge commit.
Yeah, it should not really have dropped.
/cc @codecov

**Comment by Zac-HD** [comment]
codecov tends to be pretty noisy in it's measurements, and I've seen suggestions that it might be comparing commits to the current state of (e.g.) master instead of the actual base of the branch.

Personally, and for Hypothesis, I prefer just to have `coverage` run in CI with the `--fail-under=` option set.  The disadvantage is that this doesn't aggregate platform- or version-specific coverage; the advantage is it's rock-solid and works for merge blocking.

**Comment by blueyed** [comment]
We could/should certainly disable/trim down (i.e. configure) codecov's comments probably.

The main benefit is checking the diff/patch coverage (although it fails to then display it for pytest for some reason (likely an issue with their backend still)).

We could also consider using something like [diff-cover](https://github.com/Bachmann1234/diff-cover), or https://github.com/aconrad/pycobertura additionally/instead.
