### ISSUE TITLE
Introduce match option for xfail

### ISSUE THREAD

**Issue by codekoala** [pytest-dev/pytest#4534]
It would be useful to be able to use the `match` logic from `pytest.raises` with `pytest.mark.xfail`. My current use case involves a lot of tests that use the Amazon boto3 library, which raises a `botocore.exceptions.ClientError` for pretty much every possible error. The exception has some attribute that can help understand what the error is really about, but the exception message is usually sufficient for my purposes. Currently, I am doing something like this:

```python
def test_a_thing():
    with pytest.raises(ClientError, match="AccessDenied"):
        boto3.client("ec2").do_a_forbidden_thing()
```

This pattern is littered all throughout the tests. Not only would it be more correct to mark such a test with `xfail`, but it would help clean up the tests themselves. For example:

```python
raises_access_denied = pytest.mark.xfail(raises=ClientError, match="AccessDenied")

@raises_access_denied
def test_a_thing():
    boto3.client("ec2").do_a_forbidden_thing()

@raises_access_denied
def test_another_thing():
    boto3.client("ec2").do_another_forbidden_thing()
```

This might be kind of related to the suggestion in https://github.com/pytest-dev/pytest/issues/3362, which could support more interesting matching/checking of the

**Comment by codekoala** [comment]
That's fair enough. It certainly is documented that `xfail` should be used for unfixed bugs, so best not to muddy the waters there. It made sense in my head to use `xfail` this way until you reminded me of that.

I think it would be useful to support something like what you suggested. I just tried it out and got an error (`TypeError: 'MarkGenerator' object is not callable`) which I'm guessing you already expected. I noticed there is a plugin on PyPI called `pytest-raises` that seems to offer this behavior already, but I haven't tried it yet. Would it make sense to support `pytest.mark.raises` as a built-in option?

Thanks for the quick response!

**Comment by RonnyPfannschmidt** [comment]
@codekoala thats thinkable im also hoping to introduce generalized marks at some point so we can ge away from the muddy water of string marks and go for more strict matching

but that shouldn't stop the deeper introduction of such a mark

**Comment by asottile** [comment]
not even sure there needs to be anything from pytest's side here.  I think you can just write this decorator yourself:

```python
def raises_access_denied(func):
    @functools.wraps(func)
    def wrapped_test(*args, **kwargs):
        with pytest.raises(ClientError, match='AccessDenied'):
            return func(*args, **kwargs)
    return wrapped_test
```

**Comment by codekoala** [comment]
That's very true, but it seems like something that might be common enough to merit including in pytest proper to me. My use cases have probably biased my view on that though.

**Comment by nicoddemus** [comment]
Hi @codekoala,

While I see your point of view, we need to consider that a built-in decorator is more limited, because it will always apply to the entire function, while the context manager gives you more control to decide which block of code exactly that you expect the exception. Also I suspect other people might have additional requirements to check for (extra attributes to check in the exception for example), so this new decorator might get complex fast.

For those reasons I would say I'm -1 to add a new "raises" decorator.

**Comment by codekoala** [comment]
Sounds good! Thanks for considering it!

**Comment by nicoddemus** [comment]
Cool, thanks for your understanding.

**Comment by betapl3b** [comment]
Hi everybody.

I know the discussion on this issue has been closed for quite some time now.
However, I see that the issue title talks about the `match` option for `xfail`, but neither the author's situation nor further discussion is related to `pytest.mark.xfail` decorator itself.

As a pytest user, I can think of a case where the match keyword argument would be really useful. 

Imagine that you are writing a complex e2e test that involves testing some feature with an unfixed bug.
Your test has several assertions that must pass. However, one of the assertions depends on this broken feature.
Therefore, you expect only one of the assertions to fail. You decide to use a non-strict `xfail` for this (because it is unfixed bug and when the bug is finally fixed, you don't want your test to fail). You specify that the test should be xfailed in case of AssertionError, but you can't specify what error message you expect. So essentially, `xfail(raises=AssertionError) will mute the entire test.

```python
import pytest
@pytest.mark.xfail(reason="Feature 2 has bug", match="Other") 
# Or @pytest.mark.xfail(reason="Feature 2 has bug", raises=AssertionError, match="Other") 
def test_match():
    # Assertion 1
    assert True, "Some error"
    # Assertion 2 
    assert False, "Other error"
```

This test will be "xfailed" only if it fails on "Assertion 2". If the test fails on "Assertion 1", it will be "failed" and get some attention.

By the way, code for this improvement is pretty simple and all tests are passing so far.
You can check the [commit in my fork](https://github.com/pytest-dev/pytest/compare/main...betapl3b:pytest:xfail-match)

Please let me know what you think about this use case.

**Comment by RonnyPfannschmidt** [comment]
Xfail is the wrong api for that and composes incorrectly

This should be a subtest and/or a context manager to control for scope

**Comment by betapl3b** [comment]
Hi, @RonnyPfannschmidt. Thank you for your quick reply. 

Could you please explain the difference between my case and the correct way to use xfail? According to the documentation, xfail is used for bugs that are not yet fixed or features that are not yet implemented. There is no further clarification on this. IMO my case seems to be correct from this point of view.

Since we can specify the exception type (or types), why can't we also specify the exception message?
