### ISSUE TITLE
deprecate marker based hook metadata

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#4562]
followup to  #891

while implementing i noticed we support attribute/mark based hook metadata just in pytest,
we should deprecate that custom parsing and rely entirely on pluggy markers

**Comment by blueyed** [comment]
Just for reference: instead of `@pytest.mark.hookwrapper` `@pytest.hookimpl(hookwrapper=True)` should be used.
Related code: https://github.com/pytest-dev/pytest/blob/19035f4b552c3164d4d7a10fbc6113b47232a99d/src/_pytest/config/__init__.py#L259-L287
(I've just came along about a plugin using `@pytest.mark.hookwrapper` and looked it up)

**Comment by bluetech** [comment]
I added this to the 6.1 milestone: hopefully we can start emitting deprecation warnings in 6.x. However the `@pytest.mark.{tryfirst,trylast,hookwrapper,optionalhook}` hooks are *very* commonly used in external plugins so not sure when it would make sense to completely remove.

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus while investigating i noted, that it seems like we dont have a good way to issue/record warnings with specific locations at that point in time,

this seems hard to correctly fix at first glance, so i will defer it until i can spend some more time with the issue at hand
