### ISSUE TITLE
Advice request: monkeypatch vs mock.patch

### ISSUE THREAD

**Issue by dimaqq** [pytest-dev/pytest#4576]
I'm working on a codebase where tests use a mixture of `mock.patch` and pytest's `monkeypatch`, seemingly based on authors' personal preferences.

The official docs for the latter, https://docs.pytest.org/en/latest/monkeypatch.html, refer to a blog post that's nearing its 10th anniversary; meanwhile the earlier made it into Python proper.

I wonder if there's official advice, like "use X", or perhaps "if you need feature Y, use Z" to choose between the two.

**Comment by RonnyPfannschmidt** [comment]
personally, i despise mock, needing to use it implies a structural error, so i certainly want to keep monkey-patch for when doing controlled changes of 3rd parties not under my control, but for own code - the moment a mock becomes necessary its a indicator that a re-factoring is needed

**Comment by tuukkamustonen** [comment]
I understand this is complicated topic, and that this ticket is not really a place to discuss the architectural patterns, and that I'm quite late with this reply, but could @RonnyPfannschmidt summarize what you mean by _"needing to use it [mock] implies a structural error"_? Or could you link to an article that describes the ideology that you phrase here?

**Comment by bluetech** [comment]
I'm not @RonnyPfannschmidt but here is my opinion on why `mock.patch`/`monkeypatch` is *usually* better avoided.

Monkeypatching, by definition, breaks the abstraction barrier. Some code reaches into some other code and changes it bowls. The code calls `some_function()`, but what actually runs is `patched_in_function()`. The trouble with relying on internal details is that it is brittle. If the code is refactored to call `some_other_function()` instead, the test breaks, even if the behavior is exactly the same.

A better alternative is to "formalize" the relationship between the test and the code. The conventional way to do it is give the test explicit control over the particular thing it wants to patch, usually using dependency injection.

For an example I'll use the [post](https://engineeringblog.yelp.com/2015/02/assert_called_once-threat-or-menace.html) linked by @asottile. In it, they have this code

```py
def restart_server(server):
    ...

def restart_servers_in_datacenter(servers, datacenter):
    for server in servers:
        if server.endswith("-%s" % datacenter):
            restart_server(server)
```

and they want to write a test for `restart_servers_in_datacenter`, but without it actually going to restart actual servers. What they did was to patch the `restart_server` function, and they explain some problems they ran into and how they fixed them.

The alternative to patching is do something like this:

```py
class ServerManager:
    # Takes some dependencies itself (for example).
    def __init__(self, http_client: HttpClient, auth_token: str) -> None:
        self.http_client = http_client
        self.auth_token = auth_token

     def restart_server(self, server: Server) -> None:
          self.http_client.post("restart server", auth_token=self.auth_token, {server: server.id})

def restart_servers_in_datacenter(server_manager: ServerManager, servers, datacenter):
    for server in servers:
        if server.endswith("-%s" % datacenter):
            server_manager.restart_server(server)
```

Now the test doesn't need to patch. It can do this:

```py
fake_server_manager = mock.create_autospec(ServerManager)
restart_servers(fake_server_manager, servers, datacenter)
assert len(fake_server_manager.restart_server.calls) == 1
```

Now the test *cannot* make mistakes, it most provide its own implementation of the dependency. It is not possible for the real code to run accidentally. And there is no abstraction being broken, no peace is disturbed, just regular argument passing.

You can decide to fake at a deeper level, if you want to increase the coverage:

```py
fake_http_client = mock.create_autospec(HttpClient)
server_manager = ServerManager(fake_http_client, 'fake token')
restart_servers(server_manager, servers, datacenter)
assert len(fake_server_manager.restart_server.calls) == 1
```

Sometimes it's beneficial to go "full Java" and do this:

```py
class ServerManager(meta=ABCMeta):
      @abstractmethod
     def restart_server(self, server: Server) -> None: pass

# As before.
class RealServerManager(ServerManager): ...

# Tests can use this.
class FakeServerManager(ServerManager):
     def __init__(self) -> None:
          self.restarted_servers = {}  # type: Set[Server]

     def restart_server(self, server: Server) -> None:
          self.restarted_servers.add(server)
```

depending on the case.

This intersects with general OO good practices for testable code, see [here](http://misko.hevery.com/2008/07/30/top-10-things-which-make-your-code-hard-to-test/) for example. This style of programming is also *enforced* in the [object-capability security model](https://en.wikipedia.org/wiki/Object-capability_model), which I (personally) hope will gain more prominence in the future.

As a disclaimer, I should say that sometimes monkeypatching in tests is necessary, for example when dealing with external code you have no control over. And sometimes it is just easiest and putting more effort is not worth it. And sometimes you *intentionally* want to test some internal detail.  I don't mean to be dogmatic.

**Comment by tuukkamustonen** [comment]
@bluetech Thanks for explaining that (and sorry for late response as I'm travelling). It's a good writeup, I agree with that. However:

The distinction you make in your post is _monkeypatching vs dependency injection / inversion of control_ (whatever we want to call it). My question, however, was (what I thought RonnyPfannschmidt was referring to) about _mocking vs not mocking_ (using mock objects, not `mock.patch` or `monkeypatch`). Ronny wrote:

> personally, i despise mock, needing to use it implies a structural error, so i certainly want to keep monkey-patch -- the moment a mock becomes necessary its a indicator that a re-factoring is needed

Maybe I'm interpreting this wrong, but to me it seems that he says "mock objects are bad" but "monkeypatching is good"?

**Comment by RonnyPfannschmidt** [comment]
i consider both practices bad for different reasons,
i consider monkeypatches as acceptable practice for systems where certain hook point are not given (like a 3rd party library not  intended to be set up for partial tests)

i consider mock objects bad because they encode expectations that may eventually differ with real systems, and generally try to have in memory or limited interface implementations instead of mocks when possible

however even if there is a systematic weakness to both approaches, they still win over playing architecture astronaut

so there is a number of situations where the use of those approach beats making them structurally possible for YAGNI or no controll of the upstream anyway

**Comment by dimaqq** [comment]
Since I've started this discussion, allow me to share what I've learned from experience over the past year a bit.

(The examples below are real use cases from the codebase, stripped of project specifics and simplified for clarity. Pundits may offer better solutions for each case, but I'll stand by my examples, they are the work of several smart individuals, constrained by requirements of a particular problem domain, and lived through many PRs)

**Mocking** is a valuable technique, especially for **unit** tests, that is focused on only **one aspect** of code under test, for example:

```py
def test_reject_ancient():
    with mock.patch("time.time", return_value=42):
        old_request = sign_request(data)
    with pytest.raises(TooOld):
        verify_request(old_request)
```

Here, something specific is patched just to set up some tiny detail. I don't care about the exact value of time, as long as it's way long ago. The "cost" of the tight coupling in the test is justified by keeping the implementation simple.

Which can be extended to something a bit more complex (may or may not be the best choice):

```py
@asynctest.mock.patch("mymodule.backend.SomeSideEffect", autospec=True)
async def test_simple_login(_, ephemeral_server, test_user):
    async with aiohttp.ClientSession() as session:
        async with session.get(ephemeral_server.url) as resp:
            assert resp.status == 200
```

Here, a simple test is done over 2 fixtures and 1 other thing is **mocked away**, because it's outside of test scope.

As test complexity and purpose gets closer to **functional** (or integration) testing, **fixtures** rule, and some fixtures are likely to ** monkey-patch**, for example:

```
@pytest.fixture
def config():
    monkeypatch("some.config", TEST_DEFAULTS)

@pytest.fixture
async def server(config):
    async with start_a_server() as s:  # uses global config
        yield s

...

async def test_login(server, client, user, parser, logger):
    resp = await client.post(server, user)
    assert parser.parse(resp.text) == "yes, it worked"
    assert logger.recorded({"result": "success", "username": user.name})
```

Here, fixtures and fixture dependencies are used extensively to control the "life cycle" of the monkey patches. The fixtures are essentially **fake objects** and perhaps, more generally, **test doubles** and their implementation relies on **mokeypatch** to insert (and later remove) the double into the codebase.

Note that nowhere here I've seemingly concerned myself with theoretical difference between mocking and monkeypatching. I'm being practical and use whatever works best (🎉`pytest`🎉) balancing complexity of code/fixture/test.

**Comment by bluetech** [comment]
@tuukkamustonen 

> Maybe I'm interpreting this wrong

Yes, I misread what @RonnyPfannschmidt said. FWIW I think about the opposite -- I try to avoid patching, but I'm perfectly OK with `mock.create_autospec()` mocks as a shortcut for unittests.

@dimaqq 

If I apply my suggestion to your examples, then I would avoid `mock.patch` in these cases.

Instead of

```py
    with mock.patch("time.time", return_value=42):
        old_request = sign_request(data)
```

I would have `sign_request` accept a `asof_time: float` parameter, and use that. Real code can pass `time.time()`, test can pass a hardcoded value -- no patch needed!

For `test_simple_login`, I guess it is more of an integration test (running against a real server)? For these cases I try to setup a "test environment" (usually configured through some settings object given in initialization), and for this environment I provide fake/mock implementation of "side effect"-y services. Each dependency (sometimes called "service") requires an implementation. Patching can be fine, but it's very fragile. If `mymodule.backend.SomeSideEffect` changes its name in any way, suddenly the tests start to perform this side effect (hopefully it doesn't launch nuclear missiles :rocket: :smiley: ).

For `monkeypatch("some.config", TEST_DEFAULTS)`, I would have `start_a_server()` take the config, instead of having it use a hardcoded import path. This would avoid the need to patch here as well. Usually web frameworks have some `App` or `Application` entry point which allows this.

**Comment by The-Compiler** [comment]
I also want to point out that sometimes (especially for common libraries or usecases), there are third-party patching solutions which avoid having to deal with mocks by hand. I think they can make a lot of sense when dealing with things which are inherently "in the way" (like external HTTP services). In those cases, changing the code to pass in e.g. fake responses might mean those responses aren't the same as they would be in reality, and the "over-generalization" might lead to much more complex code.

Some examples I'm aware of:

- [responses](https://github.com/getsentry/responses) for requests
- [VCR.py](https://vcrpy.readthedocs.io/en/latest/) for various HTTP libraries
- [freezegun](https://github.com/spulec/freezegun) for date/time

**Comment by MartinThoma** [comment]
I was just about to ask the same question: **In Python 3.6+, does pytest.monkeypatch provide any value over unittest.mock.patch?** A small concrete example would be pretty awesome :slightly_smiling_face: 

I have seen the [Monkeypatching/mocking modules and environments](https://docs.pytest.org/en/stable/monkeypatch.html) article (and the [linked article](https://holgerkrekel.net/2009/03/03/monkeypatching-in-unit-tests-done-right/)) and was wondering if this is only interesting for applictions which have to handle Python versions before Python 3.3 where [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html) with the [`patch` decorator](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch) was introduced.

It would be awesome if you could help me here. If it's desired, I can make a DOC-PR to add the outcome.

I didn't completely read this issue as most of the discussions seemed to be about "is mocking a sign for bad code". However, I was confused in the beginning by @asottile stating `MagicMock` is a con of `patch`. I might just not know something, but can't you use the `new` parameter of patch to use whatever you want instead of a MagicMock?

**Comment by The-Compiler** [comment]
@MartinThoma It boils down to "it's just much more simple to use, with less magic involved" in my eyes. You get a pytest fixture (rather than a decorator), and it's essentially just `monkeypatch.setattr(thing, 'attribute', value)`, rather than having a quite awkward signature which does a lot of things at once and is hard to explain.

**Comment by asottile** [comment]
I believe there's no official recommendation because it's really about opinions and trade offs -- for instance I will never use `monkeypatch` because I've been burned by it's unknown scope duration (sometimes leaking to places I don't expect) whereas the context manager form of `unittest.mock` is explicit on what it affects.  my con above about `MagicMock` is it's all too easy to leak those into apis that _should_ `TypeError` / `AttributeError` but magically succeed (specs can help with this for the most part though).  The design of `MagicMock`'s assertions is also problematic (a typo'd assert_whatever can lead to a test silently succeeding!)

**Comment by MartinThoma** [comment]
Cool, thank you @The-Compiler and @asottile !  (I miss "thank you" as a Github reaction :-) )

As people might stumble over this via Google searches: I can recommend [Demystifying the Patch Function](https://youtu.be/ww1UsGZV8fQ?t=1062) (Lisa Roach, Pycon 2018) if you just get started with patching / MagicMock + spec / autospec / spec_set. She explains this really well.

**Comment by keu** [comment]
As of 2022 `pytest-mock` covers 100% of cases for me and is much clear to use than `mock` and definitely than `monkeypatch`

**Comment by nicoddemus** [comment]
Thanks everyone for the great discussion, but I think we can close this as there's no actionable item. 👍
