### ISSUE TITLE
getfixturevalue does not support parametrized fixtures

### ISSUE THREAD

**Issue by dmtucker** [pytest-dev/pytest#4666]
I was hoping the following test would run 6 times...

`test_example.py`:
``` python
import pytest


@pytest.fixture(params=['a', 'b', 'c'])
def letters(request):
    return request.param


@pytest.fixture(params=[1, 2, 3])
def numbers(request):
    return request.param


@pytest.mark.parametrize('fixture', ['letters', 'numbers'])
def test_matrix(request, fixture):
    assert request.getfixturevalue(fixture) in ['a', 'b', 'c', 1, 2, 3]
```
Pytest https://github.com/pytest-dev/pytest/commit/ba452dbcf01f16f1bdad1950c91977298588712d:
```
================ test session starts ================
platform linux -- Python 3.7.1, pytest-4.1.2.dev29+gba452dbc, py-1.7.0, pluggy-0.8.1
rootdir: /ifs/home/dtucker/Projects/pytest, inifile: tox.ini
collected 2 items

test_example.py FF                            [100%]

===================== FAILURES ======================
_______________ test_matrix[letters] ________________
The requested fixture has no parameter defined for test:
    test_example.py::test_matrix[letters]

Requested fixture 'letters' defined in:
test_example.py:5

Requested here:
test_example.py:16
_______________ test_matrix[numbers] ________________
The requested fixture has no parameter defined for test:
    test_example.py::test_matrix[numbers]

Requested fixture 'numbers' defined in:
test_example.py:10

Requested here:
test_example.py:16
============== short test summary info ==============
FAIL test_example.py::test_matrix[letters]
FAIL test_example.py::test_matrix[numbers]
============= 2 failed in 0.39 seconds ==============
```
`pip list`:
```
Package        Version               Location
-------------- --------------------- -------------------------------------
atomicwrites   1.2.1
attrs          18.2.0
more-itertools 5.0.0
pip            18.1
pluggy         0.8.1
py             1.7.0
pytest         4.1.2.dev29+gba452dbc /ifs/home/dtucker/Projects/pytest/src
setuptools     40.6.3
six            1.12.0
wheel          0.32.3
```
`lsb_release -d`:
```
Description:    CentOS Linux release 7.6.1810 (Core)
```

**Comment by RonnyPfannschmidt** [comment]
Thats intentional

**Comment by nicoddemus** [comment]
Please take a look at https://pypi.org/project/pytest-lazy-fixture, it supports your use case. 👍

**Comment by dmtucker** [comment]
Aha! Great, thanks 😊

**Comment by jxramos** [comment]
@RonnyPfannschmidt can you expound upon the "intentionality" you reference in your comment above. What's going on with that intentionality reflected in the design of pytest and what the implications are. Is it to prevent some kind of infinite recursion, or what's going on exactly, what's the motivation for it, what is it preventing or guiding etc.

Looking at the codebase for the source of that message takes us here
https://github.com/pytest-dev/pytest/blob/54623f0f33c367e19c4041d30f11f71787e30719/src/_pytest/fixtures.py#L622-L630

I'm curious where the `ValueError` comes down from precisely, I'm thinking it's the `relative_to` piece
`source_path.relative_to(funcitem.config.rootpath) `
https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.relative_to

When we raise "*The requested fixture has no parameter defined for test*" is that message used to indicate that the fixture is never statically joined to any test case anywhere in the session either directly or transitively through fixture dependencies? It's just sort of present but floating since there's no autouse, and it has no hardcoded static connection to any actual test case?

**Comment by RonnyPfannschmidt** [comment]
Getfixturevalue has no idea what parameter to pick if a fixture wasn't considered at collection time

As long as that's the case, The only valid choice is to fail

**Comment by jxramos** [comment]
Very good. Let me explore a related twist on this subject, so let's say I pull in a bunch of fixtures from a plugin, and none of those fixtures intersect with/get referenced by/used by an actual test case. Is it the case that a `FixtureDef` would never get created for those unused fixtures showing up from the plugin? So the pytest manager only populates fixture definitions with fixtures that actually get used by test cases or are built in fixtures? Is that what we meant by *considered at collection time*, considering means a fixture is called upon somewhere, either by a test case or by another fixture that ties to a fixture which is actually used and connects to a test case. Is that accurate?

https://github.com/pytest-dev/pytest/blob/54623f0f33c367e19c4041d30f11f71787e30719/src/_pytest/fixtures.py#L963-L968

**Comment by RonnyPfannschmidt** [comment]
Fixture defs get created at plugin loading/collection time, so that existing fixtures are known

In the generated tests phase of collection the statically discoverable fixture closure of each test function is walked for parameterized fixture to generate the tests for the parameters

**Comment by BillyTheHack** [comment]
For people looking for a solution six years later, @nicoddemus suggestion (pytest-lazy-fixture, without an s) is now deprecated and abandoned.
[pytest-lazy-fixtures](https://pypi.org/project/pytest-lazy-fixtures/) is currently working and being actively maintained as a replacement.
