### ISSUE TITLE
Report duration per fixture

### ISSUE THREAD

**Issue by aparamon** [pytest-dev/pytest#4811]
Currently, [--durations](https://docs.pytest.org/en/latest/usage.html#profiling-test-execution-duration) reports setup, call, and teardown times.
Might it be possible to implement optional per-fixture timing reports, instead of gross setup and teardown values?

**Comment by nicoddemus** [comment]
Hi @aparamon,

It should be possible by writing a `hookwrapper` around `pytest_fixture_setup`, caching the results somewhere and displaying them in `pytest_terminal_summary`. It may be in a separate plugin or in the core, but I'm not sure it should be in the core as a immediate option because I'm not sure it would see too much use. What do you think?

**Comment by aparamon** [comment]
@nicoddemus Plugin way is fine, at least to get started. Thank you for the implementation pointers!

**Comment by nicoddemus** [comment]
Here's a quick `conftest.py` file which seems to do the trick:

```python
from collections import defaultdict

import pytest
import time


_elapsed = defaultdict(lambda: 0.0)


@pytest.hookimpl(hookwrapper=True, tryfirst=True)
def pytest_fixture_setup(fixturedef):
    start = time.perf_counter()
    yield
    elapsed = time.perf_counter() - start
    _elapsed[fixturedef.argname] += elapsed


def pytest_terminal_summary(terminalreporter):
    terminalreporter.section(f'fixture durations {len(_elapsed)}')
    for name, elapsed in sorted(_elapsed.items()):
        terminalreporter.line(f'{name}  {elapsed:.2f}')
```

**Comment by nicoddemus** [comment]
Closing for now, feel free to follow up with further questions.
