### ISSUE TITLE
Pytest --collect-only -q is not deterministic on Python 3.5

### ISSUE THREAD

**Issue by thomasjpfan** [pytest-dev/pytest#4838]
`pytest --doctest-modules --collect-only -q order.py` outputs a different order, where `order.py` is defined:

```python
# order.py

def a():
    """
    Examples
    ---------
    >>> X = 2
    """
    pass


class A:
    path = staticmethod(a)

    def hello():
        """
        Examples
        ---------
        >>> X = 2
        """
        pass


class B:
    path = staticmethod(a)

    def hello():
        """
        Examples
        ---------
        >>> X = 2
        """
        pass
```

`pip list`:
```bash
Package        Version  
-------------- ---------
atomicwrites   1.3.0    
attrs          18.2.0   
certifi        2018.8.24
more-itertools 4.3.0    
pathlib2       2.3.2    
pip            10.0.1   
pluggy         0.7.1    
py             1.6.0    
pytest         3.8.1    
setuptools     40.2.0   
six            1.11.0   
wheel          0.31.1  
```

On osx and linux.

**Comment by nicoddemus** [comment]
Hi @thomasjpfan,

You example is missing `--doctest-modules`, took the liberty of updating it.

Indeed I see different collections in separate runs:

```
λ pytest --doctest-modules --collect-only -q .tmp\order.py
order.py::order.A.hello
order.py::order.A.path
order.py::order.B.hello

λ pytest --doctest-modules --collect-only -q .tmp\order.py
order.py::order.A.hello
order.py::order.A.path
order.py::order.B.hello

λ pytest --doctest-modules --collect-only -q .tmp\order.py
order.py::order.A.hello
order.py::order.B.hello
order.py::order.a
```

While on Python 3.6 I always see `A.hello`, `B.hello` and `a`.

**Comment by nicoddemus** [comment]
I suspect the problem lies here:

https://github.com/pytest-dev/pytest/blob/master/src/_pytest/doctest.py#L426

I think `finder.find` returns the items in random order or something like that.

**Comment by thomasjpfan** [comment]
Thank you for adding `--doctest-modules` and the debugging information.

**Comment by thomasjpfan** [comment]
This may be a doctest bug. Running this in the same folder as my `order.py`:

```python
import doctest
import order

finder = doctest.DocTestFinder()
print(finder.find(order, 'order'))
```

Results in different items being found.

**Comment by treszkai** [comment]
I confirm, the issue is definitely in `doctest`. I boiled down the issue to doctest.py:980 (in CPython 3.5.6), where the module’s dictionary is iterated in `DocTestFinder._find()`:

```python
    # Look for tests in a module's contained objects.
    if inspect.ismodule(obj) and self._recurse:
        for valname, val in obj.__dict__.items():
```

(This `obj` is the same object as that we passed to `finder.find()`.)

In CPython 3.6 the dictionary order _happens to be_ the insertion order; in Python 3.7 it is [_guaranteed_](https://docs.python.org/3.7/library/stdtypes.html#dict-views). In 3.5.6, the following command does not have a consistent result:

```bash
python -c "import order; print([x for x in order.__dict__ if x in 'aAB'])"
```

Python 3.5 [accepts only security fixes](https://devguide.python.org/#branchstatus), and next release is expected [in September](https://www.python.org/dev/peps/pep-0478/). I see no clean solution to this in `pytest`.

**Comment by nicoddemus** [comment]
Thanks @treszkai,

So I agree there's nothing pytest can do here, so let's close this as "won't fix". 😕

**Comment by thomasjpfan** [comment]
@treszkai Thank you your help on this issue!
