### ISSUE TITLE
Order differences in IDs and parameters with multiple @parametrize decorators

### ISSUE THREAD

**Issue by torfsen** [pytest-dev/pytest#4853]
Thanks for your work on pytest, it's amazing!

I'm using the `@pytest.mark.parametrize` decorator multiple times on the same test function to run the test over the cartesian product of the parameter values. This works fine, but I've noticed that the order of the parameters in the generated test ID is different from their order in the test function definition:

```
import pytest

@pytest.mark.parametrize('foo', (1, 2))
@pytest.mark.parametrize('bar', (3, 4))
def test(foo, bar):
    assert foo < bar
```

```
$ pytest --collect-only test_pytest.py 
[...]
  <Function test[3-1]>
  <Function test[3-2]>
  <Function test[4-1]>
  <Function test[4-2]>
[...]
```

Note how the order is `foo, bar` in the test function, but in the ID the value of `bar` is listed before that of `foo`. IMO this is confusing, especially when using more parameters and/or more `@parametrize` decorators. The order in the function definition is the one I would have expected for the ID, too.

My system:
```
$ pip list
Package        Version
-------------- -------
atomicwrites   1.3.0  
attrs          18.2.0 
more-itertools 6.0.0  
pathlib2       2.3.3  
pip            19.0.3 
pluggy         0.9.0  
py             1.8.0  
pytest         4.3.0  
setuptools     40.8.0 
six            1.12.0 
wheel          0.33.1 

$ uname -a
Linux leibniz 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ python --version
Python 3.5.2
```
(I get the same results using Python 2.7.12)

**Comment by nicoddemus** [comment]
Hi @torfsen,

Thanks for writing. 

Actually what determines the order of the parameters is the order in which the markers are applied, and not the order of the function arguments: if you switch the order of the parameters in the function definition, you will see that the function ids stay the same. If you switch the order of the marks, you will get the parametrization you expect:

```python
import pytest

@pytest.mark.parametrize('bar', ('bar3', 'bar4'))
@pytest.mark.parametrize('foo', ('foo1', 'foo2'))
def test(foo, bar):
    pass
```

You will get:

```
test-foo.py::test[foo1-bar3]
test-foo.py::test[foo1-bar4]
test-foo.py::test[foo2-bar3]
test-foo.py::test[foo2-bar4]
```

And this makes sense because of how decorators work in Python: the inner most decorator is applied first.

TBH I think the current behavior is correct, although I can certainly see why you thought otherwise. 👍

**Comment by torfsen** [comment]
Thanks for the clarification!
