### ISSUE TITLE
Modular use of fixtures

### ISSUE THREAD

**Issue by 013ymc** [pytest-dev/pytest#5112]
Hi,
Suppose that I have a group of tests which are logical connected - so I grouped them into a class, I also wrote a generic fixture that accept parameters for initializing the resource.
1. I want to use this resource in multiple classes, so each class must provide it's own parameters for it, How do I do that ?
2. I also need to be initialize another resource per class that accept part of the parameters that were given to the first resource, where do I store these parameters? (The second resource refers to a method scoped fixture).

Last thing: If you have links/tutorials/examples on how to use fixtures in a generic/modular matter with classes, I'll be grateful.

Thank you !

**Comment by SalmonMode** [comment]
Fixtures can depend on other fixtures, and if a fixture is defined in a higher scope, it can be overridden in a lower scope while only affecting that lower scope.

For example, if you have fixture `a` defined in the `conftest.py` in the root of your tests package, that will be the default definition of fixture `a` for all tests and other fixtures in that entire tests package. But if you define another fixture `a` in a module in that tests package, that will be the version of fixture `a` that is used for all tests in that module. Similarly, if you defined that 2nd version of fixture `a` inside a _class_ inside that module, rather than just defining it in the global scope of the module, it would only apply for that class. 

Basically, you can override fixtures for smaller scopes, and they can't bubble outside of the scope they're defined in. Even if you define a fixture with a scope of `session`, but you define it inside a class, it will only be able to apply to things inside that class.

Here's a very simple example:

```python
@pytest.fixture(scope="class")
def a():
    return 4

@pytest.fixture(scope="class")
def b(a):
    return a

class TestA:
    def test_b(self, b):
        assert b == 4

class TestB:
    @pytest.fixture(scope="class")
    def a(self):
        return 3
    def test_b(self, b):
        assert b == 3
```

This also goes for subpackages in that test package. You can think of a `conftest.py` as something similar to the `__init__.py`, and each package within a package can have its own `conftest.py` that has the opportunity to define fixtures that override fixtures from a `conftest.py` that was higher up.

Keep in mind, that while overriding a fixture, you can still access the original one if you need to. But you're only able to do it in the fixture that overrides it. For example:

```python
@pytest.fixture(scope="class")
def a():
    return 4

class TestA:
    @pytest.fixture(scope="class")
    def a(self, a):
        return a * 2
    def test_a(self, a):
        assert a == 8
```

As for referencing things that were made earlier up the chain, pytest caches the result, and you can request a fixture more than once. The only thing to keep in mind is that "scope" is basically a limit that says "I can only run once per <scope>". Follow the single responsibility principle and limit fixtures to doing and/or providing a single thing, and they get easier to manage/maintain.

Other than that, here's a write up I made a little while ago that has some tips I've compiled:

https://salmonmode.github.io/building-good-tests/

#shamelessplug
