### ISSUE TITLE
[HELP] Is it possible to parametrize test using fixture's return value ?

### ISSUE THREAD

**Issue by megachweng** [pytest-dev/pytest#5137]
Scenario: I keep a list in a fixture and want to parametrize test by this fixture's return value
```python3
# conftest.py
@pytest.fixture(scope='function')
def platform():
    return ['Event', 'Course']

# test_main.py
def test_platform(platform_enum):
    for p in platform:
        # ...do some stuff
        assert result == p
```
Only one test is generated If I test in a for loop.  I tried to solve by using parametrize fixture, but I have to hard code fixture.params which is really ugly.
```python3
# conftest.py
@pytest.fixture(scope='function')
def platform():
    return ['Event', 'Course']

@pytest.fixture(params=[0, 1])
def param(request, platform):
    return platform[request.param]

# test_main.py
def test_platform(param):
     # ...do some stuff
     assert result == param
``` 

Is there better way to solve this?

**Comment by SalmonMode** [comment]
This has been asked a few times in the past, but the problem is that test collection happens before the fixtures are run, and the fixtures are only run as the tests request them. Parametrization is evaluated during the test collection process and it's basically just looking at the params and generating permutations without running the code of any of the fixtures or tests.

Parametrization is actually a pretty clean way of handling this, especially in your case (assuming I'm reading this right). It didn't seem right to me either, but that was before I knew how I could leverage it effectively/properly. In your case, I would just do this:

```python
# conftest.py
PLATFORMS = ['Event', 'Course']
@pytest.fixture(scope='function', params=PLATFORMS)
def platform(request):
    return request.param
```

```python
# test_main.py
def test_platform(platform):
     # ...do some stuff
     assert result == platform
```

It's good to maintain the single responsibility principle for fixtures and tests, as well as keeping any state changing stuff in fixtures, rather than in your tests (the `# ...do some stuff` bit would be better off in one or more fixtures). The more you adhere to this, the more you can leverage dependency injection, which is what pytest is all about. I try to think of a single fixture as something that does and/or provides a single thing. If I define them that way, it's super easy for me to swap out any of them for a specific test (or group of tests) and achieve the desired flow with minimal effort.

Parametrization is exactly this, and is meant to let you easily do the same series of operations, just with a different set of data. I've even used it to generate tests that had a nearly identical structure (e.g. `assert getattr(thing, that) == stuff`, where `that` and `stuff` were parametrized).
