### ISSUE TITLE
Test failure based on order of methods in test class

### ISSUE THREAD

**Issue by smmalmansoori** [pytest-dev/pytest#5309]
Using a class based test `TestUser` if I place the method `test_to_dict_without_phone_and_email` before either `test_to_dict` or `test_from_dict` the latter would fail with a KeyError. However, when placed after them they would all pass.

The issue seems related to ``User.to_dict`` which all three methods call with the following difference in parameters:

`test_to_dict` & `test_from_dict`:

```python
user.to_dict(include_phone_number=True, include_email=True)
```

`test_to_dict_without_phone_and_email`:

```python
user.to_dict()
```

I've checked a couple of times and I don't think the bug is in my code. Here's a stripped down version of my project which reproduces the issue.

- [sample-pytest-failure](https://github.com/smmalmansoori/sample-pytest-failure)

---

**How to run the code (requires Python 3.7)**

```console
$ git clone https://github.com/smmalmansoori/sample-pytest-failure.git
$ cd sample-pytest-failure/
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install -r requirements.txt
$ pytest
```

The output would be the following error:
```console
___________________________ TestUser.test_from_dict ____________________________

self = <tests.unit.test_models.TestUser object at 0x103bd2668>
session = <sqlalchemy.orm.scoping.scoped_session object at 0x103bd2d30>
user = <[KeyError("'phone_number'") raised in repr()] User object at 0x103bd2550>

    def test_from_dict(self, session, user):
        session.add(user)
        session.commit()

        user.from_dict({'phone_number': '+971521234568',
                        'email'       : EMAIL})

        data = user.to_dict(include_phone_number=True, include_email=True)
>       assert data['phone_number'] == '+971 52 123 4568'
E       KeyError: 'phone_number'

tests/unit/test_models.py:128: KeyError
===================== 1 failed, 13 passed in 2.31 seconds ======================
```

---

```
$ pip list
Package           Version
----------------- -------
alembic           1.0.10 
atomicwrites      1.3.0  
attrs             19.1.0 
Babel             2.6.0  
Click             7.0    
dnspython         1.16.0 
email-validator   1.0.4  
Flask             1.0.3  
Flask-Babel       0.12.2 
Flask-Migrate     2.5.1  
Flask-SQLAlchemy  2.4.0  
idna              2.8    
itsdangerous      1.1.0  
Jinja2            2.10.1 
Mako              1.0.10 
MarkupSafe        1.1.1  
more-itertools    7.0.0  
mypy              0.701  
mypy-extensions   0.4.1  
phonenumbers      8.10.12
pip               19.1.1 
pluggy            0.11.0 
py                1.8.0  
pytest            4.5.0  
python-dateutil   2.8.0  
python-editor     1.0.4  
pytz              2019.1 
setuptools        41.0.1 
six               1.12.0 
SQLAlchemy        1.3.3  
sqlalchemy-stubs  0.1    
SQLAlchemy-Utils  0.33.11
typed-ast         1.3.5  
typing-extensions 3.7.2  
wcwidth           0.1.7  
Werkzeug          0.15.4 
```
macOS Mojave 10.14.5
```
$ uname -a
Darwin MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```
```
$ pytest --version
This is pytest version 4.5.0, imported from ...
```

**Comment by asottile** [comment]
We're unfortunately not a debugging service -- this is far from a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example), if you could get it down to a simple reproduction (ideally a single file < 100 lines) then perhaps we can take a look at it

I suspect you have a classic case of test pollution due to global state somewhere -- you'll likely need to use a debugger to figure out where things diverge between your two scenarios.  I'd suggest stepping through with either `pytest --trace`, or by setting a manual `breakpoint()` or by postmortem debugging using `pytest --pdb`

**Comment by asottile** [comment]
as a wild-ass-guess it's probably the wacky decorators and using mutable sets, almost certainly this line is a problem: https://github.com/smmalmansoori/sample-pytest-failure/blob/644d2a2ac763a29c05d2fb93624f8cd7851b0e62/src/app/model/meta/schema.py#L20

try changing the magic decorators to use `frozenset` instead of set literals and you might find your problem

good luck 😉

**Comment by smmalmansoori** [comment]
I thought it would only be mutable if passed as default parameter value *facepalm*. Anyways thanks and sorry for the trouble, it worked out.

**Comment by asottile** [comment]
no problem :)
