### ISSUE TITLE
wrong input may cause exception in pytest code

### ISSUE THREAD

**Issue by pvrij** [pytest-dev/pytest#5445]
On 
platform win32 -- Python 3.8.0b1, pytest-4.6.2, py-1.8.0, pluggy-0.12.0
I did:

```
pytest --fixtures
```

and got:

```
======================================================= ERRORS ========================================================
___________________________________________ ERROR collecting testresult.txt ___________________________________________
c:\python38\lib\site-packages\py\_path\common.py:165: in read_text
    return f.read()
c:\python38\lib\codecs.py:322: in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
E   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 165981: invalid start byte
========================================= 5 skipped, 1 error in 30.06 seconds =========================================
```

The error apparently relates to:

```
c:\python38\lib\site-packages\py\_path\common.py:164
        with self.open("r", encoding=encoding) as f:
```        
Note that LocalPath.open does not support an encoding argument.

In `C:\Python38\Lib\site-packages\py\_path\local.py`

I replaced

```
            return py.error.checked_call(io.open, self.strpath, mode, encoding=encoding)
```

by:

```			
            return py.error.checked_call(io.open, self.strpath, mode, encoding=encoding, errors='backslashreplace')
```

this takes care of the exception.

I believe the cause of the error on my side was a file called 'testresult.txt' containing the results of a pytest run with output redirection.

**Comment by nicoddemus** [comment]
Hi @pvrij,

The problem is that `testresult.txt` contains invalid UTF-8 characters. `test*.txt` files are by default collected as doctests as UTF-8, hence the error.

The only thing left to do on pytest's side would be to no longer collect `test*.txt` files by default, not sure we should do that as it is a breaking change though.

**Comment by pvrij** [comment]
Hello Bruno,

I'm completely inexperienced with pytest, so any answer is acceptable to
me. However, I believe that an uninformative exception like 'UnicodeError'
in pytest code should be prevented. This could be done by the
'backslashreplace' (or any tolerant error response scheme), which boils
down to 'ignore'. Alternatively you could maybe catch the error and provide
an appropriate errormessage - so that newbies like me (easily) understand
what's going on.

(I also don't understand how output-redirection could lead to illegal
utf-8; but that is not so important)

kind regards

Patrick

Op do 13 jun. 2019 om 21:56 schreef Bruno Oliveira <notifications@github.com

**Comment by nicoddemus** [comment]
Hi @pvrij, 

> I believe that an uninformative exception like 'UnicodeError'
in pytest code should be prevented. This could be done by the
'backslashreplace' (or any tolerant error response scheme), which boils
down to 'ignore'

I don't think that would be a good idea, because then you would get garbled text. I empathize with your view as an experienced user, but I believe it would be even worse to get garbled text back because then you would have an even harder time to figure out what's going on.

I believe the real problem here is that `test*.txt` is collected by default by pytest. The pattern used to collect python files are `test_*.py` and `*_test.py`, so it feels like an oversight that doctests are collected by the `test*.txt` pattern.

I've opened https://github.com/pytest-dev/pytest/issues/5450 to discuss the default behavior we have today.

Thanks for writing!
