### ISSUE TITLE
pytest.ini options in installed package

### ISSUE THREAD

**Issue by astrofrog** [pytest-dev/pytest#5815]
For a project I'm working on, I need to customize the behavior of the tests via options in a ``pytest.ini`` file, and I'd like these options to get picked up when running tests on the installed package with:

```
pytest --pyargs packagename
```

So I attempted to make it so that ``pytest.ini`` lives inside the package and gets installed with it, but this doesn't seem to work. I set up [a very minimal example here](https://github.com/astrofrog/debug-pytest). Basically if I do:

```
pytest debug_pytest
```

in the repository, the option in ``pytest.ini`` gets picked up, but if I install then run the tests with:

```
pip install .
cd <another directory>
pytest --pyargs debug_pytest
```

the ``pytest.ini`` file is ignored. Is there any way to get this to work, or are the better ways to customize pytest options in installed packages?

I know that using ``conftest.py`` might be an option, but I'd like to only use that as a last resort if needed - the reason for that is because I actually need to be able to do the above for a number of different packages that use a specific plugin, and dealing with maintaining a structured file like ``pytest.ini`` or ``setup.cfg`` is much easier than maintaining free-form Python code.

I'm using pytest 5.1.2 on MacOS X 10.14.6. Thanks!

**Comment by nicoddemus** [comment]
Hi @astrofrog,

`conftest.py` files would be an option, but given that you would rather an alternative, one I can think of is using the `PYTEST_ADDOPTS` environment variable together with the `-o` flag.

**Comment by astrofrog** [comment]
@nicoddemus - thanks! Just to check, is it expected behavior that the pytest.ini approach as above doesn't work?

**Comment by nicoddemus** [comment]
Yes, because of how pytest searches for the rootdir: if no specific files or directories are given, it uses `.` as starting point to search for the rootdir and consequentially the `pytest.ini` files.

Even if we were to support this somehow, then users might have their own `pytest.ini` file found around, which they would like to overwrite yours or not.

For this to work we would need to support multiple config files, which brings its own complexity of which option is overwritten by which of the possible config files.

Given the complexities involved, I don't think we have any plans to introduce this type of complexity any time soon.

**Comment by astrofrog** [comment]
@nicoddemus - ok thanks! In that case feel free to close this.

**Comment by nicoddemus** [comment]
OK then, thanks!

**Comment by espdev** [comment]
@astrofrog 

Also you can use `-c` option to specify the path to the configuration file explicitly. It might help in some cases. I had the same troubles and it works in my case because I execute pytest via [my cli entry point](https://docs.pytest.org/en/latest/example/simple.html#freezing-pytest).

```
-c file   load configuration from file instead of trying to locate one of the implicit configuration files.
```
