### ISSUE TITLE
Team UNAVAILABLE on Sep 20th - Digital #ClimateStrike

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#5862]
https://digital.globalclimatestrike.net/

**Comment by ml31415** [comment]
Is it really necessary to bring this ideological issues even into software development projects?

**Comment by RonnyPfannschmidt** [comment]
Yes, it's a issues that would destroy the world if left alone, doing nothing is wrong

**Comment by ml31415** [comment]
And it's an issue that you want to resolve and sort out here on github?

**Comment by RonnyPfannschmidt** [comment]
It's an issue we partake in awareness raising, as such its necessary to communicate the ramifications on support platforms like this issue tracker

**Comment by ml31415** [comment]
Can we also discuss world peace, child abuse and whatever else comes to mind then?

**Comment by Kos** [comment]
> Can we also discuss world peace, child abuse and whatever else comes to mind then?

I'm having trouble identifying your actual intention behind this comment, can you explain please? Are you expressing frustration because you think it's not OK for the Pytest team to support climate change awareness in this particular way?

**Comment by RonnyPfannschmidt** [comment]
I'm starting to get the impression that you want to troll because you disagree about us choosing to participate in a globally organized political event for a certain cause

If that's the case, feel free to do that somewhere else.

Rethoric tactics like in the previous post are a disgrace, please take you fight somewhere where people want to fight

**Comment by Kos** [comment]
Apologies Ronny. I support what you're doing with #ClimateStrike. I was hoping to somehow address Michael's frustration but looks like I did really a terrible job here. :( It was out of place for me to join the thread  and I'm sorry.

**Comment by RonnyPfannschmidt** [comment]
My apologies as well, I was targeting the same post, but I neglected to properly target and you where faster

**Comment by RonnyPfannschmidt** [comment]
For more context, I am on a prolonged train ride and mobile atm

**Comment by ml31415** [comment]
And the next thing you come up with is to add some terms of service, that only supporters of some ideology are allowed to use pytest? Or some check, that all the latest power saving modes are enabled on the machine, else it refuses to work?

I really think this is just so offtopic, that it doesn't belong here. Anyways, enjoy.

**Comment by blueyed** [comment]
I agree with @ml31415 although I've thought about licenses so that only vegans can use my stuff.. ;)

But in general I was just remembered of this issue, since my attempts to trim the build matrix down have been ignored/rejected - saving power there would help the environment more than an action like this IMHO.

**Comment by nicoddemus** [comment]
> since my attempts to trim the build matrix down have been ignored/rejected

That's not really true, we have merged many PRs from you with that intent. 

Really, not sure what you want to accomplish with comments like this.

**Comment by blueyed** [comment]
@nicoddemus 
It's true that you have merged things from me in this regard, but I've said many times that it makes not much sense to run so many jobs.  Especially with regard to coverage I've made sure that it is only run to get everything covered, which means that it would be enough to only run those jobs.

E.g. with my fork I only have 3 jobs (IIRC) and get quite the same results (no Windows, but still).

I've found two PRs in this regard that were not accepted at least: https://github.com/pytest-dev/pytest/pull/4958 and https://github.com/pytest-dev/pytest/pull/4865 (this was merged, but there I also had this particular intention in mind, which you did not like/want).

> Really, not sure what you want to accomplish with comments like this.

I'm aware that they are snarky, and that I'm annoying in this regard.
This comes out of frustration, and I'm sorry, but at least I'm trying to be productive / constructive at its root.

I've remembered this issue here yesterday when waiting for CI, and just thought to state the fact that there is actually something actionable that could be done.
