### ISSUE TITLE
Problem with usefixtures in pytest 5.1.3

### ISSUE THREAD

**Issue by 1605200517** [pytest-dev/pytest#5880]
The following test passes.

```
import pytest
from email.policy import SMTP

# @pytest.mark.usefixtures("smtp_connection") 

@pytest.fixture
def smtp_connection():
    from smtplib import SMTP
    smtp = SMTP("smtp.gmail.com", 587, timeout=5)
    return smtp
    


def test_ehlo(smtp_connection):

    response, msg = smtp_connection.ehlo()
    assert response == 250


```

And the following does not (change: use global usefixtures labeling instead of passing the argument to the test).

```
import pytest

@pytest.mark.usefixtures("smtp_connection") 

@pytest.fixture
def smtp_connection():
    from smtplib import SMTP
    smtp = SMTP("smtp.gmail.com", 587, timeout=5)
    return smtp
   


def test_ehlo():

    response, msg = smtp_connection.ehlo()
    assert response == 250

```

Error message:
```
    def test_ehlo():
    
>       response, msg = smtp_connection.ehlo()
E       AttributeError: 'function' object has no attribute 'ehlo'

test_sandbox.py:15: AttributeError
```

Original example source (needed to change the smtp component library name):
https://docs.pytest.org/en/latest/fixture.html

Environment: Python 3.6.8, Ubuntu Linux 18.04.3

**Comment by The-Compiler** [comment]
If you want to access a fixture inside a test (rather than just relying on it for setup/teardown), you will need to add it as an argument.

`@pytest.mark.usefixtures` is only useful when you want to use a fixture for setup/teardown purposes, but don't need to access it - also note that you'd use that decorator on a test (or via `pytestmark` for all tests in a file/class/etc.), not on a fixture.
