### ISSUE TITLE
PytestCollectionWarning when importing a module named "Test*"

### ISSUE THREAD

**Issue by nakami** [pytest-dev/pytest#6154]
- [x] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions
- [x] minimal example if possible

## Description

My project structure:

- src/
    - TestComponents/
        - TestComponentA.py (contains class TestComponentA)
        - TestComponentB.py (contains class TestComponentB)
    - \<some other dirs and files on which tests are run\>
    - tests/
        - do_something_with_ComponentA_test.py
        - do_something_with_ComponentB_test.py

So, by convention, unfortunatelly some files in my project are named `Test*` and saved within the directory `TestComponents`. The files in `TestComponents/` are TO BE TESTED. In `tests/` I store the tests TO BE RUN onto the files in "TestComponents/" (and some others which don't cause issues).

In my test files, e.g. do_something_with_ComponentA_test.py, I import classes from TestComponents like this:

do_something_with_ComponentA_test.py:
```python
from TestComponents.TestComponentA import TestComponentA

def test_TestComponontA():
    testcomponenta = TestComponentA()
    # do something on testcomponenta
```

Unfortunately, pytest thinks that the class I imported contains a class with testcases, then finds an `__init__` method and stops. The former is the main problem already, I do not intend to include tests in `TestComponentA.py` (or in `TestComponentB.py`) - I just want to create a `TestComponentA`  (or `TestComponentB.py`) object to test its functionality. From what I see, pytest does not allow me to explicitly omit those import statements regarding collecting test classes.

## What I tried (without success)

- `-k "not TestComponents"` and `-k "not Test"`
- `--ignore=TestComponentA`
- `pytest.ini`: python_files = *_test.py

## Workaround

As a workaround, it seems that including the `import` statements inside a test function, but that's bad practise:

do_something_with_ComponentA_test.py:
```python
#from TestComponents.TestComponentA import TestComponentA

def test_TestComponontA():
    from TestComponents.TestComponentA import TestComponentA
    testcomponenta = TestComponentA()
    # do something on testcomponenta 
```

## Example

Running pytest via:
> python.exe' -m pytest src/tests

I get warnings like:

```
src\TestComponents\TestComponentA.py:3
  C:\GitLab-Runner\builds\<ID>\0\proj\src\TestComponents\TestComponentA.py:3: PytestCollectionWarning: cannot collect test class 'TestComponentA' because it has a __init__ constructor (from: src/tests/do_something_with_ComponentA_test.py)
    class TestComponentA:
````

## pytest and operating system versions

- Windows 10 64bit
- Python: 3.7.4
- pytest-5.2.2

**Comment by K1ngjulien** [comment]
# this is dumb 

afaik it is trying to collect test results from all classes starting with "Test" because thats what unittest would do. But its event trying to do that with **imported classes**, which are obviously not the classes used for unittesting. those should be in their own files anyway! is the following really the expected behaviour??

```
.
├── src
│   ├── __init__.py
│   └── module.py
└── tests
    └── test_module.py
```
```python
# src/module.py

class TestClassThatsNotATest:
    def __init__(self):
        pass

    def return_one(self):
        return 1 
```

```python
# tests/test_module.py

from src.module import TestClassThatsNotATest

def test_module_returns_one():
    obj = TestClassThatsNotATest()
    assert obj.return_one() == 1
```

running the tests returns a warning for the class that was imported, because it has `__init__`, even tho that class is not in a file named `test_*.py`

```
[~/code/importtest]: python -m pytest
===================================== test session starts =====================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/julian/code/importtest
collected 1 item
tests/test_module.py .                                                                   [100%]
======================================= warnings summary =======================================
src/module.py:3
/home/julian/code/importtest/src/module.py:3: PytestCollectionWarning: cannot collect test class 'TestClassThatsNotATest' because it has a __init__ constructor (from: tests/test_module.py)
class TestClassThatsNotATest:

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================= 1 passed, 1 warning in 0.02s =================================

```

BUT if i do one simple workaround, by importing the class as something not starting with "Test", pytest doesn't complain


```python
# tests/test_module.py with workaround

from src.module import TestClassThatsNotATest as SomeOtherName

def test_module_returns_one():
    obj = SomeOtherName()

    assert obj.return_one() == 1
```

now the tests don't produce any warnings:
```
[~/code/importtest]: python -m pytest
===================================== test session starts ======================================
platform linux -- Python 3.8.5, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/julian/code/importtest
collected 1 item

tests/test_module.py .                                                                   [100%]

====================================== 1 passed in 0.01s =======================================
```

**Comment by bluetech** [comment]
@K1ngjulien, "this is dumb" is a pretty bad way to start a conversation.

This behavior is intentional. Importing tests into a file is a reasonable and supported thing to do. Your workaround is good, but if you must import a class named `Test*` to your test file, another workaround is to add a `__test__ = False` class attribute to that class, then pytest will skip it.

**Comment by K1ngjulien** [comment]
@bluetech sorry ^^
thanks, i wasn't sure someone would still reply here
the `__test__ = False` unfortunately doesn't work for my usecase....

My concrete issue is the following class which is used to annotate types from a JSON REST API:
```python
class TestCase(TypedDict):
    TestCaseId: int
    AuthorId: int
    OwnerId: int
... 
``` 
unfortunately, you can only add type annotations in a class deriving from `TypedDict`. is there another way or will I have to use my approach?

additionally, that class doesn't even have `__init__`

**Comment by nicoddemus** [comment]
You may import it as a different name:

```
from xyz import TestCase as TTestCase
```

Alternatively you can delete it at the end of the module:

```
del TestCase
```

This way pytest won't be able to see it when it loads it and starts to look for classes named `Test`.

Alternatively you can change the prefix used to identify test classes with [python_classes](https://docs.pytest.org/en/latest/reference.html#confval-python_classes).

**Comment by K1ngjulien** [comment]
thank you. I think I'll stick to using them as `modulename.Classname`

**Comment by captain-fox** [comment]
Isn't is just easier to rename source modules and classes?
If this implementation is already causing troubles with `pytest` then covering it with any kind of workaround is not worth the cost of facing other unforseen and costly issues, which would probably be much harder to debug. 

I'd rather "bend" company's naming policy and go extra mile to explain why the change is necessary.

**Comment by K1ngjulien** [comment]
The API library I was writing was interfacing with a test managment tool used to keep track of all sorts of testing related stuff which meant that many of the endpoints looked somewhat like this:

```python

def get_testcase(case_id: int) -> TestCase:
    ...

def get_testrun(run_id: int) -> TestRun:
    ...
```

Therefore changing the class names would not really make sense, make the consumer code less readable and had nothing to do with company naming policy.

I'm no longer working on that project but I don't think I came across any more issues after just using a different way of importing the class i.e. something along the lines of this:

```python
import apilib

def test_something():
    obj = apilib.TestCase()
    ...
```


Since there is no `from ...` import used here, the class is not inside the `dir()` of the `test_something.py` module and therefore pytest doesn't try to collect test results from it and it works.
