### ISSUE TITLE
activate github sponsor option

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest#6211]
I saw that that while the project already activated the funding option, it links to two 3rd party platforms. I would prefer to be able to use GitHub itself for several reasons:
* already using it as donor and receiver
* increased visibility on github profiles (networking effect)
* github is matching donation to some extent
* i prefer to keep my donations in single platform, at least for the moment 
* my initial attempt to activate tidelift on a project endup up in limbo

**Comment by hugovk** [comment]
It's possible to be GH sponsored as a team as well:

> You'll need to provide an organization bank account in order to join. GitHub Sponsors does not support organization payouts to individuals' personal bank accounts.

I think I read somewhere that the PSF can help with with that part, but can't find it now.

**Comment by ssbarnea** [comment]
With teams/organizations it can easily get more complex. If you go with personal account, you easily add as many individuals you want. I would go with personal for start and look for team aspect for the future. Activating my own sponsor account took only two or three days.

**Comment by RonnyPfannschmidt** [comment]
additionally with githubs continued support of ICE i'm not sure how much we want to buy into the platform

**Comment by ssbarnea** [comment]
@RonnyPfannschmidt I do not share much love either but at the same time, we can drop at any moment, especially after the matching ends, and we already build a longer list of donors. Once these happen it would be easier to as them to switch from one platform to another, but building the network is the hard task. I even find hard for myself to get into the habit of donating, making habit takes time, so lets be sure we do our best to ease that.

**Comment by RonnyPfannschmidt** [comment]
@ssbarnea thanks for elaborating the strategic gradients there

**Comment by The-Compiler** [comment]
FWIW I do already have my own [sponsorship profile](https://github.com/sponsors/The-Compiler/) up and running since around four weeks - for me personally, it's been quite a success (currently at around $1300 monthly, after GitHub's matching). 

However, that's mostly via [qutebrowser](https://www.qutebrowser.org/) users, where it's reasonable that donations go to me, given that I do a lot of work on it.

For a project like pytest, which is much more group-maintained, I'm not so sure - how do you expect a user to decide which maintainers to donate to, and at which levels? Sure, if everyone had some $1 level, they could just pick everyone from the list - but given that everyone can set up their own tiers/levels, it can get complicated fast.

**Comment by The-Compiler** [comment]
It looks like OpenCollective offers a [closed beta sign-up](https://forms.gle/xgacvmzTqFxaMzo4A) so their account can be used for GitHub Sponsors. Should we sign up for that, given that we already [do use OpenCollective](https://opencollective.com/pytest)?

**Comment by nicoddemus** [comment]
Oh definitely! Can you sign us up @The-Compiler? 😁

**Comment by The-Compiler** [comment]
Done!

**Comment by nicoddemus** [comment]
Thanks @The-Compiler!

Should we close this then?

**Comment by The-Compiler** [comment]
I'd say leave it open until we actually launch stuff - there's probably still plenty to discuss until then.

**Comment by nicoddemus** [comment]
True!

**Comment by blueyed** [comment]
@RonnyPfannschmidt thanks, missed that one.

**Comment by The-Compiler** [comment]
I never got an answer for the closed beta signup, but it looks like this went out of beta now:

https://blog.opencollective.com/double-the-love/

So is this something we should set up now? Note we probably don't necessarily *need* more money currently :laughing:

If we set it up: Someone else will have to draft some text/tiers for it, but I'd gladly review/proofread things.

Also, I'd suggest distributing stickers for some level (I'd say 5$ or 10$ monthly), and I'll gladly take care of the distribution around May/June (as I'm sending out stickers for the qutebrowser crowdfunding then anyways).

**Comment by ssbarnea** [comment]
Feel free to put personal profiles on sponsorship for pytest. Nobody said it must be only one, any core deserves to be listed there. In the end, the personal approach may prove to be a better way to distribute the donations, let the user decide which to donate to :D

**Comment by The-Compiler** [comment]
FWIW I did add my [sponsorship profile](https://github.com/sponsors/The-Compiler/) for [pytest-qt](https://github.com/pytest-dev/pytest-qt/) (after @nicoddemus agreed) since that's where I probably contributed most to.

I'd happily add myself to `FUNDING.yml` here as well if that's okay for others, but I'm not sure - for one, I'm not doing a lot in the pytest core currently (mainly a bit of triaging, I guess), and also there's a maximum of four usernames which can be listed.

**Comment by ssbarnea** [comment]
I did not know about the max cap. Still, who to prio could be an issue after the cap is reached.

**Comment by nicoddemus** [comment]
> I'd happily add myself to FUNDING.yml here as well if that's okay for others, but I'm not sure - for one, I'm not doing a lot in the pytest core currently (mainly a bit of triaging, I guess), and also there's a maximum of four usernames which can be listed.

I've missed this reply apparently.

Definitely feel free to add yourself there @The-Compiler; I think everyone who has contributed in the past is welcome to add their personal sponsorship profile there (limits aside of course), as it is clear that the sponsorship is personal.

**Comment by ssbarnea** [comment]
@nicoddemus How about creating a `meta` project which we could use for organization level tasks/features, and avoid polluting pytest itself with it?

I seen many organizations doing this, including https://github.com/PyCQA/meta/

**Comment by gnikonorov** [comment]
I think a meta project would be very helpful

**Comment by The-Compiler** [comment]
I took a quick look through the pytest-dev organization and I'm seeing some ~10 people with GitHub Sponsors profiles. Given that we don't have an easy way to list everyone, I'd rather not go down this route at all.

My original intention with this was to provide a way for people to "tip" if someone was involved in a PR/issue they're interested in, but given that there's already a sponsor button when hovering someone's comment, I think that suffices.

**Comment by ssbarnea** [comment]
There are benefits on having the top sponsor button enabled, reminds users about the funding aspect more than the tooltip. They will be able to make a decision about whom to sponsor or not. IMHO, is better to have some people there than none.

How about not over-complicating it and deal with the limit only when we reach it? Github itself may address it for us.

The Pulse tab can give an insight about who should be eligible to list himself there. In the end no change is made without review. For example, I would gladly support @nicoddemus and @The-Compiler from being listed there.

Based on my experience with projects using it I start to believe it has one very good unexpected advantage: seems to speedup reviews from maintainers. I cannot prove it with numbers but the feeling is clear: the change of getting a review done on a proposed change is far bigger if there is a sponsorship relationship.

Regarding the meta project, I can also create it but that is not up to me to make this decision. Put some thumbs up/down on my previous comment to count the "votes".

**Comment by nicoddemus** [comment]
We have two separate discussions:

1. Add individuals to the Sponsor button in the `pytest-dev/pytest` repository.

   I understand @The-Compiler's concerns, at the point where the "Sponsors" program reaches most developers (at the moment it is not available in all countries yet), it will be a bit of an uncomfortable having to "elect" who gets to appear in the Sponsor button or not, or when that max number of people are reached, even people who might get elected will not be conformable to speak up because that would mean removing someone else from there.

   So while I sympathize with the thought of "not over-complicating it and deal with the limit only when we reach it", I think if we go ahead with it, then when we reach that point of having reached the maximum number of individuals in the Sponsor button will make things extra complicated.
   
   For those reasons I personally would prefer not to do it until GitHub increases that limit (also it helps that decision that @The-Compiler, which would be one of the beneficiaries, also thinks this way).

   > the change of getting a review done on a proposed change is far bigger if there is a sponsorship relationship.

   Out of curiosity, what do you mean? When the person opening the PR is a sponsor, and the reviewer is sponsored? 

2. About the `pytest-dev` organization meta project.

   I like this idea, I believe we can use it to host:

   * Instructions on how to move/create plugins in pytest-dev.
   * Samples for `tox.ini`, GitHub actions, travis files, pre-commit configs, etc.
   * Code of conduct: this is a bit delicate, so I believe an approach that can work is to add a code of conduct that applies to all repos in the org, *unless* they include a code of conduct themselves. I don't think the code of conduct should be enforced to *existing* repos because it was not part of the requirements when they joined, but it *could* be made a requirement for new plugins to conform to the code of conduct. 
     We should then opening an issue in all repos (and closing it afterwards perhaps) noting about the new code of conduct that the repos are now implicitly subscribing to, and steps maintainers can take if they don't want to be a part of that. I mention this not because I expect people to opt-out of the code of conduct, mostly because it should not be done without their acknowledgement.

    Does that fit of what you think a meta project could bring to the table @ssbarnea?
