### ISSUE TITLE
Include deploy and coverage in GitHub actions

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#6369]
Follow up to https://github.com/pytest-dev/pytest/pull/6355:

- [x] Coverage
- [x] GitHub release notes
- [x] Deploy
- [x] Cleanup Azure and Travis files

**Comment by nicoddemus** [comment]
https://github.com/pytest-dev/pytest/pull/6441#discussion_r366372520

**Comment by webknjaz** [comment]
FTR it should be possible to request the missing interpreters from GH for GHA by opening an issue in their setup-python repo

**Comment by The-Compiler** [comment]
I guess the other question is how far away we are from dropping 3.5.0/.1 (see e.g. #5751) or just 3.5 entirely (upstream support [ends this September](https://devguide.python.org/#status-of-python-branches)). Perhaps we should start showing deprecation warnings for Python 3.5 with pytest 5.1 or so? I think I'd rather just keep Travis around until we dropped it instead of investing time (both ours and Github's) in something which we'll remove a few months down the line.

**Comment by nicoddemus** [comment]
> Perhaps we should start showing deprecation warnings for Python 3.5 with pytest 5.1 or so?

(I guess you mean pytest 6.1)

Not sure, we did this in the past with Python 2.7 support and a lot of people complained that they were sick of tools telling them all the time about Python 2.7 deprecation.

I don't think we need to explicitly tell users about the upcoming Python 3.5 support drop, due to `python_requires` Python 3.5 users will still get a supported version with `pip install`.

I'm closing this now, I think we will remove Travis files naturally as part of dropping Python 3.5 support. 👍

**Comment by webknjaz** [comment]
> a lot of people complained that they were sick of tools telling them all the time about Python 2.7 deprecation.

LOL this reminds me of https://github.com/pyca/cryptography/issues/5335#issuecomment-663747001. OTOH I think emitting a deprecation is the right thing to do.
