### ISSUE TITLE
doc: TerminalReporter is not documented

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest#6649]
It could be added as follows, but only `rewrite` has a docstring and would be included.

It is used with the `pytest_terminal_summary` hook at least, and therefore is public API it seems.

```diff
diff --git i/doc/en/reference.rst w/doc/en/reference.rst
index 50e32d660..552ad895b 100644
--- i/doc/en/reference.rst
+++ w/doc/en/reference.rst
@@ -838,6 +838,13 @@ Session
     :members:
     :show-inheritance:

+TerminalReporter
+~~~~~~~~~~~~~~~~
+
+.. autoclass:: _pytest.terminal.TerminalReporter
+    :members:
+    :inherited-members:
+
 TestReport
 ~~~~~~~~~~

```

**Comment by shankarj67** [comment]
I would like to work on this. What exactly do I have to do?

**Comment by blueyed** [comment]
@shankarj67 
My patch from above might be enough to make it show in the docs.
Check `tox -e docs` to generate them (or `make -C doc/en` if you have deps installed).

**Comment by mcsitter** [comment]
I build the documentation. You can see the result here:
![grafik](https://user-images.githubusercontent.com/48606431/83338625-7f3ab680-a2c6-11ea-9b06-c2330bb5d0de.png)
The page is already very long so this addition should not hurt the usability. Of course it is also properly added in the table of contents with all the links (including to source) working properly.
![grafik](https://user-images.githubusercontent.com/48606431/83339073-616f5080-a2ca-11ea-9e57-8b1f01d69747.png)

I assume the reason why only `rewrite` is shown is because it is the only method with a docstring in the class as the source indicates. Adding relevant docstrings would be great but sadly that is beyond my skills and knowledge.

I am happy to open a PR for the fix.
Commit: mcsitter/pytest@5c3296ca21500581224a2e4becefc74995b6752b

**Comment by soxofaan** [comment]
same issue here: I was looking into `pytest_terminal_summary` at https://docs.pytest.org/en/latest/reference/reference.html#pytest.hookspec.pytest_terminal_summary but "TerminalReporter" there is a bit of dead end at the moment. 

I think even the minimal docs from the quickfix mentioned above would be useful as it would at least link to the appropriate source code at  https://docs.pytest.org/en/latest/_modules/_pytest/terminal.html, which is a lot better than the current dead end.

**Comment by soxofaan** [comment]
@blueyed  I created PR https://github.com/pytest-dev/pytest/pull/12661  from your suggestion. Do you want me to include attribution to you in the changelog entry?

**Comment by soxofaan** [comment]
FYI: in the mean time two `TerminalReporter` methods got docstrings: `wrap_write` and `build_summary_stats_line`

The added doc section now looks like:
![image](https://github.com/user-attachments/assets/1cd7fb28-4fb5-44d9-bc6e-07855cfcf107)
