### ISSUE TITLE
Wondering what the recommended way to do fixtures for unit versus integration tests is

### ISSUE THREAD

**Issue by ayroblu** [pytest-dev/pytest#6679]
Hi, I setup a conftest to disable internet, but I only want to disable it for unit tests.
My current command to run a unit test is:
`pytest -s -c='./config/python/pytest_unit.ini' src`

**Comment by Formartha** [comment]
We'll, depends on the way you've implemented it.
Fixture could be easier to maintain than conftest for the entire project. 

In any case,
if you still wish to proceed with conftest configuration, you can set it up in a unit module so that it will be used only by it.
Than, call the tests from the folder of the unit tests.

e.g.
`project 
        - tests
                 - unit_tests
                           - conftest.py (disable internet)
                           - tests.py
                 - integration_tests
                            - tests.py
`

**Comment by Zac-HD** [comment]
Closing this issue as the question seems to have been answered.  For future reference, we recommend using the [`pytest` tag on stackoverflow](https://stackoverflow.com/questions/tagged/pytest).
