### ISSUE TITLE
Question: is it possible to chain fixtures?

### ISSUE THREAD

**Issue by DanielPBak** [pytest-dev/pytest#6824]
Not a bug or feature request (yet), but:

Is it possible to chain fixtures together in a way like what is described here?

https://stackoverflow.com/questions/47696002/chaining-pytest-fixtures

Without needing to use pytest.skip(), which sets the status of the test to "skipped" (rather than ignoring it outright)?

Either filtering fixtures (like this question describes) or combining them in some way (but not using the product of the combined fixtures but just chaining them).

If this isn't functionality that's provided natively, how would I go about adding it?

**Comment by markshao** [comment]
the framework could not understand wheter `None` is a test paremeter or not

Looks like need an api like this 
```python

def _filter(number):
    if number % 2 == 1:
        return number

@pytest.fixture(params=number, filter=_filter):
def odd_number(request):
    return request.param
```

**Comment by The-Compiler** [comment]
Hmm, I suppose you could solve this by using some special value (or even `None`) in the fixture, and then somehow use the [`pytest_collection_modifyitems` hook](https://docs.pytest.org/en/latest/reference.html#_pytest.hookspec.pytest_collection_modifyitems) to filter out the tests you don't want - no idea if that actually works though!

**Comment by RonnyPfannschmidt** [comment]
that filter proposal adds nothing over using a lsit comprehension to compose params

pytest has no cappability to do the chains asked for by in the stackoverflow question in a effective manner

there has been some talk about the idea of a "uncollect" or a "test ignore"

at work we have a private project which does takeout of tests in the modifyitems hook in case the environments are not availiable

**Comment by nicoddemus** [comment]
> Hmm, I suppose you could solve this by using some special value (or even None) in the fixture, and then somehow use the pytest_collection_modifyitems hook to filter out the tests you don't want - no idea if that actually works though!

The idea is good, but wouldn't work because `pytest_collection_modifyitems` happens at collection time, and by that time fixtures have not been created yet for one to check their value. By the time the fixture executes and we have access to the value, the test is already part of the collection so it can't be removed (only skipped).

The only solution I can think of is really skipping the unwanted items during fixture execution:

```python
import pytest

@pytest.fixture(params=[0,1,2,3,4,5,6])
def number(request):
    return request.param

@pytest.fixture()
def odd_number(number):
    if number % 2 == 1:
        return number
    else:
        pytest.skip("even number: {}".format(number))

def test_all_positive(number):  # want to be called with 0, 1, 2, 3, 4, 5, and 6
    assert number >= 0

def test_all_odds_positive(odd_number):  # want to be called with 1, 3, and 5
    assert odd_number >= 0
```

**Comment by dbak-invn** [comment]
> > Hmm, I suppose you could solve this by using some special value (or even None) in the fixture, and then somehow use the pytest_collection_modifyitems hook to filter out the tests you don't want - no idea if that actually works though!
> 
> The idea is good, but wouldn't work because `pytest_collection_modifyitems` happens at collection time, and by that time fixtures have not been created yet for one to check their value. By the time the fixture executes and we have access to the value, the test is already part of the collection so it can't be removed (only skipped).
> 
> The only solution I can think of is really skipping the unwanted items during fixture execution:
> 
> ```python
> import pytest
> 
> @pytest.fixture(params=[0,1,2,3,4,5,6])
> def number(request):
>     return request.param
> 
> @pytest.fixture()
> def odd_number(number):
>     if number % 2 == 1:
>         return number
>     else:
>         pytest.skip("even number: {}".format(number))
> 
> def test_all_positive(number):  # want to be called with 0, 1, 2, 3, 4, 5, and 6
>     assert number >= 0
> 
> def test_all_odds_positive(odd_number):  # want to be called with 1, 3, and 5
>     assert odd_number >= 0
> ```
This is what I'm doing right now, but it leads to "test skipped" being in the final report.

Ideally, I would like to filter out these cases at collection time, not at execution time.


> that filter proposal adds nothing over using a lsit comprehension to compose params
> 

How does the filter add nothing? How would I use a list comprehension in this fashion to filter the fixture out of another fixture?

**Comment by dbak-invn** [comment]
What about an "ignoreif" marker that applies at collection-time?

**Comment by dbak-invn** [comment]
@RonnyPfannschmidt Can you clarify how the modifyitems hook works?

Also, how can I use a list comprehension with params to accomplish this filtering?

**Comment by SalmonMode** [comment]
I'm my opinion, a test should never be defined if it's never meant to be executed. In my experience, implementing logic to skip tests that you don't want to ever execute is a sign of an issue with overall test structure and/or design and will only bring more headaches.

> Can you clarify how the modifyitems hook works?

It's not so much how that hook works, an more so what happens (or rather _doesn't_ happen) before that hook.

Pytest basically generates tests as it runs through parsing definitions of things in your tests package. When something is parameterized, Pytest needs `ids` for the effected tests so that it can create unique nodeids for them and can call upon them later. To do this, it looks at the parameters passed to the `params` arg, and then either 1) uses the repr (or `__str__`? I forget at the moment) for each param set, 2) maps them to the list passed to the `ids` arg, or 3) uses the callable passed to the `ids` arg to generate `ids` to map the param sets to.

The fixtures are not executed to do this, and once this is done, the list of nodeids created is what the modifyitems hook gets.

> How does the filter add nothing? 

> Also, how can I use a list comprehension with params to accomplish this filtering?

Ultimately, you can put whatever you want into that argument, so long as it's iterable. How that iterable object gets created doesn't matter, as long as it's created before collection time (i.e. when python itself has to parse the package). So you can define your list outside of the fixture decorator in the global scope, storing it in a variable, and then just reference that variable to pass it to the params arg, e.g.:

```python
stuff = ["apple", "banana", "cherry"]

@pytesy.fixture(params=stuff)
def fruit(request):
    return request.param
```

So if you wanted to generate a list of odd numbers, you would just need to do something like:

```python
stuff = filter(list(range(10)), lambda x: x % 2 != 0)
```

Having a filter argument in the fixture decorator just isn't necessary because there's a built in way to filter list in Python already.

**Comment by Zac-HD** [comment]
Closing this as an inactive question.
