### ISSUE TITLE
Working with conftests.

### ISSUE THREAD

**Issue by thakkardharmik** [pytest-dev/pytest#6942]
Hello experts,

I am facing some issue using conftest at different hierarchy. Can someone help me understand the flow or suggest how can I achieve the following.
- conftest.py
- component1
   - conftest.py
   - sub1
      - conftest.py
      - test_1.py
   - sub2
      - conftest.py
      - test_2.py
- component2
   - conftest.py
   - sub
      - conftest.py
      - test_1.py

In the following structure I have some setup tasks (fixture) in component1/conftest.py that I want to perform after pytest_sessionstart and before fixtures in component1/sub1/conftest.py. 
I could see that post pytest_sessionstart, the fixture in component1/sub1/conftest.py get invoked instead. Is there a way to control this? or any suggestions on design.

**Comment by laurentbristiel** [comment]
did you add __init__.py files in your folders to make them package?
I see in this page of the doc that they put __init__.py in each folder so that they are packages (but I am not yet familiar enough to see if this is mandatory to have your conftest.py to be detected...)

**Comment by thakkardharmik** [comment]
@laurentbristiel yes I do have __init__.py in each of the folders.

**Comment by SalmonMode** [comment]
@thakkardharmik a conftest is basically a way to define fixtures (and pytest hooks) that see available for everything in the same package (i.e. folder) as that conftest, including sub-packages of that package. This doesn't control the order those fixtures run in, so there isn't a real hierarchy there. It's just availability. 

The only sort of hierarchy that exists is in regards to overriding fixture definitions. So if you define fixture `a` in `component1/conftest.py`, and another fixture `a` in `component1/test_thing.py`, the one in `test_thing.py` will override the one in the conftest, but only for that test file. Similarly, if you also had a fixture `a` defined in `component1/sub1/conftest.py`, it would override the one in the parent package's conftest, but only for `sub1`.

This still doesn't determine order those.

What determines order is, in order of importance:

1. The scope of a fixture (e.g. class, function)
2. Whether or not the fixture is "autouse"
3. Which fixtures are requested by other fixtures and tests

A fixture of a larger scope can't happen before a fixture of a smaller scope, so fixtures with larger scopes happen before smaller scoped fixtures. If fixture `a` requests fixture `b`, fixture `b` will happen first (because `a` is depending on `b`'s actions/value). If a fixture of a larger scope requests a fixture of a smaller scope, pytest will throw an error telling you this can't be done.

Pytest will look at all these factors to try and "linearize" the order in which fixtures should run. It's important to make sure that if you need a certain fixture to happen before another fixture, that you have that latter fixture request that former fixture. If you don't do this, pytest will effectively put them in whatever order it feels like, so you might as well consider it non-deterministic. It'll pick the same order every time (at least for a given version of pytest), but you shouldn't depend on that to control order as anything from an update to pytest, to just moving the definition of a fixture to another line in the file can impact the order they run in.

**Comment by Zac-HD** [comment]
Closing this as an inactive question.

@SalmonMode - you've been helpful in _so many_ of these, thanks for that! :star_struck:
