### ISSUE TITLE
Provide reverse order

### ISSUE THREAD

**Issue by thbde** [pytest-dev/pytest#7042]
As a developer, I want to execute the tests in reverse order to reveal test dependencies.

Given that the natural order of execution is O={t1, ..., tn}, maybe provide a command line switch that allows to run all tests on reverse order reverse(O)={tn, ..., t1}.

Further details and motivation: https://github.com/pytest-dev/pytest-randomly/issues/242
@adamchainz suggested to discuss incorporating this option into the core library instead of a plugin.

**Comment by The-Compiler** [comment]
Personally I think this is better suited for a plugin, but let's see what others say.

**Comment by Zac-HD** [comment]
Yep, [just use the `pytest-randomly`](https://pypi.org/project/pytest-randomly/) plugin.

**Comment by adamchainz** [comment]
Hi

I'm the developer of pytest-randomly. @thbde opened the issue there first and I encouraged them to open it here.

I didn't want to add a `--reverse` option to pytest-randomly, since it's not randomness associated. So I created [pytest-reverse](https://pypi.org/project/pytest-reverse/).

Given:
* the paper linked in the pytest-randomly issue shows reversal is almost as effective as random ordering for discovering test dependencies
* random order has its associated problems with non-determinism, etc.
* Django has for many years had the `--reverse` option in its unittest runner.
* the plugin isn't much code (13 lines)

...I figured this would be something worth adding to pytest core, and asked @thbde to open the issue here.

If you think it's fine in a plugin - great, I'm happy to maintain it. I'll suggest it for pytest-dev and ensure it's linked to appropriately in various docs. But I'd ask you to reconsider.

Thanks,

Adam

**Comment by blueyed** [comment]
Code for reference: https://github.com/adamchainz/pytest-reverse/blob/master/src/pytest_reverse.py

I think it is a good option for pytest itself.

It should then use a hookwrapper / extra handling though probably to ensure it works as expected with e.g. `--ff` (https://github.com/pytest-dev/pytest/commit/f75f7c192586fd856dad10673cd6d1f8cce03f75#diff-0f9f126d34efdf99c5f0cae4707bdca7).

**Comment by adamchainz** [comment]
Thanks for pointing that out @blueyed — I've updated the code to use a hookwrapper.

**Comment by symonk** [comment]
I would like to see --reverse brought into the core, i think it has a pretty nice use case for aiding with test dependence

**Comment by DahlitzFlorian** [comment]
If the feature is accepted to be part of the core of pytst, I would be more than happy to implement and test it.

**Comment by nicoddemus** [comment]
I think this is better off as a plugin, it is easy to implement it as such.

> If you think it's fine in a plugin - great, I'm happy to maintain it. I'll suggest it for pytest-dev and ensure it's linked to appropriately in various docs. But I'd ask you to reconsider.

We would gladly accept a PR in this regard! 😁

**Comment by adamchainz** [comment]
I tried to find somewhere to fit in the current docs but there isn't currently a section or page on test isolation. The "flaky tests" page touches on it but it would probably need a bit of a rewrite to separate the isolation-specific details.
