### ISSUE TITLE
Pytest's assertion rewrite rewrites assert's message; if multi-assert plugin is used, it can be wrong

### ISSUE THREAD

**Issue by GeorgeFischhof** [pytest-dev/pytest#7074]
Hi Folks,

when I use pytest-assume or pytest-check and assert (the function used instead of assert) contains an expression which can not be evaluated (only get value if the assert would fail), pytest generates an error.
I tried it with pytest-assume, pytest check, on linux, windows

here is an example with output. I used the őytest.assume or assert, the other code part was commented out.

BR,
George

```

import pytest


def test_rewrite():
    test_passed, info = do_testing()
    pytest.assume(test_passed, (
        'We have the following evidence: \n'
        'collected info:  %.2f'
        % (info)
    ))

    """
    Output of pytest.assume:
    
============================================= test session starts ==============================================
platform win32 -- Python 3.7.4, pytest-5.1.2, py-1.8.0, pluggy-0.12.0
rootdir: C:\\George\\Python\\Try_it_out\\try_pytest\\try_pytest
plugins: assume-2.2.0
collected 1 item

test_rewriting.py F                                                                                       [100%]

=================================================== FAILURES ===================================================
_________________________________________________ test_rewrite _________________________________________________

    def test_rewrite():
        test_passed, info = do_testing()
        pytest.assume(test_passed, (
            'We have the following evidence: \n'
            'collected info:  %.2f'
>           % (info)
        ))
E       TypeError: must be real number, not NoneType

test_rewriting.py:10: TypeError
============================================== 1 failed in 0.13s ===============================================

    """

    assert test_passed, (
        'We have the following evidence: \n'
        'collected info:  %.2f'
        % (info)
    )

    """
    Output of assert:
    
============================================= test session starts ==============================================
platform win32 -- Python 3.7.4, pytest-5.1.2, py-1.8.0, pluggy-0.12.0
rootdir: C:\\George\\Python\\Try_it_out\\try_pytest\\try_pytest
plugins: assume-2.2.0
collected 1 item

test_rewriting.py .                                                                                       [100%]

============================================== 1 passed in 0.04s ===============================================    
    """


def do_testing():
    info = None
    # do testing ...
    test_passed = True
    if not test_passed:
        info = collect_or_calculate_issue_related_info()
        # It can be expensive
    return test_passed, info


def collect_or_calculate_issue_related_info():
    info = 1.1
    return info

```

current pip list , but reproduced it when only pytest and pytest-assume were installed

atomicwrites==1.3.0
attrs==19.3.0
colorama==0.4.3
importlib-metadata==1.6.0
more-itertools==8.2.0
packaging==20.3
pip==20.0.2
playsound==1.2.2
pluggy==0.12.0
py==1.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycparser==2.19
pydantic==1.3
pydot==1.4.1
PyJWT==1.7.1
pyOpenSSL==19.1.0
pyparsing==2.4.2
pypiwin32==223
pyrsistent==0.15.6
pytest==5.1.2
pytest-assume==2.2.0
pytest-check==0.3.8
pytz==2019.3
pywin32==226
requests==2.22.0
rsa==4.0
setuptools==41.2.0
six==1.13.0
soupsieve==1.9.5
SQLAlchemy==1.3.13
sqlalchemy-schemadisplay==1.3
SQLAlchemy-Utils==0.36.3
starlette==0.12.9
urllib3==1.25.7
uvicorn==0.11.1
wcwidth==0.1.7
websockets==8.1
Werkzeug==0.16.0
zipp==0.6.0

**Comment by sallner** [comment]
Hello @GeorgeFischhof, 
if I understand you correctly, you would like to receive a test failure in case the expression `" %.2f" % info` cannot be evaluated with `info = None`. 
As far as I understand the code in `pytest-assume` and `pytest`, a test failure is only rendered, if an assume or assert is False. In this case it is rather a programming error, so it should be an actual error. If this is possible during a rewrite, then that seems bad luck. 

What would you expect in this situation? My naive approach would be to only pass messages which safely evalute, or evaluate before passing it to assume.

**Comment by GeorgeFischhof** [comment]
Hi @sallner,
the best thing would be, and I would like that, if the message would be evaluated only at failed assert / assume / whatever.

Assert works well. 

In this case I can replace the None with for example zero (and I did this), but this is just a workaround - I think.

In the example I wanted to show with the names, that in end-to-end testing it can happen, that gathering the evidence can be expensive, so that is why the variables have no valid values.

Programming error?
I do not know... In this case maybe it seems so, but it can happen that somehow the result of evidence collection only valid when the test failed.

Even worse, that it means, that the message evaluation is called even on a passed test. And it can contain other function calls which can do some harmful thing (tear-down or reestablish a connection)

Because assert works in a way, and everyone create the program according to this, where the message part is only evaluated if the value is false, so that is somehting like:

if passed:
    increment_number_of_good_test_cases_etc
else:
    evaluate_message_log_the_failure

BR,
George

**Comment by SalmonMode** [comment]
This appears to be an XY problem.

In python, strings are not lazy evaluated, including those formatted with `%`, so the string will always be evaluated before the arguments are passed to `pytest.assume`. The error is also being thrown because you're using `%.2f`, which is expecting a number. This will never work if `info` is `None`. So this isn't an issue with pytest. Also, just as a heads up, such strings are also no longer used in general since `str.format` is available, as are `f` strings, particularly because of issues similar to this one (i.e. `"something {}".format(None)`  and `"something {}".format(12.65)` will both work).

But going back to the core of your issue, as I mentioned [here](https://github.com/pytest-dev/pytest/issues/7075#issuecomment-612509405), pytest has it's own system for running multiple `assert`s. Going through plugins like pytest-assume (that add in alternate functionality, rather than enhancing the functionality that's already there) often leads to incompatibility with more advanced pytest features, such as assert rewrites. Working within a system as much as the system allows, provides maximum compatibility with that system (at least, usually).

I would take a couple steps back and start with a fresh take on how your end goal can be achieved with pure pytest. For that, there are 2 parts.

I would first consider the approach I mentioned [here](https://github.com/pytest-dev/pytest/issues/7075#issuecomment-612509405). That is incredibly useful when you have multiple things about a resulting state (triggered by a single action on an initial state) that you want to assert separately. For example, after signing in to a website, you might separately check that there is now a sign out button, and that the signed in user's info shows up.

That may not be what you need, or it may only be part of the puzzle for you. So for the next part, the key is abstraction.

You can make classes that represent data; either a discrete part of the state of your SUT, or the entire state. These classes can have magic methods, such as `__eq__`, that make comparisons/assertions _super_ straightforward and easy to read. The extra cool bit, is that you can define the `__repr__` for one of these classes, and pytest will show that repr in failure outputs. With this in place, if you do `assert x == y`, and it resolves to `False`, pytest will show the repr of both objects, and try to highlight where they are different. You can leverage the `__repr__` method this way to provide informative failure reports, as well as avoiding making the expensive calls you mentioned until there's an actual issue.

I recommend having each class represent discrete parts of the SUT's state, because that'd be inline with SOLID principles, easier to manage, and read better in your assertions (e.g. "assert sign out button is present" and "assert user info equals expected user" versus "assert page looks good").

**Comment by GeorgeFischhof** [comment]
Hi @SalmonMode,

thank you for your suggestions. 
I will check, and write / rewrite my test cases accordingly.

BR,
George
