### ISSUE TITLE
[Feature] Pytest should have its own native solution for using several asserts in one test case

### ISSUE THREAD

**Issue by GeorgeFischhof** [pytest-dev/pytest#7075]
Hi Folks

Pytest should have its own native solution for using several asserts in one test case

it is several times required for system / end to end tests, and there are some issues with plugins and / or pytest and plugin combinations

BR,
George

**Comment by symonk** [comment]
HI @GeorgeFischhof can you please elaborate the issue, with an example? what are the issues you are experiencing with plugin(s) regarding assertions?

**Comment by SalmonMode** [comment]
It has one. That's what fixtures with larger scopes can do. For example:

```python
@pytest.fixture(scope="class")
def do_thing_to_impact_system_state(system_state):
    # do thing

@pytest.fixture(scope="class", autouse=True)
def do_another_thing_to_impact_system_state(system_state, do_thing_to_impact_system_state):
    # do another thing

class TestSomething:

    def test_something_about_the_resulting_system_state(self, system_state):
        assert system_state.thing == "stuff"
    def test_something_else_about_the_resulting_system_state(self, system_state):
        assert system_state.another_thing == "more stuff"
```

In this approach, fixtures are used to perform state-changing actions targeted at the class-level scope. Because the final fixture is autouse, it triggers all previous fixtures automatically (reducing boilerplate fixture requests). This results in the class scope representing the final, resulting state. The tests can then make non-state-changing assertions against it, each checking the results of separate behaviors.

**Comment by GeorgeFischhof** [comment]
Hi @symonk,

for example the previous issue: #7074

BR,
George

**Comment by Zac-HD** [comment]
https://stackoverflow.com/questions/39896716/can-i-perform-multiple-assertions-in-pytest discusses a few ways to do this.

**Comment by hugovk** [comment]
See also subtests:

* https://blog.ganssle.io/articles/2020/04/subtests-in-python.html
* https://testandcode.com/111

**Comment by GeorgeFischhof** [comment]
Hi 

as it comes across again and again, I tried to put the data into a class, it is quite good, but not customizable (I have about 30 data in my real struct, and need to write, and explain about 5-10 in test cases, overlapping)

And I tried to put the assert into subfunction, and that is not good in a for cycle, which is also needed several times.

Below the code, and result ...

BR,
George

`

from dataclasses import dataclass


@dataclass
class MyData:
    apple: int
    banana: str


def test_try_it_out():
    for index in range(2):
        my_data = MyData(apple=index, banana='aaa')
        check_my_data(my_data)


def check_my_data(my_data: MyData):
    assert my_data.apple == 2, "my data apple 2"

`

`
Testing started at 9:53 ...
C:\Python37\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py" --path C:/George/Python/Try_iy_out/test_try_it_out.py
Launching pytest with arguments C:/George/Python/Try_iy_out/test_try_it_out.py in C:\George\Python\Try_iy_out

============================= test session starts =============================
platform win32 -- Python 3.7.6, pytest-5.1.2, py-1.8.0, pluggy-0.12.0 -- C:\Python37\python.exe
cachedir: .pytest_cache
rootdir: C:\George\Python\Try_iy_out
plugins: assume-2.2.0, pytest_check-0.3.8
collecting ... collected 1 item

test_try_it_out.py::test_try_it_out FAILED                               [100%]
AssertionError: my data apple 2
0 != 2

Expected :2
Actual   :0
<Click to see difference>

def test_try_it_out():
        for index in range(2):
            my_data = MyData(apple=index, banana='aaa')
>           check_my_data(my_data)

test_try_it_out.py:13: 



================================== FAILURES ===================================
_______________________________ test_try_it_out _______________________________

    def test_try_it_out():
        for index in range(2):
            my_data = MyData(apple=index, banana='aaa')
>           check_my_data(my_data)

test_try_it_out.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

my_data = MyData(apple=0, banana='aaa')

    def check_my_data(my_data: MyData):
>       assert my_data.apple == 2, "my data apple 2"
E       AssertionError: my data apple 2
E       assert 0 == 2

test_try_it_out.py:17: AssertionError
============================== 1 failed in 0.09s ==============================

Process finished with exit code 1

Assertion failed

Assertion failed

`

**Comment by SalmonMode** [comment]
@GeorgeFischhof I'd run with my example using multiple tests within a test class. Since you have 30 comparisons you need to make, I would include a test method for each one. This way, each test method can be named in regards to what it's looking for, which might be able to provide the explanation you're looking to give. Or you can take the `assert x == y, "explanation"` approach.

I'm working on some updates for the docs currently, and I've included an explanation of this class-based approach. You can find it [here](https://pytest--7381.org.readthedocs.build/en/7381/fixture.html#running-multiple-assert-statements-safely).

I'm not quite certain about which is best for your uses, but another approach is to rely on the `__repr__` produced by your dataclass classes by having an expected instance and comparing against that. Pytest will try to highlight where the differences are. For example, using your `MyData` class:

```python
def test_fruit():
    assert MyData(apple=2, banana="yes") == MyData(apple=3, banana="no")
```

Might produce a failure message like this (I'm on mobile, so this is just a rough approximation):

```
-<MyData apple=2 banana='yes'>
               ^         ^^^
+<MyData apple=3 banana='no'>
               ^         ^^
```
