### ISSUE TITLE
junitxml.py store test results after the whole session, not after every test.

### ISSUE THREAD

**Issue by anonyknight** [pytest-dev/pytest#7087]
Command to use:
**pytest --junit-xml='test.xml' --caputre=no** 

- [ ] _pytest/junitxml.py stores test results in function pytest_sessionfinish. If pytest was killed somehow during the test session, we see the captured log results in the terminal before the stopped point but cannot see test results in junit-xml. **Here the test results reporting behaviors are not aligned.**

- [ ] pytest-5.4.1.dev127+gf479cbce1

**Better solution:**
Saving test results into junit-xml after every test case can align the captured results in the terminal and junit-xml results.

**Comment by wagnerluis1982** [comment]
Hi, for this one, how about an alternative solution?

My idea would be to have an intermediary file with the test results, a kind of log, on finishing the tests, this file information would be dumped to `test.xml` (or whatever filename you choose).

This approach would not change current behavior.

The intermediary could be used in the future to restart the testing, but more important, would contain the partial test results.

**Comment by RonnyPfannschmidt** [comment]
The report log plugin provides that logging

It should be extended with a replay mechanism to enable transfer to the log to junitxml

**Comment by nicoddemus** [comment]
One thing to realize is that if the pytest process crashes, the `.xml` file will be invalid, missing the closing tags. Because of that the approach of writing during `pytest_session_finish` is the proper one I believe.

If processing a partial file in another format is not a problem, then [pytest-reportlog](https://github.com/pytest-dev/pytest-reportlog) is a good workaround as @RonnyPfannschmidt mentioned. 

Closing this now as I believe the above is a good approach to the problem. Let us know if there are further questions. 👍
