### ISSUE TITLE
data loss with mistyped --basetemp

### ISSUE THREAD

**Issue by ndevenish** [pytest-dev/pytest#7119]
This might entirely class "user error", but I mistyped the pytest launch command and lost my entire source repository, e.g. commits, stashes and WIP branches (most backed up, luckily). The system I was running on only had a small `/tmp` available so I wanted to change the path. Unfortunately I left a space in `pytest --basetmp= /scratch/tmp .` - this wiped out the entire working directory. It has the same behaviour if you don't provide a path:
```
mkdir test_folder
cd test_folder
echo -e "def test_a(tmpdir):\n  pass" >> test_a.py

pytest --basetmp= .
```

I note that the argument help says "(warning: this directory is removed if it exists)" but isn't mentioned on https://docs.pytest.org/en/latest/tmpdir.html#the-default-base-temporary-directory - and wouldn't protect against a typo anyway.

Only accepting folders that don't exist or that it's used before (with a breadcrumb file?) seem like A Fix, but changes the way it works and is more complicated. It might be simpler to be slightly safer? Is there any scenario in which allowing this option to be empty for the current working directory makes sense?

Cause looks to be https://github.com/pytest-dev/pytest/blob/3d0f3baa2bb89257dfff25ae6ebabd565287240e/src/_pytest/tmpdir.py#L31-L33 where `attr.converters.optional` treats an empty string as "Not None" and `os.path.abspath` interprets an empty string as cwd.

Pytest 5.4.1.

**Comment by bluetech** [comment]
> Only accepting folders that don't exist or that it's used before (with a breadcrumb file?) seem like A Fix, but changes the way it works and is more complicated.

I think we shouldn't change the remove-if-exists behavior. Certainly dangerous if typo'ed but functionally it's the desired behavior.

> It might be simpler to be slightly safer? Is there any scenario in which allowing this option to be empty for the current working directory makes sense?

None that I can think of. I doubt anyone is passing an empty value rather than `.` intentionally. Given the consequences, IMO we should definitely reject empty values for this option.

If you'd like to work on this, from a cursory look I think it will be good to reject in the argument parser already. So passing a custom [`type`](https://docs.python.org/3/library/argparse.html#type) for basetmp [here](https://github.com/pytest-dev/pytest/blob/4f8fff9cab6e2333890e21eb840724e7e4d41763/src/_pytest/main.py#L166).

**Comment by RonnyPfannschmidt** [comment]
both `.` and `''` should be rejected as unintended, similarly any parent folder of the cwd

**Comment by prashant616** [comment]
@RonnyPfannschmidt Hi, I am new to open-source projects and I want to work on this issue. Let me confirm what changes I need to make.
I have to add a custom argparse type in [this](https://github.com/pytest-dev/pytest/blob/master/src/_pytest/main.py) file which will be passed to [`basetemp`](https://github.com/pytest-dev/pytest/blob/5afa8717dba9c149dbd02ec257c8cbcb80c25514/src/_pytest/main.py#L167) and will return `None` if `basetemp` is `.` or `''` or parent of cwd.

**Comment by RonnyPfannschmidt** [comment]
Actually it should error

**Comment by pangloss** [comment]
Hi guys, I think this issue is mis-classified and is a very major issue. This issue can cause all work in progress together with the local .git repo to be lost irretrievably, meaning that it could cause developers to lose not only their work in progress, but also multiple commits or even their entire project. I know of at least one instance where this did lead to lost work on a real project. 

I see that there is an open PR to address this but it's been stalled for nearly a month.

@blueyed @nicoddemus are you aware of this major issue?

Thanks for your hard work on a great project!

**Comment by nicoddemus** [comment]
Indeed @pangloss, thanks for the ping! We are still in the process of reviewing everything for 6.0, and indeed this is a serious issue. 

The PR has now been merged. 👍
