### ISSUE TITLE
--doctest-modules runs __main__ files

### ISSUE THREAD

**Issue by max-sixty** [pytest-dev/pytest#7124]
- [x] a detailed description of the bug or suggestion
- [ ] output of `pip list` from the virtual environment you are using
- [x] pytest and operating system versions: pytest 5.4.1, MacOS
- [ ] minimal example if possible

As per this [SO question](https://stackoverflow.com/questions/61417426/is-if-name-main-required-in-a-main-py), pytest will run `__main__.py` files when passed `--doctest-modules`, even though it avoids them when collecting tests without that flag.

Is that intentional?

**Comment by FrozenBob** [comment]
pytest normally avoids `__main__.py` files not because of any specific `__main__.py` handling, but simply because the name `__main__.py` doesn't match the `test_*.py` or `*_test.py` patterns pytest looks for.

That said, `__main__.py` files are typically not considered modules, and even `multiprocessing` doesn't expect `__main__.py` files to have an `if __name__ == '__main__'` guard. Importing `__main__.py` is questionable behavior. Plus, `--doctest-modules` already avoids `setup.py`, which is a very similar case.

**Comment by Zac-HD** [comment]
Closing this because it's been answered (and inactive for more than two weeks) :smile:

**Comment by max-sixty** [comment]
@Zac-HD that wasn't exactly my interpretation of @FrozenBob 's response — though possibly I'm not understanding it fully — I interpreted his response as "Yes it's likely not correct behavior for pytest to import `__main__.py`"

While I think this is still a relevant issue, you know this better than I do, so feel free to close if you have other reasons to close.

Thanks as ever

**Comment by Zac-HD** [comment]
No, sorry, I should have read this more closely - I think you're right, and we should probably change this (though I haven't investigated in depth).

**Comment by nicoddemus** [comment]
Fixed by https://github.com/pytest-dev/pytest/pull/8949
