### ISSUE TITLE
Create new INI key that contains a list of required plugins

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest#7305]
Building off of https://github.com/pytest-dev/pytest/pull/7286, we need a way to let users list plugins that are absolutely required. We should have pytest emit a warning when a required plugin is not found, and the `--strict-config` flag should turn these warnings into errors if passed

The key for this should be called `required_plugins` and it should be a comma separated list of plugins that must be installed

So it would look like:
```
[pytest]
required_plugins = pugin1,plugin2,...,pluginN
```

**Comment by gnikonorov** [comment]
I propose we create a new key called `whitelisted_warnings` ( or similar ), and its value would be a comma separated list of keys that should not generate warnings when deemed invalid.

E.g.:
```
[pytest]
whitelisted_warnings = key1,key2,...,keyN
```

**Comment by gnikonorov** [comment]
Thoughts on the above format @RonnyPfannschmidt ?

**Comment by gnikonorov** [comment]
We can’t really easily do this by specifying a list of plugins to ignore, since we don’t know in advance all the plugins available the user may have declared key value pairs for

**Comment by RonnyPfannschmidt** [comment]
We shouldn't guess, we should have a list of required plugins so nothing in the ini is undefined

**Comment by gnikonorov** [comment]
@RonnyPfannschmidt - so you’re suggesting just add a field that lists required plugins and error if any of the plugins in the comma separated value is not loaded

**Comment by RonnyPfannschmidt** [comment]
i wuld start with a warning  i think

**Comment by gnikonorov** [comment]
Let’s do the same thing as we did with keys in the linked PR. Warning by default with the option to raise an error given as a flag

**Comment by nicoddemus** [comment]
Hey folks,

I'm curious what's the use case for this? I mean, why would someone rather white list some keys rather than require a plugin to be installed?

**Comment by gnikonorov** [comment]
@nicoddemus the idea is to allow users to opt out of invalid key warnings for plugins that may not always be installed ( correct me if I’m wrong @RonnyPfannschmidt ) since we introduced the raising of warnings for unknown INI keys in the linked PR in the issue description

**Comment by nicoddemus** [comment]
@gnikonorov thanks, but I understand that is the intent of the proposal, but I would to know about use cases for that feature, if possible. As I said, seems strange to me why someone would white list keys instead of requiring plugins to be installed.

In that sense, an option like `required_plugins` would make more sense to me: it would list plugins required to execute the test suite, so pytest can bail out with an useful message instead of (possibly) failing in a confusing manner.

An example: if a test suite uses `pytest-flask`, trying to execute it without `pytest-flask` installed will possibly fail with a confusing `'client' fixture not found`. Using the above idea however, the project could have `pytest-flask` listed in `required_plugins`, so pytest is able to bail out right away with `required plugin 'pytest-flask' not installed, exiting...`.

(Of course this is a different proposal altogether, just thought I would mention it).

**Comment by gnikonorov** [comment]
I think I misunderstood, and suggested the wrong thing. Reading your explanation I think `required_plugins` is the proper thing to do

**Comment by gnikonorov** [comment]
@nicoddemus @RonnyPfannschmidt if neither of you object to `required_plugins`, I'll go ahead and open a PR for it

**Comment by gnikonorov** [comment]
Friendly ping @RonnyPfannschmidt @nicoddemus. Are we ok with adding in a new INI key required_plugins and have it behave like the updated issue description?

**Comment by RonnyPfannschmidt** [comment]
@gnikonorov sorry for the delay, its indeed the way to go for now

**Comment by gnikonorov** [comment]
Thanks for confirming @RonnyPfannschmidt I’ll have a PR up soon
