### ISSUE TITLE
evaluate a new primary branch name to replace master

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#7344]
In light of the #BLM movement i bumped into https://twitter.com/mislav/status/1270388510684598272?s=19

As master in git appears to be inheritance from bitkeeper master/slave i think it's warranted that the complete pytest-dev org takes a bit of time to set up a new best practice

Cc @pytest-dev/core

**Comment by Zac-HD** [comment]
I'm `+0` on changing our default branch, because there's a lot of tooling and many tutorials that assume the default branch name is `master`.  So while it would definitely be good for some, it would also make life a bit more difficult for new contributors.

On the other hand, there are still places where `slave` appears in Pytest and some of our first-party plugins; and that seems a lot worse to me - and has fewer downsides to fixing it.  So my proposal is to:

- note our in-principle support for a new default branch name
- change the default branch name when a standard alternative to `master` has appeared
- prioritize the removal of "slave" in all existing pytest code and docs across our organisation  
  (i.e. `git grep slave` should not return any results outside old changelog entries)

**Comment by RonnyPfannschmidt** [comment]
@zac-hd thanks for the input

I like your proposal to immediately sort the details in our own code and deferring the git setup until a broad consensus emerged from the broader community

**Comment by symonk** [comment]
Hi @RonnyPfannschmidt happy to help if you want to share a compiled list of areas that could use some changes

**Comment by Zac-HD** [comment]
@symonk - https://github.com/search?q=user%3Apytest-dev+slave&type=Code has some results - when I have a few hours my plan is to clone one of the plugin repos, `git grep slave`, and either delete each instance or replace it with `worker` (as we did in `pytest-xdist` several years ago).

Where it's already deprecated in favor of `worker`, as in `pytest-xdist`, IMO this is a good time to finish that process by removing the compatibility attributes.

I also want to be careful about drafting the changelogs, so that we clearly express (a) our support for diversity, (b) that this is not a new move for our project - rather finishing a years-long process, and (c) exactly what the technical impact will be (hopefully very small).

**Comment by RonnyPfannschmidt** [comment]
I'd be delighted to see that come down, im currently with family and might not get to it until the weekend

**Comment by symonk** [comment]
I guess this is quite problematic in the sense that some references are function args, any downstream code calling such functions by keyword= would break (in the instance of pytest-services from the link above)

**Comment by RonnyPfannschmidt** [comment]
@symonk indeed, a first step is to triage the occurrences into trivial, needing some work and  needing a migration+break later

**Comment by Zac-HD** [comment]
I think we have consensus *against* changing our default branch name at this time, and *for* removing "slave" references from our actual code.

I therefore suggest that we close this issue in favor of https://github.com/pytest-dev/pytest-xdist/pull/541, which is tracking all the plugin changes - at this point the patches have all been written, it's just a matter of merging them and releasing the corresponding new versions!

**Comment by RonnyPfannschmidt** [comment]
thanks, closing this one as sorted

i suspect we will revisit the main branch name in near future as there seems to be a emerging consensus of the branch name main
i plan to touch this after reviewing some early adopters/migrators
