### ISSUE TITLE
[RFC]: Defining parameters for ( and marking ) good first issues

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest#7353]
Hi everyone. Another documentation based question/suggestion/discussion here.

I noticed we don't have the label 'good first issue' in our labels list ( we do have 'status: easy' which appears to be equivalent from the description ) and we also don't have any guidance in our documentation on how to determine what would constitute a good first issue.

Do we feel like it would be a good idea to (a) change the 'status: easy' label to 'good first issue' and/or introduce a 'good first issue' label, and (b) provide guidance on what would constitute an issue worthy of that label in our documentation. I ask since I feel like it would make pytest more welcoming to newcomers ( not that it isn't extremely welcoming already ), GitHub is now helping users discover issues labelled 'good first issue' more easily, and  'good first issue' seems to have become the open source standard.

![Screen Shot 2020-06-11 at 9 53 43 PM](https://user-images.githubusercontent.com/13026015/84456528-2a842d80-ac2e-11ea-8117-03cebf28d2e0.png)

cc @bluetech @nicoddemus @RonnyPfannschmidt to get the discussion started

**Comment by Zac-HD** [comment]
I've renamed our `status: easy` label to `good first issue`, so we get all the nice UI integrations.

Documentation of what might count would be nice, but I think our status quo of "a maintainer thinks that it would be an easy / good first issue" is OK for now.  Happy to take a PR with some docs, but closing this issue since it's been inactive for so long.
