### ISSUE TITLE
Dynamic test suites

### ISSUE THREAD

**Issue by mciepluc** [pytest-dev/pytest#7404]
Hello pytesters!

I am wondering if it is possible to create a dynamic test suites. Let's tart with a simplest example - I have a single parameterized test that I run several times with randomized parameterization. This test outputs some data, and based on this data (that is incoming dynamically after each run finished) I may want to:
- decide to run this test more times,
- impact further parameterization (e.g. by constraining randomization),
- run different test.

I am wondering if it is possible to do it. Thanks for help!

**Comment by SalmonMode** [comment]
This comes up occasionally, and isn't possible yet. But I always recommend against it anyway.

Ideally, tests are repeatable, and the steps and data they use are apparent just from reading them. Randomized inputs can easily make tests nondeterministic, or have no actual impact on what behavior is being testing. In the latter case, it renders parameterization based off of randomized sets moot, since no new behavior is being testing on top of them not being easily repeatable (so it's kind of a double whammy).

This doesn't mean randomized input is inherently bad, for example, I randomized emails for my generated users to ensure they're unique. But if it changes the behavior under test, then you're better off making sure each set of data that would trigger different behavior is built in so it can always be run.

But I find in general that if all the tests are defined up front, things become much easier in pytest and similar frameworks.

Ideally, tests shouldn't be run based off of other tests, either, as it means confounding variables are being introduced since the tests aren't being engineered solely around the behavior you want them to test as they're being made to have unnecessary dependencies. If tests aren't dependent on things they don't fundamentally need to be, then there's less things involved that could be borked and cause your tests to error out before actually being able to perform the test, which means you get a clearer picture of all the things that are broken, sooner.

Sometimes, in more complex systems/tests (e.g. e2e tests), you may have dependencies that you just can't mock because you have to engage with those systems to prepare for the test (e.g. using the backend's API to generate a user to log in as). This can usually be taken advantage of, though, to "kill" tests early by relying on simple validation that you would have built into your tools anyway. For example, I make an API client to abstract how I deal with my backend's API, and in its methods, it parses the response, often into custom data types. So if I try to log in through that client, if the response isn't good or even parsable, an error would get thrown, causing the test to error out early, saving a _ton_ of time (and I also get a convenient error message telling me it failed to log in so I don't have to go digging around to find the cause). If I have several tests that need to log in through the API to work, they'll all error out very quickly, so it's effectively the same as not running those tests if the test that checks logging in works had failed (the run time of the test suite would have a more or less negligible difference between these two cases).

That said, you may be looking to do something called "property-based testing". In which case, I recommend [Hypothesis](https://hypothesis.readthedocs.io/en/latest/index.html).

If you provide some more context, I'd be happy to help come up with a more complete solution (provided Hypothesis wasn't what you were looking for). 😁

**Comment by mciepluc** [comment]
I come from semiconductor industry, where random testing has solid fundamentals.
Widely used is so-called random metrics-driven verification. The basics are pretty simple - test scenarios are randomized (but repeatable - randomization depends on randomization *seed*), and the test completion results in coverage. Because designs-under-verification are complex "black-boxes" with no internal observability, it is difficult to know the relation between stimulus and the coverage (I believe it is pretty close to what you call e2e testing).
Therefore test suites are build of repeatable randomized tests. If you see a failure in a particular run - you can easily repeat it because you know the *seed*. But to ensure the coverage goal - tests need to be run many times. 
Thanks for property-based-testing note, this approach is also widely used in ICs, but it is not the solution I am looking for :)

**Comment by SalmonMode** [comment]
I'm currently reading through [the paper you published on it last year](https://link.springer.com/article/10.1007/s10836-019-05777-0) to get a better idea of the testing methodology. 

In section 4 of the paper, you mention segments and checkpoints, and the "INIT". Is the INIT effectively the result of each call of the test suite? As in this is where the seed is generated and the structure of the test suite is determined?

**Comment by mciepluc** [comment]
Thank you for the attention my paper got from your side :)
Concepts presested there are however quite advanced - for sure it would be a nice final goal, but I suggest to start from something easier. 
"INIT" is an example test scenario (segment) such as "Sx". Do not pay attention to the checkpoints at the moment - they can be easily interpreted as one of the test input parameters, but unknown at the session start phase. They will be comming gradually as the test suite execution is progressing. 
Regarding seeds manipulation I see it this way. Each standalone test run (corresponding to the "test segment" according to the paper) is called with input parameters (that may include constraints, test data and checkpoint) and seed. When test is finished, test suite automation functionality makes decision about scheduling another test and generates parameters for it. Does it make sense? Note that each test segment is easily reproducable, because we know the parameters and seed that were used to run it.

**Comment by mciepluc** [comment]
BTW, a simple example of the proposed flow is here: https://github.com/mciepluc/apbi2c_cocotb_example/blob/master/tb/test_i2c.py
It does not use pytest, test segments are simple functions (```def segment_xxx()```) called dynamically. The testing is completed when a given coverage level have been exceeded. This example is also described in the paper.

**Comment by RonnyPfannschmidt** [comment]
i beleive hypothesis does something similar, but there is not yet a deep integration between pytest and such dynamic tooling (so its "tricky")

**Comment by mciepluc** [comment]
I am thinking about possible workarounds that would not require additional pytest functionality, a few of question that I have in mind that my help me:
- is it possible to discover the tests "gradually"? I understand that all tests are discovered at the very beginning, before any of them is running. Is there any way to impact this behavior?
- is it possible to skip (or to break) the test that is already running, or is scheduled?
- can I parametrize test by a dynamic object, which is not yet build at the test discovery stage, so the test simply (during execution) waits until this object is built?

**Comment by RonnyPfannschmidt** [comment]
Gradual discovery was abandoned to sort out setup /teardown reordering

There is no built-in way to break the current test, you'd have to make one matching your framework

 Parameterisation can be done with symbolic /standin values and the fixtures creating the objects will have to do the rest

**Comment by Zac-HD** [comment]
> I believe Hypothesis does something similar, but there is not yet a deep integration between pytest and such dynamic tooling (so its "tricky")

The exact workflow described is out of scope even for Hypothesis - I'm working on a "fuzzing mode" which will keep running tests and prioritize whichever is most likely to cover new branches, but that's a completely different runtime environment to pytest-style "run these tests and then stop".

So your best option for the workflow you've described is to implement it *inside* a test function, so that you're responsible for the details and pytest just calls the wrapper function.
