### ISSUE TITLE
codecov does not properly check assertion disabled cases on diffs 

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest#7407]
building off of https://github.com/pytest-dev/pytest/pull/7396

`codecov` it would seem that codecov does not properly check assertion disabled cases on diffs, and as such under reports coverage.

We should investigate further

cc @RonnyPfannschmidt

**Comment by antonblr** [comment]
I think this is fixed by https://github.com/pytest-dev/pytest/pull/8188 - a non-covered [diff](https://codecov.io/gh/pytest-dev/pytest/compare/7450b6dd95aa4dfb9c64c2442a173ca65143b442...49ec2aed0f326fc5fa25dbdd7c47bf0a888dbd97/diff#) from original PR now shown as [covered](https://codecov.io/gh/pytest-dev/pytest/src/master/src/_pytest/config/__init__.py#L11510) after the fix.

**Comment by bluetech** [comment]
Let's close it then - better to ask for forgiveness than to ask for permission :)

**Comment by gnikonorov** [comment]
Yes please feel free to close! Sorry @antonblr and @bluetech for the delayed response
