### ISSUE TITLE
Since pytest 6.0.0, pylint complains about unimplemented abstract methods in custom collector

### ISSUE THREAD

**Issue by andy-maier** [pytest-dev/pytest#7591]
Hi, we have implemented a custom pytest collector that takes testcases from YAML files. Starting with pytest 6.0.0, pylint reports the following about that collector:

```
tests/functiontest/conftest.py:225:0: W0223: Method 'get_closest_marker' is abstract in class 'Node' but is not overridden (abstract-method)
tests/functiontest/conftest.py:225:0: W0223: Method 'gethookproxy' is abstract in class 'FSCollector' but is not overridden (abstract-method)
tests/functiontest/conftest.py:225:0: W0223: Method 'isinitpath' is abstract in class 'FSCollector' but is not overridden (abstract-method)
tests/functiontest/conftest.py:252:0: W0223: Method 'get_closest_marker' is abstract in class 'Node' but is not overridden (abstract-method)
```
The collector has worked fine for a long time, and it still works fine.

The line pylint reports this on is the class definition of a collector class that is based on pytest.File:

```
class YamlFile(pytest.File):

    def collect(self):  # The only method in this class
        . . . 
```
The whole source code is here: https://github.com/pywbem/pywbem/blob/master/tests/functiontest/conftest.py#L225

Versions:

Python 3.8.0 (default, Oct 15 2019, 17:49:23). This happens on all Python 3.x versions we used pytest 6.0.1 with (3.5, 3.6, 3.7, 3.8), on macOS and Ubuntu.

pylint 2.4.4
astroid 2.3.3

platform linux -- Python 3.8.0, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
plugins: cov-2.10.0, yagot-0.5.0, requests-mock-1.8.0

Please let me know in case a collector has to implement these methods.

**Comment by bluetech** [comment]
None of these methods are abstract (as in `abc.abstractmethod`) which led to some head scratching, but it seems that pylint considers any method which raises `NotImplementedError` to be abstract.

`get_closest_marker` is only marked such because we use `raise NotImplementedError()` in `@overload`ed functions. Given how pylint treats these, we can change these to just use `pass  # pragma: no cover` instead. Though ideally pylint would learn to ignore the contents of functions decorated with `@overload`.

As for `gethookproxy` and `isinitpath`, they really are abstract in the sense that the `_collectfile()` function provided by `FSCollector` assumes they have been implemented. In the case of your `YamlFile` collector, you don't use `_collectfile` so it ends up not mattering. I suppose it is a less than ideal subclassing design. The `NotImplemented` were added in pytest 6.0.0 by commit be00e12d47c820f0a90d24cd76ada8a0366c5a67 which fixed some internal typing issues.

I will take a look at resolving this when I get the chance. However we may want to add a quick fix for pytest 6.0.x at least.
