### ISSUE TITLE
[docs][404] "Not found" setup

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest#7596]
I navigated to https://pytest.org/latest/capture.html#capturing-of-the-stdout-stderr-output from somebody else's notes on the Internet.
I understand that it's a "404 Not Found" page but it looks broken.

It's probably minor but I think the styles and pictures should be fixed at least. Ideally, some redirects would be useful too.

**Comment by symonk** [comment]
Thanks for reporting @webknjaz

**Comment by nicoddemus** [comment]
In this case I'm not sure there's much we can do, the proper URL is https://pytest.org/en/latest/capture.html#capturing-of-the-stdout-stderr-output (note `/en`), and has always been like this since I've known the project. Probably the source where you got this was incorrect?

Closing this for now, but thanks anyway @webknjaz for the report!

**Comment by webknjaz** [comment]
Well, my point is that setup of the page 404 could be improved. This probably requires some fix for the Sphinx Jinja2 templates.

**Comment by nicoddemus** [comment]
> Well, my point is that setup of the page 404 could be improved. This probably requires some fix for the Sphinx Jinja2 templates.

Ahh indeed I missed that, thanks!

**Comment by mcsitter** [comment]
I would happily pick this up! I also came across links with broken pages in the past for example on #1477 in which i also noted the missing `en` in the link. There are other examples as well!

Sadly I have no idea how to tackle this. The only thing i know is that the `404.html` created from the tox test renders as expected.
The browser console reports that on the linked broken pages the imports from `https://pytest.org/latest/_static` don't work. This makes sense to me, since that folder does not exist relative to links outside of `/en.`

There is a reference to a javascript file in the `template.html` in the `_templates` directory. `_static/version_warning_offset.js` of course also fails to import on the broken pages. In the `layout.html` template a `basic` directory is referenced, which I cannot find. Where do I start?

**Comment by webknjaz** [comment]
@mcsitter normally, base Jinja templates are part of the theme that is pip-installed. Try looking it up.

**Comment by webknjaz** [comment]
This is the theme used: https://github.com/pallets/pallets-sphinx-themes/tree/master/src/pallets_sphinx_themes/themes/flask. That in turn inherits https://github.com/pallets/pallets-sphinx-themes/tree/master/src/pallets_sphinx_themes/themes/pocoo.

And so here it is: https://github.com/pallets/pallets-sphinx-themes/blob/master/src/pallets_sphinx_themes/themes/pocoo/static/version_warning_offset.js.

You could contribute upstream as a long-term fist, but short-term you could copy that file into this repo and make the changes. This would override that file.

**Comment by mcsitter** [comment]
I had a look into this. Thank you for pointing me there! I was only familiar with the django template language, so this was useful. Hoewever putting full urls into the links for css and js in the head of the html seems clunky, complicated and unflexible. Since the styling is also served on the same domain.

The issue is not the html i believe. It is that people land on pages with broken links, where they expect a certain part of the documentation to be, which might even exist, just under a slightly different urls. I think the docs are server with readthedocs or at least [pytest.readthedocs.io](https://pytest.readthedocs.io) redirects to the docs. RTD actually supports redirects exactly for our use case:
> You can now set a Prefix Redirect that will redirect all 404’s with a prefix to a new place.

Implementing a redirect is really easy. The functionality and the described use case apply to our issue here, so we should use tool provided. [How to implement user defined prefix redirects.](https://docs.readthedocs.io/en/stable/user-defined-redirects.html#prefix-redirects).

Here is what it looks like in the configuration page (in german. Couldn't find how to change the language):
![grafik](https://user-images.githubusercontent.com/48606431/90006207-be0ec480-dc98-11ea-88bf-ae0adc1fd504.png)

As you can see it does exactly what we want!

**Comment by mcsitter** [comment]
Maybe someone who has the permissions to make this change in the configuration could chime in and give feedback on this? I do not know who to mention.

**Comment by webknjaz** [comment]
that would be @nicoddemus or somebody else from @pytest-dev/Core

**Comment by nicoddemus** [comment]
Thanks @webknjaz and @mcsitter!

I've configured like you asked:

![image](https://user-images.githubusercontent.com/1085180/94214423-e7358e00-feaf-11ea-8770-aa7973a97205.png)

It worked for me accessing and old URL like: https://pytest.org/latest/fixture.html#fixtures

Can you confirm yourselves?

**Comment by mcsitter** [comment]
Both links mentioned in this issue as well as the link in the issue i mentioned above work for me. Awesome!

**Comment by webknjaz** [comment]
Resolved!

**Comment by nicoddemus** [comment]
Thanks folks!
