### ISSUE TITLE
How to get input variable from another script while running pytest for SeleniumBase in Python?

### ISSUE THREAD

**Issue by bsmith4133** [pytest-dev/pytest#7654]
The file I upload to a website changes with each run, and I'd like a way to change it in test method. Currently, I have it set up like this:
## functions.py
```
def get_file():
    ...
    file = file_ex1.doc
    return file

def run_test1():
    cmd = "pytest -v webtests.py::EF --browser=chrome"
    subprocess.run(split(cmd))  # run command line
...
```

## webtests.py
```
file_path = file  # changes with each run, should come from get_file()

class EF(BaseCase):
    def test_now(self):
        self.open('https://www...')
        self.find_element('input[name="Query"]').send_keys(file_path)`

```
I was wondering about the best way to change the `file_path` variable based on the output of certain functions in `functions.py`. For example, it could sometimes produce a file called file1 to upload, or another time filet2.txt. What's the best way to connect the two scripts and run `test_now()` with the updated file path each run? Or is there a better way to set this up?

Thanks so much in advance.

**Comment by RonnyPfannschmidt** [comment]
the pytest-native way would be to declare a command-line option and a fixture that allows to pass that option to the test
as far as i can tell SeleniumBase uses unittest, so in order to make that work one needs a class level autouse fixture that puts the value onto self, as unittest tests do not work with fixtures natively
