### ISSUE TITLE
Complete move to GitHub

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#769]
- [x] Ask submitters to re-create PRs at the new repository;
- [x] Update all links in the documentation and PyPI;
- [x] Update "how to contribute" docs;
- [x] Upload new docs to pytest.org;
- [x] Send an email to all relevant mailing lists about the migration;
- [x] Close BitBucket issues and post a link to the issue at GitHub;

**Comment by blueyed** [comment]
Thanks! :octocat:

**Comment by The-Compiler** [comment]
Thank you for all your work, @nicoddemus! :+1:

I have one small feature request: What about making @pytestbot migrate existing PR comments from BitBucket (via the normal API rather than the migration API)?

This is something which would have to be done manually for each PR after the author recreated it here. It'd be nice to have everything in one place, even when the original PR is linked.

If you feel like it's not worth the effort I understand - just thought I'd throw out the idea.

**Comment by nicoddemus** [comment]
Hey @The-Compiler,

Do you mean porting all PR (even closed ones) or just those still open and being reviewed? 

For the first case we would have to re-create all PRs, but PRs must be created from forks from specific users so that does not seem feasible to do.

If you mean porting the comments from open PRs only, it would be possible after the PRs are re-opened here on GitHub by the original submitter (see #776), but as those are few in numbers I'm not sure it would be worth the effort...

Thanks for the feedback! :smile:

**Comment by The-Compiler** [comment]
The second - yeah, I'm also not sure - probably it's not indeed.

I also noticed @pytestbot links to github users even when they don't exist - but I guess editing the comments now to fix that isn't easy, so I guess let's leave it as-is.

**Comment by hpk42** [comment]
FWIW i wouldn't bother porting the PRs.  I also noticed that the github user links are given too definitively but that's how it is now. people will cope i guess.
