### ISSUE TITLE
Documentation: post-process test reports shows incorrect usage of get_result()

### ISSUE THREAD

**Issue by ExaltedBagel** [pytest-dev/pytest#7788]
The official documentation uses outcome.get_result() without try/except to handle the case where an uncaught exception happened. Since get_result() was made to rethrow exception info, it should be shown how to handle such cases in the example.

[Official Example](https://docs.pytest.org/en/latest/example/simple.html#post-process-test-reports-failures)

**Comment by nicoddemus** [comment]
Hi @ExaltedBagel, 

IIUC that doesn't apply there: in that hook we want to obtain the `TestReport` instance generated by the `pytest_runtest_makereport`. If that call has raised an exception somehow, it is probably best to let it propagate up anyway because it is an internal error. 

If you think I'm misunderstanding, can you provide a quick example in code of what you mean?

Thanks!

**Comment by ExaltedBagel** [comment]
Alright, this makes perfect sense to me, thanks. Should we close this issue?

**Comment by nicoddemus** [comment]
Sure, thanks!
