### ISSUE TITLE
_pytest.pytester.Testdir missing in objects.inv

### ISSUE THREAD

**Issue by PhilippSelenium** [pytest-dev/pytest#7892]
I don't know if this was by choice or by accident but the documentation for _pytest.pytester.Testdir is missing in the intersphinx file:

```
python3 -m sphinx.ext.intersphinx https://docs.pytest.org/en/latest/objects.inv | grep Testdir
```

pytest version: 6.1.1

**Comment by nicoddemus** [comment]
Hi @PhilippSelenium,

That's due to https://github.com/pytest-dev/pytest/pull/7854: we introduced `Pytester`, and because `Testdir` and `Pytester` both have the same interface, we decided to show the members of `Pytester` in the docs only: https://docs.pytest.org/en/latest/reference.html#pytest.pytester.Pytester. 

However thinking about this a bit more I'm not sure this is ideal: `Pytester` now will tend to gain extra functionality which we don't plan to backport to `Testdir` (I think at least), so we really should show members of both classes in the docs.

Also notice that your link points to the "latest" docs, which are actually `master`, for version 6.1.1 you should use https://docs.pytest.org/en/stable/objects.inv instead, which still contain the intersphinx docs for `Testdir`.

**Comment by PhilippSelenium** [comment]
@nicoddemus Thanks for the hint. I should use stable.
