### ISSUE TITLE
error: unrecognized arguments: -n

### ISSUE THREAD

**Issue by saurabhkdhiman** [pytest-dev/pytest#7943]
I have a hello.py file which includes 

```python
import xdist

def execute_program:
    pytest.main(args=arg, plugins=[xdist])

if __name__ == '__main__':
    commands_list = [ 'test_dir', '-n', '5']
    execute_program(commands_list)
```

When I am running this file using python hello.py, I am getting following error: 

```
> ERROR: usage: run_test.py [options] [file_or_dir] [file_or_dir] [...]
> run_test.py: error: unrecognized arguments: -n 2
>   inifile: C:\Users\saura\Documents\Latest\unifiedclient\automation\pytest.ini
>   rootdir: C:\Users\saura\Documents\Latest\unifiedclient\automation
```

Packages:

```
Pip list:
apipkg          1.5
atomicwrites    1.4.0
attrs           20.2.0
certifi         2020.6.20
chardet         3.0.4
colorama        0.4.4
execnet         1.7.1
idna            2.10
iniconfig       1.1.1
numpy           1.19.2
packaging       20.4
pandas          1.1.3
pip             20.2.4
pluggy          0.13.1
py              1.9.0
pyparsing       2.4.7
pytest          6.1.1
pytest-forked   1.3.0
pytest-html     2.1.1
pytest-metadata 1.10.0
pytest-xdist    2.1.0
python-dateutil 2.8.1
pytz            2020.1
requests        2.24.0
rstr            2.2.6
setuptools      49.2.1
six             1.15.0
toml            0.10.1
urllib3         1.25.11
```

Pytest & Os:

```
pytest 6.1.1, OS Windows 10
Python - 3.8.6
```

**Comment by symonk** [comment]
Hello, @saurabhkdhiman as a first thing, your function:

```python
def execute_program:
    pytest.main(args=arg, plugins=[xdist])
```

takes no args, perhaps start with:

```python
def execute_program(commands):
    # now resolve these args correctly
    pytest.main(args=arg, plugins=[xdist])
```

**Comment by saurabhkdhiman** [comment]
@symonk Thanks for quick reply. 
I have executed it without specifying plugins( pytest.main(YOUR_ARGS_HERE)) and it worked fine but when I created package of this .py file using pyinstaller and executed this .exe file, I am getting same error:

ERROR: usage: run_test.exe [options] [file_or_dir] [file_or_dir] [...]
hello.exe: error: unrecognized arguments: --html=report.html -n 2
  inifile: C:\Users\saura\Documents\Latest\unifiedclient\automation\pytest.ini
  rootdir: C:\Users\saura\Documents\Latest\unifiedclient\automation


Pytest.ini file content:
[pytest]
log_cli = True
addopts = -v -s --html=report.html

**Comment by RonnyPfannschmidt** [comment]
Under pyinstaller xdist does not work for technical reasons (pyinstaller breaks things)

**Comment by symonk** [comment]
Good to know @RonnyPfannschmidt thanks for the info

**Comment by symonk** [comment]
@saurabhkdhiman can we close this issue based on Ronnys feedback?

**Comment by saurabhkdhiman** [comment]
@symonk can I get a fix OR any solution for this?

**Comment by nicoddemus** [comment]
@saurabhkdhiman unfortunately there's no easy fix, pytest-xdist and any freeze method (pyinstaller, cx_freeze, etc) are not really compatible.

These are the problems:

1. On those environments setuptools entry points are not processed (so xdist, and any other plugins, are not loaded).
2. pytest-xdist in particular spawns other python processes using `sys.executable -c`, executing `xdist.remote` as source code passed as argument. This is a problem because a) your executable needs to understand `-c` and execute the code given, and b) pytest-dist uses `inspect.getsource` to obtain the source code of `xdist.remote`, and that does not work in a frozen environment.

So there are a number of problems that need to be overcome, which can't really be fixed by xdist or the frozen environments directly. It is not impossible, I've managed to do it at work but only in a very custom workflow that's not really shareable, but it is pretty complex.

**Comment by nicoddemus** [comment]
Closing for now.
