### ISSUE TITLE
Implement soft asserts with pytest

### ISSUE THREAD

**Issue by jigree** [pytest-dev/pytest#8027]
If I understand correctly, at this point pytest only has hard asserts i.e. if I have a test with more than one assert statements, if first assert fails, it halts the test and doesn't proceed. 
Although hard asserts are great and helpful with unit testing, soft asserts will be a very helpful addition to pytest.
There are ways to simulate them for e.g. by try/except AssertionError and logging failures manually and failing the whole test in the end with Assert False by keeping track of success/failures but it doesn't let us utilize automated reporting and highlighting of failures appropriately.

Requesting you to please consider this feature request. Thank  you !

**Comment by The-Compiler** [comment]
This won't be possible using the normal `assert` statement, because that triggers a Python exception on failure (well, unless pytest did more crazy rewriting, but I doubt this is a good idea).

There are plugins which allow for doing this with an alternative syntax, such as [pytest-check](https://github.com/okken/pytest-check). FWIW I'm -1 on having something like this in the core.

**Comment by nicoddemus** [comment]
Agree with @The-Compiler. 😁 

Closing this for now, but feel free to follow up with further questions.
