### ISSUE TITLE
add deselected test case list option

### ISSUE THREAD

**Issue by Aytikin** [pytest-dev/pytest#8034]
#### What's the problem this feature will solve?

I have encountered problem on tracking what test cases that are deselected among more than one thousand of test cases with given marker.  it will be easily missed if we don't have this list checked from time to time if we have large amount of test cases and contributor. 

#### Describe the solution you'd like

an option (--collect-only-deselected) similar to --collect-only, but collect only deselected ones.

We have different platforms that uses same framework.
if one developer developed a test case in one platform A, and that is potentially applicable for another platform B.  This test case is deselected for platform B only due to marker.platform_A on this test case. We might be able to detect this and possibly adapt this for platform_B as well.

#### Alternative Solutions

No, only manually search..

**Comment by nicoddemus** [comment]
Hi @Aytikin,

Thanks for the suggestion.  

However I believe this option is a bit exotic to be implemented directly into the core.

As a suggestion, you can implement [`pytest_deselected`](https://docs.pytest.org/en/latest/reference.html#pytest.hookspec.pytest_deselected) into your root conftest file to keep track of deselected items. With that you have even more power, because you might save that information to an easy to parse file (like JSON) with all the information you need.

Closing this for now, feel free to follow up with further questions.
