### ISSUE TITLE
Fixture execution order 

### ISSUE THREAD

**Issue by kracekumar** [pytest-dev/pytest#805]
```python

import pytest


class Meh(object):
    @pytest.fixture(autouse=True)
    def a(self, request):
        print("meh")


class Foo(object):
    @pytest.fixture(autouse=True)
    def b(self):
        print("foo")


class Bar(object):
    @pytest.fixture(autouse=True)
    def c(self):
        print("bar")


class TestBaz(Meh, Bar, Foo):
    @pytest.fixture(autouse=True)
    def d(self):
        print("baz")

    def test_1(self):
        assert 1 == 1


class Meh1(object):
    @pytest.fixture(autouse=True)
    def foo(self, request):
        print("meh")


class Foo1(object):
    @pytest.fixture(autouse=True)
    def one(self):
        print("foo")


class Bar1(object):
    @pytest.fixture(autouse=True)
    def two(self):
        print("bar")


class TestBaz1(Meh1, Bar1, Foo1):
    @pytest.fixture(autouse=True)
    def three(self):
        print("baz")

    def test_1(self):
        assert 1 == 1

```

#### Output

```shell
(score)➜  score git:(master) ✗ py.test -s -v tests/integration_tests/test_test.py --pdb
============================================================================================================================= test session starts ==============================================================================================================================
platform darwin -- Python 2.7.6 -- py-1.4.27 -- pytest-2.7.0 -- /Users/krace/.virtualenvs/score/bin/python
rootdir: /Users/krace/code/score, inifile:
collected 2 items

tests/integration_tests/test_test.py::TestBaz::test_1 meh
foo
bar
baz
PASSED
tests/integration_tests/test_test.py::TestBaz1::test_1 meh
foo
baz
bar
PASSED

=========================================================================================================================== 2 passed in 0.03 seconds ===========================================================================================================================
```

I am using multiple classes with mixin approach to write test cases. Fixtures are executed alphabetically, not in the order.

I am expecting the fixtures to be run in `Meh1 -> Foo1 -> Bar1 -> TestBaz1`. Adding `scope=class` doesn't help. What am I doing wrong ?

**Comment by nicoddemus** [comment]
pytest currently doesn't try to take in account subclasses when executing fixtures. 

One way to "enforce" one fixture to execute before the other is to make each fixture depend on a fixture of its subclass, for example make `b` fixture receive a `a` argument, or use `pytest.mark.usefixtures`.

One of the design goals for fixtures is [modularity](https://pytest.org/latest/fixture.html#modularity-using-fixtures-from-a-fixture-function), so that fixtures can be used in different contexts without test functions knowing about them. An advantage of this is that fixtures can easily be defined at a module first and then later, when proven useful to be used in other tests/modules, moved to a `conftest` easily without changing tests themselves.

**Comment by kracekumar** [comment]
Thanks. If it makes sense can we explicit add subclassing fixtures won't work in  `FAQ` ?

**Comment by nicoddemus** [comment]
Sure, good idea. Could you open a PR? :smile:

**Comment by kracekumar** [comment]
Yes, I will do it.
