### ISSUE TITLE
Module fixture runs before session fixtures if redefined

### ISSUE THREAD

**Issue by voronind** [pytest-dev/pytest#8074]
If we have session fixture `customer` and redefine it with module scope, It can run after module fixtures.

`tests/conftest.py`
```python
import pytest

@pytest.fixture(scope='session')
def customer():
    return 1

@pytest.fixture(scope='module')
def module_transaction():
    yield
```

`tests/test_1.py`
```python
import pytest

@pytest.fixture(scope='module')
def customer(customer):
    return customer + 1

def test_1(module_transaction, customer):
    assert customer == 2
```

```console
$ pytest tests --setup-only
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/voronin/projects/sintez_addons, configfile: setup.cfg
collected 1 item                                                               

test-module/test_1.py 
    SETUP    M module_transaction
SETUP    S customer
    SETUP    M customer (fixtures used: customer)
        tests/test_1.py::test_1 (fixtures used: customer, module_transaction)
    TEARDOWN M customer
    TEARDOWN M module_transaction
TEARDOWN S customer

============================ no tests ran in 0.01s =============================
```

**Comment by voronind** [comment]
Related #5303

**Comment by asottile** [comment]
this output seems correct to me, the scope of a fixture doesn't always indicate its ordering as they are only instantiated _as needed_.  the scope of the fixture determines the lifetime of the fixture -- not the setup order

based on the parameters of your test, the first argument's fixture gets set up first

in your case you have a few choices if you want to force the ordering -- one is to reorder the parameters of your test such that `customer` is first -- another is to set `autouse=True` on your session fixture so it is always set up

**Comment by voronind** [comment]
Documentation says that scope is about ordering. https://docs.pytest.org/en/stable/fixture.html#order-higher-scoped-fixtures-are-instantiated-first
In my case `module_transaction` is `autouse` and I can not reorder.

**Comment by voronind** [comment]
If we define `customer2` fixture we got other fixture lifetime.

`tests/test_1.py`
```python
import pytest

@pytest.fixture(scope='module')
def customer2(customer):
    return customer + 1

def test_1(module_transaction, customer2):
    assert customer2 == 2
```

```console
$ pytest tests --setup-only
Loading .env environment variables...
============================= test session starts ==============================
platform linux2 -- Python 2.7.15rc1, pytest-4.6.11, py-1.8.0, pluggy-0.13.0
rootdir: /home/voronin/projects/sintez_addons, inifile: setup.cfg
plugins: cov-2.10.0, flake8-1.0.4, forked-1.1.3, xdist-1.31.0
collected 1 item                                                               

tests/test_1.py 
SETUP    S customer
    SETUP    M module_transaction
    SETUP    M customer2 (fixtures used: customer)
        test-module/test_1.py::test_1 (fixtures used: customer, customer2, module_transaction)
    TEARDOWN M customer2
    TEARDOWN M module_transaction
TEARDOWN S customer

========================= no tests ran in 0.02 seconds =========================
```

**Comment by nicoddemus** [comment]
Hi @voronind, 

@asottile is correct, but your example is a bit different from the docs because your test is not requesting the `customer/session` fixture directly (as the documentation example shows), but indirectly through another fixture, `customer/module`, so that's the behavior we have currently. 

1. pytest determines it needs two fixtures to execute `test_1`: `module_transaction` and `costumer`, both module-scoped, so the order they will be created stays the same (if at that point we had a higher-scoped fixture, say "session", that would be created first);

2. It creates `module_transaction`; it doesn't have any dependencies so that's that.

3. It determines that `costumer/module` needs another fixture, `costumer/session`, so it instantiates it and passes it along to the `costumer/module` fixture function.

4. With the result of the two fixtures, `test_1` is executed with those parameters.

Currently we don't do a complete fixture resolution order before setting up things, but that's being discussed in https://github.com/pytest-dev/pytest/issues/4871.

Closing this for now. 👍
