### ISSUE TITLE
pytestmark vs pytest_marks

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#816]
Currently you can use `pytest_plugins` (accepts a single string or a list of strings) to explicitly define plugin dependencies in a module, and `pytestmark` to set one or more marks into all tests in a module or class. IMO it is unfortunate that they follow a completely different naming standard, as this has tripped me more than once.

I propose that we introduce `pytest_marks` with the exact same semantics and deprecate `pytestmark` in the documentation. 

Any thoughts?

**Comment by The-Compiler** [comment]
I've not been bitten by this yet as I never needed `pytest_plugins` so far - but I agree it makes sense to be consistent here.

I also agree that `pytest_foo` is better than `pytestfoo`. Should it be `marks` instead of `mark` though? It seems it takes a single `pytest.mark.*` object, not a list of them (like `pytest_marks` would imply IMHO).

**Comment by nicoddemus** [comment]
It seems to support also a list of marks:

```python
import pytest

pytestmark = [pytest.mark.x, pytest.mark.y]

def test_foo():
    pass

def test_bar():
    pass  
```

```bash
$ py.test -m "x and y" -v test_foo.py
============================= test session starts =============================
platform win32 -- Python 2.7.7 -- py-1.4.26 -- pytest-2.7.0 -- 
collected 2 items

test_foo.py::test_foo PASSED
test_foo.py::test_bar PASSED
```

**Comment by nicoddemus** [comment]
It was decided to let this aside for now, @hpk42 has some improvements to marks in general which warrant discussion and may affect this proposal.
