### ISSUE TITLE
Import strategy differs when folder name is a number

### ISSUE THREAD

**Issue by sguillia** [pytest-dev/pytest#8177]
Hi!

Minimal example: https://github.com/sguillia/pytest-bug-repro

Very simple to reproduce

```
git clone https://github.com/sguillia/pytest-bug-repro
cd pytest-bug-repro
pytest a/test/main.py
pytest 0/test/main.py
```

`a` and `0` have exactly the same layout and contents, why does `a` fail where `0` succeeds?

I would expect both test runs to fail.

<details>
<summary>System Info</summary>

```
pytest 6.2.1
Linux 4.15.0-123-generic #126~16.04.1-Ubuntu SMP Wed Oct 21 13:48:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

<details>
<summary>Repo Info</summary>

Tree of `a` and `0` in case the minimal example repo gets deleted

```
.
├── __init__.py
├── src
│   └── __init__.py
└── test
    ├── __init__.py
    ├── main.py
    └── print.py

2 directories, 5 files
```

All `__init__.py` are empty
`main.py` does `import src`

</details>

---

**Edit**

With respect to this doc: https://docs.pytest.org/en/stable/pythonpath.html

Perhaps `main.py` would be loaded as `0.test.main` which is not a valid module name, so pytest stops walking up the filesystem, as if there was no `__init__.py` in `0`.

If it's the case and this is intended behavior, feel free to close this issue. Perhaps you might want to mention invalid module names in that doc?

Thank you

**Comment by nicoddemus** [comment]
Hi @sguillia,

pytest imports test modules as Python modules, and those cannot start with `0`. This is similar to the issue discussed in https://github.com/pytest-dev/pytest/issues/8173.

You can try using `--importmode=importlib`, which unless there are other factors at play, should then work because it uses lower-level import mechanisms which bypass that restriction.
