### ISSUE TITLE
Subclassing/modifying Testdir/Pytester

### ISSUE THREAD

**Issue by aragilar** [pytest-dev/pytest#8210]
Hi All

It looks like the recent changes to Testdir make it much harder to override its methods (as it is no longer handling anything, instead deferring to Pytester). I've been overriding the runpytest_subprocess function to allow wrapping the call to pytest in MPI (see https://github.com/aragilar/pytest-mpi), which has been working fine so far. I can understand if subclassing is not something that can be relied on long term, but it would be useful to have some kind of hook which allows modifying what command is run when calling subprocess (e.g. to test running pytest with `mpirun`, or similar environmental changes such as `xvfb`).

**Comment by nicoddemus** [comment]
Hi @aragilar,

Thanks for writing!

Yeah, `Testdir` was never really meant to be subclassed by end users, so much we are marking all pytest classes as `@final` to discourage that. I understand it is a bit frustrating however to have existing code stop working due to an internal change.

Looking at the code in pytest-mpi (nice plugin btw), I see `MPITestdir` only subclasses `Testdir` to override `pytest_subprocess` (basically):

https://github.com/aragilar/pytest-mpi/blob/master/tests/conftest.py#L27-L49

In fact it even duplicates some of the logic in `runpytest_subprocess` (dealing with temp dirs and plugins for example). 

I believe a free function works just as well here, receiving a `testdir` instance:

```python
def runpytest_mpi(
    testdir, *args, timeout=60, mpi_procs=2, max_retries=5
):
    method = testdir.request.config.getoption("--runpytest")
    if method == "inprocess":
        log.warn("To run the MPI tests, you need to use subprocesses")

    retries = 0
    p = py.path.local.make_numbered_dir(
        prefix="runpytest-", keep=None, rootdir=testdir.tmpdir
    )
    args = ("--basetemp=%s" % p,) + args
    plugins = [x for x in testdir.plugins if isinstance(x, str)]
    if plugins:
        args = ("-p", plugins[0]) + args
    args = MPI_ARGS + (str(mpi_procs),) + testdir._getpytestargs() + args
    while retries < max_retries:
        try:
            return testdir.run(*args, timeout=timeout)
        except testdir.TimeoutExpired as e:
            retries += 1
            if retries >= max_retries:
                raise
    raise e
```

Except for `_getpytestargs()` (which can be replaced by `(sys.executable, "-mpytest")`), it uses only the public API, no subclassing required. This shields you from other changes we might do to (or even done in the past), for example adding new arguments to `__init__`.

Of course your tests would have to change to call:

```python
testdir.runpytest(...)
```

To:

```
runpytest_mpi(testdir, ...)
```

But given this is used internally I see this as reasonable, in face of the other benefits.

If we can come up with a nice and clean way to extend the arguments used by `Pytester.run()`, I would not be against it personally, but I'm not entirely sure it is really necessary.

Again, sorry we broke `pytest-mpi`! 😁
