### ISSUE TITLE
Use regendoc in fixture.rst

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#8213]
Add actual regendoc runs in `doc/en/fixture.rst`.

_Originally posted by @RonnyPfannschmidt in https://github.com/pytest-dev/pytest/pull/8207#discussion_r550469858_

**Comment by matthewhughes934** [comment]
Hi, I'd like to contribute here if I could. I had a go at adding a regendoc run for the code in question, but I don't think the `emaillib` package that it uses supports python3, see the [`tox` envlist for the package](https://github.com/costastf/emaillib/blob/master/tox.ini#L7). Relevant output from `make regen REGENDOC_FILES=fixture.rst`:

```
+.. code-block:: pytest
+
+   $ pytest -q test_module.py
+   
+   ================================== ERRORS ==================================
+   _____________________ ERROR collecting test_module.py ______________________
+   ImportError while importing test module '$REGENDOC_TMPDIR/test_module.py'.
+   Hint: make sure your test modules/packages have valid Python names.
+   Traceback:
+   $PYTHON_PREFIX/lib/python3.6/importlib/__init__.py:126: in import_module
+       return _bootstrap._gcd_import(name[level:], package, level)
+   test_module.py:3: in <module>
+       from emaillib import Email, MailAdminClient
+   $PYTHON_PREFIX/lib/python3.6/site-packages/emaillib/__init__.py:8: in <module>
+       from .emaillib import SmtpServer, EasySender, Message
+   $PYTHON_PREFIX/lib/python3.6/site-packages/emaillib/emaillib.py:10: in <module>
+       from email.MIMEMultipart import MIMEMultipart
+   E   ModuleNotFoundError: No module named 'email.MIMEMultipart'
+   ========================= short test summary info ==========================
+   ERROR test_module.py
+   !!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!
+   1 error in 0.12s
```

(Since python3 [it looks like](https://docs.python.org/3/library/email.mime.html?highlight=mimemultipart#email.mime.multipart.MIMEMultipart) `MIMEMultipart` has been moved to `email.mime.multipart`)

**Comment by RonnyPfannschmidt** [comment]
i believe that the emaillib package was never used to begin with,
as far as i remember the code in the docs is older than the module on pypi

**Comment by matthewhughes934** [comment]
> i believe that the emaillib package was never used to begin with,
> as far as i remember the code in the docs is older than the module on pypi

Ah right, yeah a quick search for `"MailAdminClient" python` seems to only bring me back to these docs, although it _appears_ (I may've missed something) references to `emaillib` were added in a single commit:

```
$ git log -G 'emaillib' --oneline 
534d174fd Clarify fixture execution order and provide visual aids (#7381)
```

**Comment by matthewhughes934** [comment]
What would be the preferred approach to addressing this issue? Assuming there's no an existing `emaillib` to use (though I'm assuming it's not desirable to add dependencies here) could make a stub library to satisfy these tests, e.g.

```rst
.. code-block:: python

    # content of emaillib.py
    class MailAdminClient:
        def create_user(self):
            return MailUser()

        def delete_user(self, user):
            # do some cleanup
            pass

    class MailUser:
        def __init__(self):
            self.inbox = []

        def send_email(self, email, other):
            other.inbox.append(email)

    class Email:
        def __init__(self, subject, body):
            self.body = body
            self.subject = subject
```

Otherwise with some creativity it should be possible to write tests in the same spirit based on something similar.

**Comment by nicoddemus** [comment]
Hi @matthewhughes934,

I think the stub library would be the easiest if possible. 👍
