### ISSUE TITLE
pytest_cmdline_main documentation - called from conftest

### ISSUE THREAD

**Issue by lhupfeldt** [pytest-dev/pytest#8287]
The documentation states that the `pytest_cmdline_main` hook is not called from conftest, but it is:
https://docs.pytest.org/en/stable/reference.html?highlight=pytest_cmdline_main#pytest.hookspec.pytest_cmdline_main

*conftest.py:*
```
def pytest_cmdline_main(config):
    print(f"Hello there! {config}")
```

*output:*
```
]$ pytest 
Hello there! <_pytest.config.Config object at 0x7fddb9355e80>
================================= test session starts =================================
platform linux -- Python 3.9.1, pytest-6.2.2, py-1.9.0, pluggy-0.13.1
...
```

**Comment by symonk** [comment]
This does in fact seem incorrect, need someone with more knowledge of the internals to comment, but a simple in process run shows me the following:

```console
plugin_name='C:\\Users\\Sy\\AppData\\Local\\Temp\\pytest-of-Sy\\pytest-11\\test_cmdline_main0\\conftest.py'
```

as part of the collected first-result only hooks, which leads me to believe `conftest.py` are infact, collected and hook implementations are considered for this given hook.  cc @nicoddemus any idea if intentional? I will open a PR to address the docs to assume that this hook does infact support conftest.py files (maybe it never used too?)

**Comment by nicoddemus** [comment]
Thanks @lhupfeldt for bringing this to attention, and @symonk for the PR!
