### ISSUE TITLE
how do I stop dependabot from pushing upgrades to my fork

### ISSUE THREAD

**Issue by asottile** [pytest-dev/pytest#8327]
🤔

**Comment by nicoddemus** [comment]
Yeah this has been bothering me as well... I remember giving this a quick search in the past, but didn't find a solution. I'm all ears if somebody finds one though.

**Comment by RonnyPfannschmidt** [comment]
yikes https://github.com/dependabot/dependabot-core/issues/2804
seems like drop and remake fork

**Comment by asottile** [comment]
"we'll get to it in a few months"

wow -- maybe we should roll our own periodic `pip freeze > ...` with github actions

**Comment by The-Compiler** [comment]
> wow -- maybe we should roll our own periodic `pip freeze > ...` with github actions

FWIW that's essentially what I ended up doing with qutebrowser: [readme](https://github.com/qutebrowser/qutebrowser/blob/master/misc/requirements/README.md), [script](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/dev/recompile_requirements.py) (rather long because of the changelog URLs, feel free to ignore those), [action](https://github.com/qutebrowser/qutebrowser/blob/master/.github/workflows/recompile-requirements.yml), [output](https://github.com/qutebrowser/qutebrowser/pull/6143).

I've also used [pyup.io](https://pyup.io/) and [requires.io](https://requires.io/) before, which seem nicer than Dependabot but sometimes were a bit unreliable (though it's entirely possible they work better nowadays).

**Comment by Zac-HD** [comment]
We've also rolled our own as [a GitHub Actions cron job](https://github.com/HypothesisWorks/hypothesis/blob/master/.github/workflows/update-deps.yml) for Hypothesis - `./build.sh upgrade-requirements` just runs [`pip-compile`](https://pypi.org/project/pip-tools/) for each of our requirements files, and then re-runs the autoformatters in case their output changed.

I'd strongly advise *against* pyup.io; the company is moribund at best ([HN comments](https://news.ycombinator.com/item?id=22499015), and the website was down when we went to disable the service) and it's incredibly noisy by default - after deleting the config file, the bot opened a separate PR for *every package individually*, and then *opened new PRs* when the first round was closed.

**Comment by Zac-HD** [comment]
Closing because I think our two options are

1. Wait for upstream, or
2. Roll our own GitHub Action

and nobody is leaping for (2) 😕

**Comment by nicoddemus** [comment]
Seems [there is a new option](https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-1220769377), [renovate](https://github.com/renovatebot/renovate).

We should migrate to use that, seems like it has the same functionality plus you can disable updates on forks.

**Comment by bluetech** [comment]
I think github fixed this issue
