### ISSUE TITLE
-c flag produces the wrong root dir

### ISSUE THREAD

**Issue by elbehery95** [pytest-dev/pytest#8464]
### Scenario tested

```
tests/
       test.py
pytest.ini
pytest2.ini
```

The contents of `test.py`

```py
from pathlib import Path

def test_root(pytestconfig):
    assert Path(pytestconfig.rootpath).resolve().absolute() == Path('.').resolve().absolute()

```
`pytest.ini` and `pytest2.ini` are the same

+ When running  `pytest tests/` the test is **passing** (correct rootdir is printed):  `rootdir: D:\pytest, configfile: pytest.ini`
+ When running `pytest tests/ -c pytest2.ini` the test is **failing** (wrong rootdir and config are reported) :  `rootdir: D:\pytest\tests, configfile: ..\pytest2.ini`

Please let me know if I can submit a fix for this :)

**Comment by parthdpa** [comment]
Was wondering if anyone is working on this and if someone found a cause for this? I am a first time contributor and looking to contribute for a final project for a class.

**Comment by nicoddemus** [comment]
Hi @elbehery95, 

Sorry for the delay, and thanks for the report!

We can reproduce this even without a second config file, we get the same behavior with these invocations:

* `pytest tests/`
* `pytest tests/ -c pytest.ini`

Of course the two runs should be identical.

The problem is in the `determine_setup` function:

https://github.com/pytest-dev/pytest/blob/41a90cd9fef26a5d7bcd89990dd0594b0d3f6a14/src/_pytest/config/findpaths.py#L166-L171

It should return the same results if `inifile` is `None` or `"pytest.ini"`, but currently it returns a different `rootdir` in the latter case.

This should be simple to fix, as you can easily unittest `determine_setup`.

> Was wondering if anyone is working on this and if someone found a cause for this?

Nobody seems to be working on this currently, feel free to tackle it. 👍

**Comment by elbehery95** [comment]
Thank you for the explanation I will submit a PR

**Comment by parthdpa** [comment]
Hello @elbehery95 ,
I was wondering if I could work on this and try to submit a PR as I am a new contributor and a requirement for a final project for a class I am taking?

**Comment by parthdpa** [comment]
@elbehery95 I thank you for considering my request. Much appreciated
