### ISSUE TITLE
Restrict GitHub Actions permissions

### ISSUE THREAD

**Issue by bluetech** [pytest-dev/pytest#8599]
There is now some functionality for restricting workflow permissions: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

Given the recent CodeCov trouble this sounds like a good idea.

I suggest we enable this setting for the repository, and specify needed permissions for specific workflow files. It might cause some failed runs initially but should be easily fixed.

Another thing we can do is to [specify](https://github.com/actions/checkout#usage) `persist-credentials` for the `actions/checkout` action when it's not needed.

**Comment by bluetech** [comment]
Status:

- Updated the permissions in main
- Stopped using tokens in secrets
- Backported to the stable branch
- Changed the repo settings to default read-only permissions

I suggest we wait until the next release and see if it works well, then delete the secrets from the repo and possibly revoke them.

I'll repoen to track this.

**Comment by RonnyPfannschmidt** [comment]
:+1: thanks !!

**Comment by The-Compiler** [comment]
@bluetech So from what I'm gathering, there's nothing left to do here before the next feature release, this is just to keep track if things work out fine during the release?

**Comment by bluetech** [comment]
Right, this is just for tracking. I hope these changes won't interrupt the release -- I think I covered everything, but if not, I'll try to follow the notifications and help.

**Comment by The-Compiler** [comment]
Well, looks like it did interrupt the release :sweat_smile: It [fails](https://github.com/pytest-dev/pytest/runs/2934644907?check_suite_focus=true#step:6:3551) with:

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/pytest-dev/pytest.git/'
Traceback (most recent call last):
  File "scripts/prepare-release-pr.py", line 152, in <module>
    main()
  File "scripts/prepare-release-pr.py", line 143, in main
    prepare_release_pr(
  File "scripts/prepare-release-pr.py", line 93, in prepare_release_pr
    run(
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'push', '***github.com/pytest-dev/pytest.git', 'HEAD:release-7.0.0rc1', '--force']' returned non-zero exit status 128.
```

I think we probably shouldn't be doing `persist-credentials: false` for `prepare-release-pr.yml`?

**Comment by The-Compiler** [comment]
Opening the PR worked now. Still keeping this open until we actually manage to get a release fully published.

**Comment by ssbarnea** [comment]
Not sure if that helps you but what I did in order to ensure tests do not have access to secrets is to remove the publishing from the testing pipeline and create a new pipeline named `release` that is triggered only on github release, one that is using the "release github environment". It is key to remove repository secrets and to move them to an environment.

One extra bonus on that is that this enables to add two more features:
* ability to request review of release from a list of people (pipeline would not run without it)
* ability to declare a delay the release (how long to wait before performing the release), like cooldown, which gives someone the opportunity to cancel if a mistake was made.

For practical example check https://github.com/ansible-community/ansible-lint/tree/master/.github/workflows --- where `tox` is the normal testing pipeline, and `release` is the special one.

**Comment by The-Compiler** [comment]
Releasing the rc1 worked without any further trouble, so I suppose we can close this?

**Comment by bluetech** [comment]
Yep, closing.
