### ISSUE TITLE
pytest_assertion_pass in functions

### ISSUE THREAD

**Issue by ric79** [pytest-dev/pytest#8864]
I'm using pytest==5.4.1

I defined the function as:
```python
def pytest_assertion_pass(item, lineno, orig, expl):
    LOGGER.info("asserting that {}, row:{}, {}, {}".format(item, lineno, orig, expl))
```

I added two asserts:
```python
# test_main.py
from utils import myfunct

def test_B0_0_000(self):
    assert 1==1, "OK"
    myfunct.prova()

# utils/myfunct.py:
import pytest
def prova():
   LOGGER.info("BEFORE")
   assert 2==2, "OK2"
   LOGGER.info("AFTER")
```

Unfortunately, in logs only the first one is displayed

```
2021-07-07 09:59:43 - (conftest.py:  35)   MainThread [INFO] asserting that <Function test_B0_0_000>, row:96, 1==1, 1 == 1
                                                                           +1
                                                                           -1
2021-07-07 09:59:43 - (myfunct.py:  12)   MainThread [INFO] BEFORE
2021-07-07 09:59:43 - (myfunct.py:  14)   MainThread [INFO] AFTER
```

Is there a way to display also the second assert?
Riccardo

**Comment by Zac-HD** [comment]
I'd guess that Pytest just isn't rewriting the assertion(s) in your utils package.  What happens if you define the function inline in your test file?

(FYI inlining everything is generally a good step in reporting minimal examples; and if it doesn't work that's useful information to include in the report)

[See here for the docs](https://docs.pytest.org/en/6.2.x/assert.html#assertion-introspection-details), which suggest that "you can manually enable assertion rewriting for an imported module by calling `register_assert_rewrite` before you import it (a good place to do that is in your root conftest.py)."

**Comment by ric79** [comment]
Thanks. This solved my problem!
