### ISSUE TITLE
Improve pytest.warns() docs to clarify difference with catch_warnings()

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest#9002]
We should add some stdlib links to the relevant docs:

- If you want to get a list of warnings, but no error if no warnings were emitted, use [`warnings.catch_warnings()`](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings)
- To say "any warning here is unexpected / an error", use `with catch_warnings(): simplefilter("error"); ...`

I didn't *intend* to break anything, but nor did I consider that people might be using `pytest.warns()` like `warnings.catch_warnings()`.  My apologies for the inconvenience!

_Originally posted by @Zac-HD in https://github.com/pytest-dev/pytest/issues/8677#issuecomment-898130136_

**Comment by Zac-HD** [comment]
Per #9386 we should also expand the deprecation message to suggest use of stdlib `catch_warnings()` for cases where you either allow or expect no warnings to be emitted.

**Comment by The-Compiler** [comment]
I wonder if we should instead provide some kind of pytest convenience API for this case, though? I imagine something like `pytest.warns(optional=True)` or perhaps `pytest.warns(raising=False)`. This would make it a bit easier for people to migrate and probably also make our deprecation guide simpler.

**Comment by WarrenWeckesser** [comment]
FYI: We need to replace a few occurrences of `pytest.warns(None)` in the SciPy tests (see https://github.com/scipy/scipy/issues/15186), and we observe the same issue as noted in https://github.com/pytest-dev/pytest/issues/9386: `pytest.warns()` in 7.0.0rc1 does not work the same as `pytest.warns(None)` in 6.2.5, so the message in the deprecation warning is a bit misleading.

**Comment by bashtage** [comment]
It would be very helpful if the best way to handle runtime-dependent warnings is documented.  In a nutshell, we have parameterized tests that warn under some parameterizations and do not warn under others.  We have been using something like

```python
expected_warn = FutureWarning if param == "n" else None
with pytest.warns(expected_warn):
    ...
```

This worked in the sense that it would ensure that FutureWarning was raised when it should even if it silenced any warning otherwise, and so was not strict.  

What is the best way to handle a situation like this?  I had thought of 


```
expected_warn = [FutureWarning] if param == "n" else []
with pytest.warns(*expected_warn):
    ...
```
but it seems a bit unnatural, and I'm not even sure this would work given this thread and others.

**Comment by nicoddemus** [comment]
Please see https://github.com/pytest-dev/pytest/issues/9404.

**Comment by nicoddemus** [comment]
Fixed by https://github.com/pytest-dev/pytest/pull/9495
