### ISSUE TITLE
Use Sphinx `intersphinx` or `extlinks` for common cross-refs, not full URLs

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest#9081]
Via https://github.com/pytest-dev/pytest/pull/9041#issuecomment-914109689 - these changes make our docs easier to read in plaintext, and give us a single location to update if something we're referencing moves (e.g. the docs for an upstream package).  Specifically, let's:

- [ ] Ensure that we're using `intersphinx` for all our frequently-referenced docs
- [ ] Check for manual links which could use `intersphinx` in CI
      (using something like @hoefling's special builder, which I want to copy for my projects)
- [ ] Use `extlinks` for other patterns like Pytest issues and PRs

See https://github.com/sphinx-doc/sphinx/pull/9626 for upstream progress on this; we'll adopt the checker once it's released by Sphinx ✨

**Comment by nicoddemus** [comment]
Just a note: see if it runs fast enough that we can include the check in pre-commit, instead of just the CI.

**Comment by Zac-HD** [comment]
@hoefling - it looks like this is done, but you're the expert - should we close the issue?  If not, what additional changes do you want to see?

**Comment by hoefling** [comment]
@Zac-HD I think it can be safely closed. The only thing I was waiting for was the approval of sphinx-doc/sphinx#9626, but now I see that it got outdated. I have to rebase it onto mainline and ask @tkomiya for another review and whether it can still be included in `Sphinx==4.4`. The bump of Sphinx itself then is a different story and this issue is largely unaffected by that.

**Comment by Zac-HD** [comment]
Thanks for all your work on this 💖
