### ISSUE TITLE
test package conflicts with single python file when using --doctest-modules flag

### ISSUE THREAD

**Issue by kfrydel** [pytest-dev/pytest#9228]
If there is a package containing modules with tests and a single python file that name is the same as the package name then pytest fails during collecting tests if it is run with option `--doctest-modules`. The error is `ModuleNotFoundError: No module named 'something.test_app'; 'something' is not a package` (in this example `something` is the common name of package and the file).

Minimal example:

```
$ find .
.
./conftest.py
./app
./app/tests
./app/tests/something
./app/tests/something/__init__.py
./app/tests/something/test_app.py
./something.py

$ cat ./conftest.py  # empty

$ cat ./app/tests/something/__init__.py  # empty

$ cat ./app/tests/something/test_app.py
def test_sum():
    assert 2 + 2 == 4

$ cat ./something.py  # empty

$ pip freeze
attrs==21.2.0
importlib-metadata==4.8.1
iniconfig==1.1.1
packaging==21.0
pluggy==1.0.0
py==1.10.0
pyparsing==2.4.7
pytest==6.2.5
toml==0.10.2
typing-extensions==3.10.0.2
zipp==3.6.0

$ uname -a
Linux mordor 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ pytest --doctest-modules .
=============================================== test session starts ===============================================
platform linux -- Python 3.7.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /mnt/ssd-2/devel/sf/pytest-config-tets
collected 0 items / 2 errors                                                                                      

===================================================== ERRORS ======================================================
________________________________ ERROR collecting app/tests/something/test_app.py _________________________________
/opt/starfish/python3.7/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:962: in _find_and_load_unlocked
    ???
E   ModuleNotFoundError: No module named 'something.test_app'; 'something' is not a package
________________________________ ERROR collecting app/tests/something/test_app.py _________________________________
ImportError while importing test module '/mnt/ssd-2/devel/sf/pytest-config-tets/app/tests/something/test_app.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/starfish/python3.7/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
E   ModuleNotFoundError: No module named 'something.test_app'; 'something' is not a package
============================================= short test summary info =============================================
ERROR app/tests/something/test_app.py - ModuleNotFoundError: No module named 'something.test_app'; 'something' i...
ERROR app/tests/something/test_app.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================ 2 errors in 0.12s ================================================
```

Running pytest without the flag does not fail:
```
$ pytest .
============================================== test session starts ===============================================
platform linux -- Python 3.7.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /mnt/ssd-2/devel/sf/pytest-config-tets
collected 1 item                                                                                                 

app/tests/something/test_app.py .                                                                          [100%]

=============================================== 1 passed in 0.01s ================================================
```

**Comment by andrewdotn** [comment]
I don’t think this is specific to doctest; if you run `pytest . something.py` you’ll also get an error.

The definitions aren’t the clearest, but let’s use the following terminology:
  - a module is [“a file containing Python definitions and statements”](https://docs.python.org/3/tutorial/modules.html)
  - a package is “a collection of modules” … “`__init__.py` files are required to make Python treat directories containing the file as packages”
For now, let’s ignore the issue of namespace packages, or the ambiguity that the Python Package Index serves up things that are often but not necessarily packages in the above sense.

`something.py`, as a standalone file, is a non-package module. And in `app/tests` there’s also a `something` package that’s not a subpackage of anything else because the `something` directory contains `__init__.py` but its parent directory does not.

In a python program, `import something` can only import one or the other, but not both. Whether you get the package, or the non-package module, is determined by whether `.` or `app/tests` comes first on `sys.path`. pytest needs to be able to import both to run the tests in both, but can’t, hence the error.

To fix this, you could `touch app/tests/__init__.py`, or `rm app/tests/something/__init__.py`.

**Comment by kfrydel** [comment]
Thank you for the reply! It is very helpful. Indeed, in my case, the issue is in fact that `app/tests` is not a package (does not have `__init__.py`` file). Since there is nothing to fix in pytest, I'm closing this ticket.
