### ISSUE TITLE
Removing mock as dependency in favor of the builtin unittest.mock

### ISSUE THREAD

**Issue by Huy-Ngo** [pytest-dev/pytest#9270]
From python 3.3 [mock](https://pypi.org/project/mock/) has been included in the Python standard library as [unittest.mock](https://docs.python.org/dev/library/unittest.mock.html) and pytest only supports python 3.6+. We should therefore migrate to the standard one.

I believe pytest devs are aware of this, since unittest.mock is used  in pytest, but mock hasn't been removed from the dependency list yet.

#### What's the problem this feature will solve?

Less dependency can lead to less complication during installation.

#### Describe the solution you'd like

Ensuring all use of mock is replaced with unittest.mock, then remove mock from dependency list.

**Comment by nicoddemus** [comment]
Hi @Huy-Ngo,

`mock` is not a dependency:

https://github.com/pytest-dev/pytest/blob/842814c96938292ffc6912b2daf2a9e814b48997/setup.cfg#L44-L53

Can you elaborate?

**Comment by McSinyx** [comment]
I believe @Huy-Ngo was referring to the `testing` extra:

https://github.com/pytest-dev/pytest/blob/842814c96938292ffc6912b2daf2a9e814b48997/setup.cfg#L67-L75

**Comment by Huy-Ngo** [comment]
Thanks @McSinyx , that's what I meant

**Comment by nicoddemus** [comment]
Ahh I see thanks for the clarification.

We do have that dependency because we there are tests for compatibility with `mock` from PyPY:

https://github.com/pytest-dev/pytest/blob/49f934618c79465ba960f238d6ed35c151489dd6/testing/python/integration.py#L168

https://github.com/pytest-dev/pytest/blob/49f934618c79465ba960f238d6ed35c151489dd6/testing/python/integration.py#L219

https://github.com/pytest-dev/pytest/blob/49f934618c79465ba960f238d6ed35c151489dd6/testing/python/integration.py#L168

IIRC `unittest.mock` and `mock` might have some differences between them (depending on Python and `mock` versions) which pytest need to be aware of.

Closing for now, feel free to follow up with more. :thumbsup:
