### ISSUE TITLE
How to use skipif-decorators plus parametrized-skipif on a test-function?

### ISSUE THREAD

**Issue by htgoebel** [pytest-dev/pytest#954]
Hi,

I'm trying to decorate a test-function with `skipif`-decorators and `skipif` in `parametrize`. But the `skipif` in `parametrize` seams to overwrite the decorators.

The following scripts shows the effect. 
* `[0-blabla]` and `[2-abcdef]` should run if `T1` and `T2` are defined (ignoring `T3`),
* `[1-lalala]` should run only if  all of `T1`, `T2` and `T3` are defined.

But `[1-lalala]` happens to run as soon as `T3` is defined, even if `T1` and/or `T2` are not defined.

``` python
import pytest
import os

def has(name):
    return pytest.mark.skipif(not bool(os.getenv(name)),
                              reason="requires %s" % name)

parameters = [
    (0, 'blabla'), 
    has("T3")((1, 'lalala')),
    (2, 'abcdef'),
]

@has("T2")
@pytest.mark.parametrize("num, prefix", parameters)
@has("T1")
def test_answer(num, prefix):
    pass
```
And the output is (showing only on case is enough):
```
$ T1= T2= T3=y py.test -v /tmp/test_sample2a.py 
================================ test session starts ================================
platform linux -- Python 3.3.2 -- py-1.4.30 -- pytest-2.7.2 -- /usr/bin/python3
rootdir: /tmp, inifile: 
collected 3 items 

../../tmp/test_sample2a.py::test_answer[0-blabla] SKIPPED
../../tmp/test_sample2a.py::test_answer[1-lalala] PASSED
../../tmp/test_sample2a.py::test_answer[2-abcdef] SKIPPED

======================== 1 passed, 2 skipped in 0.01 seconds ========================
```

I want to have the `skipif` to be tested  for all parameters as decorators, as this seams more expressive for me.

What I'm doing wrong here? How can I achieve this?

Side-notes:

1. `has()` is only an example here, of course. In practice I'm using several `skipif`s predefined in your test-suite (e.g. `skip_if_dynlib_missing('ghostscript')`).
2. I tried different orders of `skipif` and `parametrize` with no success.

**Comment by codewarrior0** [comment]
Since I'm working with @htgoebel on this project, here are a couple of notes:

__Successive skipifs on a function will combine the conditions, but replace the reason.__

When you put `skipif` on a function twice, it adds the condition for the second skipif to the args list for the `skipif` mark, but it replaces the reason for the skip. So the `test_answer` function in the example has a `skipif` mark that looks like this:

`<MarkInfo 'skipif' args=(True, True) kwargs={'reason': 'requires T2'}>`

__skipif on a parameter will completely replace the skipif on the test function.__

The function also has a `parametrize` mark. This means when tests are collected, `CallSpec` objects are generated for each parameter set. The `CallSpec` for the first and third parameter sets have the same `skipif` mark as the function, but the `CallSpec` for the second parameter set has a mark that just looks like this:

`<MarkInfo 'skipif' args=(False,) kwargs={'reason': 'requires T3'}>`

**Comment by RonnyPfannschmidt** [comment]
can you try if this still happens on master?

**Comment by htgoebel** [comment]
How to install the master? `pip install https://github.com/pytest-dev/pytest/archive/master.zip` gives: 
> Make sure you're not using GitHub's tarballs (or similar ones), as those don't contain the necessary metadata. Use PyPI's tarballs instead.

**Comment by RonnyPfannschmidt** [comment]
install from a checkout or use a git url, git archives don't provide metadata

**Comment by The-Compiler** [comment]
You can do `pip install git+https://github.com/pytest-dev/pytest.git`

**Comment by htgoebel** [comment]
`pip install -U git+https://github.com/pytest-dev/pytest.git` worked. Thanks.

Both issues are fixed on master. This is good :-) Thanks.

```
$ PYTHONPATH= T1=x T2=x T3= py.test -rs -v /tmp/test_sample2a.py 
================================ test session starts ================================
platform linux -- Python 3.3.2, pytest-2.7.3.dev356+ng37ed391, py-1.4.30, pluggy-0.3.0 -- /var/tmp/foo/bin/python
rootdir: /tmp, inifile: 
collected 3 items 

../../tmp/test_sample2c.py::test_answer[0-blabla] PASSED
../../tmp/test_sample2c.py::test_answer[1-lalala] SKIPPED
../../tmp/test_sample2c.py::test_answer[2-abcdef] PASSED
============================== short test summary info ==============================
SKIP [1] test_sample2c.py:13: requires T3

======================== 2 passed, 1 skipped in 0.01 seconds ========================
```
