### ISSUE TITLE
rename importorskip to something that indicates it raises a exception and is not a marker

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#9548]
follow-up of #9542 

the name easily leads to false thinking and surprises,

initial  new name ideas:

* `import_or_skip_whole_module`
* `import_or_raise_skip`

additionally we may want to introduce a `import_optional`

**Comment by nicoddemus** [comment]
TBH I'm not sure changing the name will help users at all... one might look at `import_or_raise_skip` and misuse it as a decorator just the same.

The confusion is users using a function as a decorator, not sure there's anything we can do about that really.

**Comment by The-Compiler** [comment]
I agree, I don't think the benefits of renaming it outweigh the drawbacks of a deprecation.

Consider that `pytest.importorskip` is [widely used](https://sourcegraph.com/search?q=context:global+importorskip+count:50000&patternType=literal), yet accidental misuse seems [very rare](https://sourcegraph.com/search?q=context:global+%40pytest.importorskip&patternType=literal) (this search doesn't include `from pytest import importorskip`, because it looks like projects like `PyInstaller` have their own `importorskip` helper, which is indeed intended to be used as decorator).

**Comment by RonnyPfannschmidt** [comment]
closing as reasonable enough name then

thanks for the feedback
