### ISSUE TITLE
`py.test` command is not compatible with `multiprocessing` start-methods other than *fork*

### ISSUE THREAD

**Issue by Nikratio** [pytest-dev/pytest#958]
Currently, it is not possible to use the `py.test` command to run tests that use the `multiprocessing` module with a start-method other than *fork*. This is because the `py.test` script generated by setuptools does not include a `if __name__ == '__main__'` guard:

```
$ cat /usr/bin/py.test-3
#! /usr/bin/python3

import sys
from pkg_resources import load_entry_point
sys.exit(load_entry_point('pytest==2.6.3', 'console_scripts', 'py.test')())
```

This means that as soon as a test tries to spawn a new process, this process starts executing the test-suite itself (the `-s` option is necessary to see the output of the second process):

```
$ py.test-3 test_mp.py -s
============================================== test session starts ==============================================
platform linux -- Python 3.4.2 -- py-1.4.25 -- pytest-2.6.3
collected 1 items 

test_mp.py ============================================== test session starts ==============================================
platform linux -- Python 3.4.2 -- py-1.4.25 -- pytest-2.6.3
collected 1 items 

test_mp.py F
[...]
```

This is easily rectified by using a custom `py.test` command:

```
$ cat run_test.py 
#!/usr/bin/python3
import pytest
import sys
if __name__ == '__main__':
    sys.exit(pytest.main([__file__] + sys.argv[1:]))
$ python3 run_test.py test_mp.py  -s
============================================== test session starts ==============================================
platform linux -- Python 3.4.2 -- py-1.4.25 -- pytest-2.6.3
collected 1 items 

test_mp.py hello
.

=========================================== 1 passed in 0.11 seconds ============================================
```

But it would be much nicer if the standard `py.test` command could be used.

**Comment by RonnyPfannschmidt** [comment]
that's an issue with setuptools/pip as well as multiprocessing - py.test does not make the scripts but use the entry-points feature that existed since way before multiprocessing

also the script should differ these days for 3 main reasons

a) pip creates a different script for wheels (recent releases have those)
b) there is .exe file support on windows
c) pip >7 caches wheels whenever it can

from my POV this is nothing py.test should fix on its own, this should be fixed in pip/setuptools

because proper script creation on win32 is a major pita, at least personally i don't want to be responsible for it

**Comment by nicoddemus** [comment]
Is there anything that can be done by `py.test` at all here? From @RonnyPfannschmidt's, explanation I gather that nothing can be done and we should close this. Is this correct?

**Comment by RonnyPfannschmidt** [comment]
Workaround might be something like `pyhon -m pytest`

**Comment by Nikratio** [comment]
Reported at https://bitbucket.org/pypa/setuptools/issues/443/
