### ISSUE TITLE
Command line arguments don't work for pytester plugin 

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/pytest#968]
Because it's not active by default arguments like `--runpytest=subprocess` are not recognized:

```
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --runpytest=subprocess
  inifile: /home/ionel/osp/pytest-cov/setup.cfg
  rootdir: /home/ionel/osp/pytest-cov
```

Maybe the argument parsing for pytester should be moved in core?

**Comment by nicoddemus** [comment]
`_pytester` is not loaded by default because it is only useful for plugin authors. Besides the little import time cost, it would also appear in the list of plugins, so this might seem strange for the regular user. To workaround that you have to pass `-p pytester` in the command line (or in your `pytest.ini`).

(Based on your recent commits into `pytest-cov` I'm sure you are aware of that, but I'm writing this anyway for the benefit of those who don't have this background :smile: )

Just moving the options to the core wouldn't be enough, as something (still in core) would have to see that `pytester`-related options are set, and then load `pytester`... I'm not sure it is worth the hassle, specially because `pytester` is meant for plugin authors only. What do you think?

**Comment by ionelmc** [comment]
I don't want it that bad, using '-p' seems reasonable.

Though there's one additional problem, on 2.7 there's no `--runpytest` argument. I have to create this workaround in a `conftest.py` to make the tests run on 2.7:

```
def pytest_configure(config):
    config.runpytest = 'subprocess'
```

Would be worth to at least document this.

**Comment by nicoddemus** [comment]
I think pytester itself deserves some documentation... I think we should open a new issue for it, and then of course `--runpytest` could be documented properly. What do you think?

**Comment by ionelmc** [comment]
I agree but I don't wanna do it, just slowly learning what in that plugin :grin:

**Comment by nicoddemus** [comment]
OK, created #971 :smile:
