### ISSUE TITLE
use more unittesting techniques for py.tests own testsuite

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest#984]
we use acceptance tests very dominantly, and the larger the feature set gets the more it's apparent,
that bits are harder than necessary to test in isolation

i stranded on parts of this, when i tried to switch a part of the cache testsuite to unit-testing and ran into the need for lots of relatively senseless mocking that would directly de-value the tests compared to a acceptance test

**Comment by nicoddemus** [comment]
I agree with that sentiment.

Wouldn't be better to send an email to the mailing list instead of creating an issue though? I mean, I don't see any PR being opened that would effectively close this issue and mark it as "done". IMHO, it feels more like a guideline for core developers to agree on and keep in mind for future tests.

**Comment by RonnyPfannschmidt** [comment]
closing as its more of a discussion/small pull requests item
