### ISSUE TITLE
pytest.approx fails to print representation of tuples

### ISSUE THREAD

**Issue by akitaev** [pytest-dev/pytest#9917]
Hi,
This looks like a bug in pytest.approx

a = (1+0j, 2+0j)
b = (1, 2.2)

def test_ab():
    assert a == pytest.approx(b, abs=0.01)

E       AssertionError: assert ((1+0j), (2+0j)) == approx((1 ± 1....2 ± 1.0e-02))
E         (pytest_assertion plugin: representation of details failed: /opt/anaconda3/envs/py310/lib/python3.10/site-packages/_pytest/python_api.py:331: TypeError: object of type 'ApproxScalar' has no len().
E          Probably an object has a faulty __repr__.)

Converting the tuples to numpy arrays helps.

(pytest 7.1.2, python 3.10.4)

**Comment by ZachOBrien** [comment]
I was able to reproduce this bug with pytest=7.1.2 and python=3.10.4.

It seems that the intended behavior on line 329 of `_pytest/python_api.py` is for a collection of `ApproxScalar`s to be returned via mapping `self._approx_scalar` over an arbitrary depth collection of scalars.

But in this case, `_recursive_list_map` receives a tuple instead of a list and just applies `self._approx_scalar` to the tuple, not the tuple's elements:

```python
# _pytest/python_api.py line 329
approx_side_as_map = _recursive_list_map(self._approx_scalar, self.expected)  # self.expected is a tuple: (1, 2.2)
number_of_elements = len(approx_side_as_map)  # approx_side_as_map is an ApproxScalar with no __len__()
```

```python
# _pytest/python_api.py line 136
def _recursive_list_map(f, x):
    if isinstance(x, list):   # This is False, because x is a tuple
        return [_recursive_list_map(f, xi) for xi in x]
    else:
        return f(x)  # You get an ApproxScalar(tuple), not a tuple with elements converted to ApproxScalar
```

So we have `approx_side_as_map` is an `ApproxScalar`. This causes the call to `len` to fail.

I could take a shot at fixing this.
